### PR TITLE
Fix API client IP logging

### LINKED ISSUE #4998: API IP address validation fails incorrectly
**Describe the bug**
Arkansas discovered two issues with the API authentication after deploying 1.27.0:
- Civiform is looking at the IP of the load balancer again, even with the client_ip_type flag set to FORWARDED
- It’s also not matching the ip address range correctly. it’s saying 10.0.102.126 is not in 10.0.0.0/8, but it is

The error log when accessing with a key that should be in range is:
```
[[33mwarn[0m] a.ApiAuthenticator - UnauthorizedApiRequest(resource: "/api/v1/checkAuth", ip: "[10.0.102.126](http://10.0.102.126/)", cause: "IP[ 10.0.102.126](http://10.0.102.126/) not in allowed range for key ID: AjV+la0hDIdTWrNqEfGU5Q==")
```

The allowed range for that key is `10.0.0.0/8`, so it should be working.

Additionally:
- Turning off IP address validation allows the keys to work.
- We confirmed that Arkansas' ECS has the `CLIENT_IP_TYPE` variable set to `FORWARDED` using these steps:
  ```
  - Go to Elastic Container Service (ECS)
  - On left nav click `Task definitions`
  - Click on your staging task definition
  - Click on (probably the only) Task definition: revision
  - Click on the JSON tab
  - Click the `Download JSON` button
  - Edit the download file and replace any secret values with empty strings
  ```
- Matthew Sparks at Arkansas reported that that an API key was working in the last few weeks. Awaiting confirmation that it was using external IP addresses and not the IP addresses of the load balancer.

### PR DESCRIPTION
**Pull request by avaleske**
### Description

Updates API logging to log the correct client IP address, and adds additional details to error logs.

Additional details that are now logged for 401 errors are:
- The `CLIENT_IP_TYPE`
- The value of the `X-Forwarded-For` header
- The allowed subnet set for the key.

Also adds additional tests for the logs, and requests with the `X-Forwarded-For` header set.

## Release notes

Updates API logging to log the correct client IP address, as well as additional debugging information.

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
- [n/a] Extended the README / documentation, if necessary

#### User visible changes

n/a

#### New Features

n/a

### Issue(s) this completes

Fixes #4998

### CODE REVIEW

**Comment by avaleske** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5009** <a href="https://app.graphite.dev/github/pr/civiform/civiform/5009" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/civiform/civiform/5009?utm_source=stack-comment).

File: server/app/auth/ApiAuthenticator.java [hunk 1]
```diff
@@ -100,11 +100,13 @@ public void validate(Credentials rawCredentials, WebContext context, SessionStor
...
     }
 
-    if (!isAllowedIp(apiKey, resolveClientIp(context))) {
+    String resolvedIp = resolveClientIp(context);
+    if (!isAllowedIp(apiKey, resolvedIp)) {
       throwUnauthorized(
           context,
           String.format(
-              "IP %s not in allowed range for key ID: %s", context.getRemoteAddr(), keyId));
+              "Resolved IP %s is not in allowed range for key ID: %s, which is \"%s\"",
```
Comment (avaleske) [inline server/app/auth/ApiAuthenticator.java:108]: I added the allowed subnet range to the log for debugging convenience, but lmk if you think it shouldn't be included.

Comment (bion) [reply server/app/auth/ApiAuthenticator.java:108]: Fine to include it. If an attacker has access to server logs there are bigger problems

**Review by bion — APPROVED** [review]
