### PR TITLE
Vary program filter chip HTML element ids

### LINKED ISSUE #8632: All the program filter chips have the same id
**Describe the bug**
All the program filter chip `div` elements have the same id of `filter-chip`, which is invalid html.

**Expected behavior**
Either add a distinguishing word to the id or remove the ids from the `div` elements if they aren't needed.

### PR DESCRIPTION
**Pull request by melanie-exygy**
### Description

Varying program filter chip HTML element ids so that we have valid HTML.
  
### Issue(s) this completes

Fixes #8632

### CODE REVIEW

File: server/app/views/applicant/ProgramIndexView.java [hunk 1]
```diff
@@ -603,7 +603,7 @@ private FormTag renderCategoryFilterChips(
                         relevantCategories,
                         category ->
                             div()
-                                .withId("filter-chip")
+                                .withId("filter-chip-" + category)
```
Comment (gwendolyngoetz) [inline server/app/views/applicant/ProgramIndexView.java:606]: (question, blocking) Can the categories have spaces or non-alphanumeric characters? If yes, they should be replaced with `-` or `_`.

Comment (melanie-exygy) [reply server/app/views/applicant/ProgramIndexView.java:606]: Right now, all ten categories are a single word, but I can see the value of future-proofing this.  Will add the transformation logic.

Comment (melanie-exygy) [reply server/app/views/applicant/ProgramIndexView.java]: Done

**Review by gwendolyngoetz — APPROVED** [review]
