### PR TITLE
Separate enumerator values by semi-colon

### LINKED ISSUE #3934: Enumerator Names difficult to decipher
**Describe the bug**
As a Program Admin when reviewing applications within the browser (that is, NOT in the CSV export), the names in the enumerator are difficult to decipher. There is no comma or semi color or line return to show that there are multiple people. It is a string of names on one line. 

**To Reproduce**

1. Login as a Program Admin
2. Click on an application that has multiple household members (i.e. there are multiple names entered in the enumerator question)
3. See that the names appear in one line, difficult to decipher

**Expected behavior**
I would expect there to be some kind of "break" between names; such as a comma, semi colon or line return.

**Screenshots**
Included

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by swatkat1**
### Description

Adding list separator i.e. semi-colon between values in an Enum question answer.

## Release notes

Adding list separator i.e. semi-colon between values in an Enum question answer.

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [x] Manually tested at 200% size
- [x] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes #3934
### Screenshot
image

### CODE REVIEW

**Comment by shanemc-goog** [comment]
@swatkat1 is there a reason semicolon was chosen over comma?  I would think comma is a more common expectation.

@mferhut thoughts?

**Comment by mferhut** [comment]
Both can work. Commas usually used for smaller separations and semicolons to show bigger separations.

eg.   Spring, Winter    vs.      Spring; Winter

**Comment by shanemc-goog** [comment]
Would you mind updating the description to be more a little more specific like "Separate enumerator values by semi-colon"

File: server/test/services/export/PdfExporterTest.java [hunk 1]
```diff
@@ -227,7 +227,7 @@ public void statusTrackingDisabled() throws IOException, DocumentException {
           + "-- my-file-key UPLOADED (click to download) --\n"
           + "Answered on : 1969-12-31\n"
           + "applicant household members\n"
-          + "item1\n"
+          + "item1;\n"
```
Comment (shanemc-goog) [inline server/test/services/export/PdfExporterTest.java:230]: I don't think we want ; here as there's visual newline separators already

**Comment by shanemc-goog** [comment]
@swatkat1 I think we need to take a different approach rather than changing the value you currently are as it has a lot of downstream implications including I imagine CSV files.

FWIW the Applicant view changes the display to have \<BR\>line breaks, I think the Admin view should be able to do the same thing even if it's using ; instead of \<BR\>

File: server/test/services/export/PdfExporterTest.java (hunk 1 above)
Comment (swatkat1) [reply server/test/services/export/PdfExporterTest.java:230]: \n isn't a newline in HTML, it's just a space. Any series of whitespace characters in HTML is treated as one space. So Admins don't know when one name ends and another name begins.

Comment (shanemc-goog) [reply server/test/services/export/PdfExporterTest.java:230]: This is the PDF test though.  I assume in the PDF the newlines are rendered as newlines; such that now they will have semicolons after them

Comment (swatkat1) [reply server/test/services/export/PdfExporterTest.java]: have changed only the UI now. Replaced "\n" with "; "

**Review by shanemc-goog — APPROVED** [review]
