### PR TITLE
Removing logger.error for phone question formatting errors

### LINKED ISSUE #5258: PhoneQuestion Logging Erroneous Errors
### Errors being generated on the review page
The application review page is causing errors to be logged by the Phone Question type.

This is the [error being logged](https://github.com/civiform/civiform/blob/8b273dc0f45e8be2365402cadd1d5db4abf967a8/server/app/services/applicant/question/PhoneQuestion.java#L126C1-L130).

You don't have to fill out the application, just load the initial starting point.

###  Don't log application data
Additionally we should not include getPhoneNumberValue in the logging message in order to keep applicant data from ending up in the logs.

### Log Level
The `getAnswerString` method looks to rely on the try/catch to determin if the value is valid. If it's not valid it throws, we eat the exception, and use a placeholder string. I don't think this probably needs to be logging at all then. If we keep the logging it should be lowered to warning at the highest and not error. Trace or info may be more appropriate. Since it's being handled having it as error make reviewing the logs more noisy for unhandled errors.

## To Reproduce

- As Admin
    - Create a new question of phone type
    - Create a new program
    - Add phone type question to program
   - Publish
   - Logout
- As Applicant
    - Apply to program as quest
    - Errors logged here on the program review page

**Expected behavior**
- Don't log applicant a data
- Lower the log level
- Don't generate errors on the program review page.

### PR DESCRIPTION
**Pull request by swatkat1**
### Description

Updating logger.error to logger.warn for phone formatting errors

#### General

Read the full guidelines for PRs [here](https://docs.civiform.us/contributor-guide/developer-guide/technical-contribution-guide#guidelines-for-pull-requests)

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #5258

### CODE REVIEW

File: server/app/services/applicant/question/PhoneQuestion.java [hunk 1]
```diff
@@ -123,12 +120,7 @@ public String getAnswerString() {
               getPhoneNumberValue().orElse(""), getCountryCodeValue().orElse(""));
       return PHONE_NUMBER_UTIL.format(phoneNumber, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL);
     } catch (NumberParseException e) {
-      logger.error(
-          "Unable to retrieve or parse phone number "
-              + getPhoneNumberValue().orElse("")
-              + "for country_code "
-              + getCountryCodeValue().orElse(""));
+      return "-";
```
Comment (gwendolyngoetz) [inline server/app/services/applicant/question/PhoneQuestion.java:123]: Blocking: Can you add a javadoc comment that says `Returns formatted phone number or defaults to "-" if formatting fails. Format example: __ADD_EXAMPLE_HERE__` and replace that placeholder with an actual example of the formatted number.

Comment (swatkat1) [reply server/app/services/applicant/question/PhoneQuestion.java:126]: done

**Review by gwendolyngoetz — APPROVED** [review]
