### PR TITLE
Durable job for pre compute eligibility

### LINKED ISSUE #10070: The visibility editor when editing a screen's visibility as a civiform admin shows an eligibility message field
**Describe the bug**
As a civiform admin, when you edit the visibility of a screen, there is an option to include an eligibility message.

**To Reproduce**

1. Log in as an admin
2. Go to a program
3. Create a new screen or navigate to an existing screen
4. Select 'Edit visibility condition'
5. See the 'eligibility message' field

**Expected behavior**
There is no eligibility message field because this is the visibility editing.

**Screenshots**
Image

**Desktop (please complete the following information):**

- MacOS
- Chrome

### PR DESCRIPTION
**Pull request by azhangggggg**
### Description

We added a column `eligibility_determination` to application table while `eligibility_determination` value for existing applications defaulted to `NOT_COMPUTED`
This durable job is to calculate `eligibility_determination` of existing applications. We will run this job every Sunday 2AM till all the existing applications are handled.

Step 4 of this [TDD](https://docs.google.com/document/d/1jsGEv1m9Ky2mbEbvTyZUbplFaPEiwNxopWPjm_XaRXs/edit?tab=t.0#heading=h.a2pzjye02740)

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`

#### Durable jobs

Read the docs [here](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates)

- [x] Assigned two reviewers
- [ ] Included a rollback plan and a job to undo the data changes if appropriate

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Part of #8852

### CODE REVIEW

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+  @Override
+  public void run() {
+    logger.info("Starting job to calculate eligibility determination.");
+
+    try (Transaction jobTransaction = database.beginTransaction()) {
+      String filter =
+          """
+          eligibility_determination = 'NOT_COMPUTED'
+          """;
+      try (var query = database.find(ApplicationModel.class).where().raw(filter).findIterate()) {
```
Comment (gwendolyngoetz) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:54]: (blocking) This should also filter for applications that have `LifecycleStage.Active` or `LifecycleStage.Obsolete`. That should cut down on a lot of empty draft applications.

It would be nice to not have to do obsoleted records as they are superseded by the active application, but they are returned in the API. Unless the PRD/TDD indicates we can skip them best to include them.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+            ReadOnlyApplicantProgramService roAppProgramService =
+                applicantService.getReadOnlyApplicantProgramService(application, programDefinition);
+            EligibilityDetermination eligibilityDetermination =
+                applicantService.calculateEligibilityDetermination(
+                    programDefinition, roAppProgramService);
+            application.setEligibilityDetermination(eligibilityDetermination);
+            application.save();
+            jobTransaction.commit();
+          } catch (RuntimeException e) {
+            logger.error(e.getMessage(), e);
```
Comment (gwendolyngoetz) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:71]: (blocking) Can you add the application id to the error message.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+            ProgramModel pm = application.getProgram();
+            ProgramDefinition programDefinition = pm.getProgramDefinition();
+            ReadOnlyApplicantProgramService roAppProgramService =
+                applicantService.getReadOnlyApplicantProgramService(application, programDefinition);
+            EligibilityDetermination eligibilityDetermination =
+                applicantService.calculateEligibilityDetermination(
+                    programDefinition, roAppProgramService);
+            application.setEligibilityDetermination(eligibilityDetermination);
+            application.save();
+            jobTransaction.commit();
```
Comment (gwendolyngoetz) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:69]: (blocking) I believe this will throw when you try to commit the second application since the transaction is started outside the loop.

**Review by gwendolyngoetz — DISMISSED** [review]
Do you have a sense of how long it would take to run a large chunk of records. Filtering out the drafts will significantly help, but it would be good to have a rough idea of how long to expect this to run against a prod database as the startup jobs block the Civiform from finishing loading.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 3 above)
Comment (shane-exygy) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:69]: Anna you manually tested this correct?  I assume you didn't see Gwen's suggested error?

I agree it seems like this shouldn't work.

Comment (shane-exygy) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:69]: Sorry correction, I think the expected behavior is that subsequent commit() are no-ops, so I would think only the first record is being changed.

Comment (shane-exygy) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:69]: In reading move I think subsequent calls may be no-ops which would imply that only the first Application is updated.  But the test seems to say otherwise.

File: server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+    ApplicationModel firstApp =
+        resourceCreator.insertActiveApplication(
+            resourceCreator.insertApplicantWithAccount(), program);
+    ApplicationModel secondApp =
+        resourceCreator.insertActiveApplication(
+            resourceCreator.insertApplicantWithAccount(), program);
+    ApplicationModel thirdApp =
+        resourceCreator.insertActiveApplication(
+            resourceCreator.insertApplicantWithAccount(), program);
+
```
Comment (shane-exygy) [inline server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java:103]: **issue:** Verify the eligibility Determination is the expected default value to ensure it is't NO_ELIGIBILITY_CRITERIA from the start.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 3 above)
Comment (azhangggggg) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:69]: Yes I've manually tested this with multiple applications. I didn't see suggested error. But looking over your suggestions now.

Comment (azhangggggg) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java]: Yeah you're right it was throwing an exception. I didn't notice it in the log cuz the applications were executed correctly. Made changes to code to avoid the exception. Good catch!

Screenshot 2025-04-23 at 10 38 59 AM
Screenshot 2025-04-23 at 10 41 12 AM
Screenshot 2025-04-23 at 10 41 28 AM

File: server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java (hunk 4 above)
Comment (azhangggggg) [reply server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java:109]: Added verifying the eligibility determination step before the job ran.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 1 above)
Comment (auzlee) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:57]: +1

File: server/app/modules/DurableJobModule.java [hunk 5]
```diff
@@ -150,6 +153,13 @@ public DurableJobRegistry provideRecurringDurableJobRegistry(
                 publicStorageClient, versionRepository, persistedDurableJob),
         new RecurringJobExecutionTimeResolvers.ThirdOfMonth2Am());
 
+    durableJobRegistry.register(
+        DurableJobName.CALCULATE_ELIGIBILITY_DETERMINATION_JOB,
+        JobType.RECURRING,
+        persistedDurableJob ->
+            new CalculateEligibilityDeterminationJob(applicantService, persistedDurableJob),
+        new RecurringJobExecutionTimeResolvers.Sunday2Am());
```
Comment (auzlee) [inline server/app/modules/DurableJobModule.java:161]: iiuc this is going to process 5000 applications per week. We should either up the limit, if we determine that it won't slow down the server for a long time, or make a "daily at 3am" or "every 3 hours at :23" TimeResolver so this doesn't take months to work its way through all the old applications.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 1 above)
Comment (auzlee) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:57]: (also not blocking at all but it should be possible to build the filter in the ebeans syntax instead of as a raw strong)

File: server/app/modules/DurableJobModule.java (hunk 5 above)
Comment (gwendolyngoetz) [reply server/app/modules/DurableJobModule.java:161]: We don't need to limit the job to 5000. Only one instance of the job will run at a time in the background.

Do do that something like would work:

```
while true:
  begin tx
  find applications
    if hasNext is false
      break exiting outer while
  iterate batch of n applications
  save    
  commit/rollback where needed.
```

You can also choose to end the job if too many errors have counted up which might indicate a bigger problem.

Comment (shane-exygy) [reply server/app/modules/DurableJobModule.java:161]: @azhangggggg does the PR description need updating?  It mentions 5k still

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+            ProgramDefinition programDefinition = pm.getProgramDefinition();
+            ReadOnlyApplicantProgramService roAppProgramService =
+                applicantService.getReadOnlyApplicantProgramService(application, programDefinition);
+            EligibilityDetermination eligibilityDetermination =
+                applicantService.calculateEligibilityDetermination(
+                    programDefinition, roAppProgramService);
+            application.setEligibilityDetermination(eligibilityDetermination);
+            application.save();
+          } catch (RuntimeException e) {
+            errorCount++;
```
Comment (shane-exygy) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:73]: **suggestion (non-blocking):** Consider stopping after N errors, maybe 10.  If we're getting a lot of Runtime errors that is likely an indication of a larger issue that should be addressed before continuing to process more records.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+            logger.error("Error message {}", e.getMessage());
+          }
+        }
+      }
+
+      if (errorCount == 0) {
+        logger.info("Job succeeded");
```
Comment (shane-exygy) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:80]: **suggestion:** Swap these two lines so we know commit() succeeded before logging it.

File: server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+import org.junit.Before;
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.mockito.junit.MockitoJUnitRunner;
+import repository.ResetPostgres;
+import services.applicant.ApplicantService;
+import services.applications.ApplicationService;
+
+@RunWith(MockitoJUnitRunner.class)
+public class CalculateEligibilityDeterminationTest extends ResetPostgres {
```
[the remark this answers is not in the document]
Comment (azhangggggg) [reply server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java:23]: The reason that we're getting NO_ELIGIBILITY_CRITERIA is that none of the test programs has an eligibility criteria set. But it does verify that [CalculateEligibilityDetermination()](https://github.com/civiform/civiform/blob/b2d86f32d7523f30543b4438a3215e0aabd8164c/server/app/services/applicant/ApplicantService.java#L493) was called. There are other tests like [this](https://github.com/civiform/civiform/blob/6c209846a280ccc40b52abae42560583c2292387/server/test/services/applicant/ApplicantServiceTest.java#L1775) testing CalculateEligibilityDetermination() in more details. For this PR we're just trying to see if the method was called imo.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 2 above)
Comment (azhangggggg) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java]: yes, done

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 9]
```diff
@@ -0,0 +1,97 @@
...
+          }
+        }
+      }
+
+      if (errorCount == 0) {
+        jobTransaction.commit();
+        logger.info("Job succeeded");
+      } else {
+        logger.error(
+            "Failed to compute eligibility determination for existing applications. Error: {}",
```
Comment (shane-exygy) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:91]: **suggestion:** Since we're stopping after N errors, I'd suggest updating the phrasing to imply that, as well indicate that the value is an error count "Error: 9" is not that readable.

Perhaps: "Stopping early after {} errors."

File: server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (shane-exygy) [reply server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java:23]: I think we need to ensure that a valid eligibility update is done at least once.  Otherwise how does the test ensure changes to the underlying code don't have a bug that simply sets everything to NO_ELIGIBILITY_CRITERIA, or the loop accidentally uses the first application in every loop etc.

The test shouldn't care how the operation is done (Eg verify a method is called), but that the correct outcome is achieved, and we have no situation in which eligibility is actually computed here.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+            ProgramDefinition programDefinition = pm.getProgramDefinition();
+            ReadOnlyApplicantProgramService roAppProgramService =
+                applicantService.getReadOnlyApplicantProgramService(application, programDefinition);
+            EligibilityDetermination eligibilityDetermination =
+                applicantService.calculateEligibilityDetermination(
+                    programDefinition, roAppProgramService);
+            application.setEligibilityDetermination(eligibilityDetermination);
+            application.save();
+          } catch (RuntimeException e) {
+            errorCount++;
```
Comment (shane-exygy) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:75]: **issue (blocking):** Most of these error handling lines aren't tested.

File: server/app/modules/DurableJobModule.java (hunk 5 above)
Comment (shane-exygy) [reply server/app/modules/DurableJobModule.java:161]: I think it's still not right

"We will run this job once and have it handle as many applications in batches as it can in one run."

As I understand it .commit() is only called if there are 0 errors, so from the outside we're not updating applications in batches, they'll be updated all or nothing.  and if there's an error it'll have to be run again assuming the error is resolvable with a re-run.

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 11]
```diff
@@ -0,0 +1,114 @@
...
+  public PersistedDurableJobModel getPersistedDurableJob() {
+    return persistedDurableJobModel;
+  }
+
+  @Override
+  public void run() {
+    logger.info("Starting job to calculate eligibility determination.");
+
+    try (Transaction jobTransaction = database.beginTransaction(TxIsolation.SERIALIZABLE)) {
+      jobTransaction.setBatchMode(true);
```
Comment (shane-exygy) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:52]: **note (non-blocking):** FYI the default batch size is 20, you may want to increase that via `jobTransaction.setBatchSize()`

"The batch buffer size default value is set via databaseConfig.persistBatchSize which defaults to 20."

https://ebean.io/docs/transactions/batch

**Review by shane-exygy — APPROVED** [review]

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 11 above)
Comment (azhangggggg) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:52]: Setting the batch size to 50, avoiding increasing memory usage too much.

**Review by shane-exygy — APPROVED** [review]
