### PR TITLE
Make IT_EMAIL_ADDRESS server setting ADMIN_READABLE

### LINKED ISSUE #11601: Make IT_EMAIL_ADDRESS admin_readable
`IT_EMAIL_ADDRESS` is currently admin_writeable and most places in the code base that reference it pass in the request and pull it from the Settings Manifest. Durable jobs, however, reference it directly from the config file and don't get the updated value from the admin settings UI. This value doesn't change very often, so engineers decided the short term fix should be to make it admin_readable. The work here is to update the mode of the variable in env-var-docs.json and update all the callsites to remove the `request` option passed in. Once it's released, we'll need to call out to govs that they need to add it back into their deploy config files.

---- Former description of bug below ----

**Describe the bug**
Durable jobs are still pulling the value for `IT_EMAIL_ADDRESS` from the config, even though `IT_EMAIL_ADDRESS` is admin writeable so it should be pulling the value from the settings manifest.

Here is where we're referencing it from the config: https://github.com/civiform/civiform/blob/cc45bb74df14b29eef232b6e9078abd5f4a1ba46/server/app/durablejobs/AbstractDurableJobRunner.java#L56

Here is the settings manifest method we should be using instead: https://github.com/civiform/civiform/blob/cc45bb74df14b29eef232b6e9078abd5f4a1ba46/server/app/durablejobs/AbstractDurableJobRunner.java#L56

**Expected behavior**
When a durable job fails, admin should be emailed at the value they set for `IT_EMAIL_ADDRESS` in the admin settings panel.

### PR DESCRIPTION
**Pull request by rockycodes**
### Description

This change updates the `IT_EMAIL_ADDRESS` to be `ADMIN_READABLE` instead of `ADMIN_WRITEABLE`. We want to make this change so that the correct value for `IT_EMAIL_ADDRESS` is referenced in all places.

Changing this server setting to be `ADMIN_READABLE` means it will no longer be editable via the Admin Settings Panel and will need to be set in the deploy config. Please make this obvious when publishing the release that includes this change. Release notes are below.

## Release notes

`IT_EMAIL_ADDRESS` will no longer be able to be set via the Admin Settings Panel and will need to be set in your deployment config. Before upgrading to this release, please make sure `IT_EMAIL_ADDRESS` is set in your deployment config to the correct value.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [ ] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if the primary reviewer is not an admin and this PR includes functionality changes)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Issue(s) this completes

Fixes #11601

### CODE REVIEW

File: server/app/durablejobs/AbstractDurableJobRunner.java [hunk 1]
```diff
@@ -55,7 +55,8 @@ public AbstractDurableJobRunner(
     this.durableJobRegistry = Preconditions.checkNotNull(durableJobRegistry);
     this.itEmailAddress =
         config.getString("it_email_address").isBlank()
-            ? config.getString("support_email_address")
+            // TODO(#11736): Set support_email_address as the fallback email
+            ? "civiform-dev@exygy.com"
```
Comment (rockycodes) [inline server/app/durablejobs/AbstractDurableJobRunner.java:59]: This email is used when a durable job fails, so it's fine for it to come to us. This is the value that was being used as a fallback anyway since we can't pick up the value they set in the config.

**Review by swatkat1 — APPROVED** [review]
Thanks!
