### PR TITLE
Fix Infinite Redirect from IE User Agent

### LINKED ISSUE #10222: IE browser check stuck in redirect loop
We have a filter that checks if the User Agent is Internet Explorer. If you attempt to load the site it's getting in a redirect 

`curl -L -A "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko" -v https://demo.civiform.dev`

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

When a browser user agent is detected to be that of Internet Explorer we redirect to the _unsupported browser page_. However it was discovered that this was in a redirect loop and never working. This was discovered in the logs from a demo site.

This will now not try to start a session for the unsupported browser page and let it load as expected.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

Fixes #10222

### CODE REVIEW

**Review by shane-exygy — APPROVED** [review]

File: server/app/filters/OptionalProfileRoutes.java [hunk 1]
```diff
@@ -10,7 +10,11 @@
 final class OptionalProfileRoutes {
 
   public static ImmutableList<String> routes =
-      ImmutableList.of("/", "/programs", "/applicants/programs");
+      ImmutableList.of(
+          "/",
+          "/programs",
+          "/applicants/programs",
+          controllers.routes.SupportController.handleUnsupportedBrowser().url());
```
Comment (rockycodes) [inline server/app/filters/OptionalProfileRoutes.java:17]: this lgtm and makes me thing we should make the other urls in this list reference the controller url instead of being hard-coded.

**Review by rockycodes — APPROVED** [review]
lgtm!
