### PR TITLE
[Status Migration] - Adding UpdateStatusDefinitions function in ApplicationsStatusRepository 

### LINKED ISSUE #7040: Ensure application status can always be changed to any available status
**Describe the bug**
1. If a submission does not have a status (eg, no default status was set), the submission cannot be changed to a different status. 
2. If a submission has Status A, and Status B was created after the submission was submitted, the submission's status cannot be changed to Status B. 

**Expected behavior**
1. Admins are able to add status to a submission that currently does not have a status. The same status dropdown shows for submissions without a status as for submissions with a status.
2. Admins are able to change a submission to any current status, including statuses created after the submission.

**Additional context**
This is needed as part of our [bulk status updates](https://docs.google.com/document/d/19jETzFmpIHEGfHfEbzqnPwSGmEB-WD-mauhXl5b9CDE/edit) work.

### PR DESCRIPTION
**Pull request by swatkat1**
### Description

Adding UpdateStatusDefinitions function in ApplicationsStatusRepository.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)

### Issue(s) this completes

Fixes #7040

### CODE REVIEW

File: server/app/repository/ApplicationStatusesRepository.java [hunk 1]
```diff
@@ -52,4 +52,22 @@ public List<StatusDefinitions> lookupListOfObsoleteStatusDefinitions(String prog
...
+        .eq("program_name", programName)
+        .and()
+        .eq("status_definitions_lifecycle_stage", StatusDefinitionsLifecycleStage.ACTIVE)
+        .update();
+
+    // create new status
+    ApplicationStatusesModel newStatusDefinition =
+        new ApplicationStatusesModel(
+            programName, statusDefinitions, StatusDefinitionsLifecycleStage.ACTIVE);
+    newStatusDefinition.save();
```
Comment (avaleske) [inline server/app/repository/ApplicationStatusesRepository.java:71]: **issue**: Can we wrap this in a transaction so it happens atomically. otherwise a database read between these two writes could end up with unexpected data, like there not being an ACTIVE `StatusDefinitions` for a program.

**Review by avaleske — CHANGES_REQUESTED** [review]

File: server/app/repository/ApplicationStatusesRepository.java (hunk 1 above)
Comment (avaleske) [reply server/app/repository/ApplicationStatusesRepository.java:71]: https://ebean.io/docs/transactions/

Comment (swatkat1) [reply server/app/repository/ApplicationStatusesRepository.java]: Great idea. Done!

File: server/app/repository/ApplicationStatusesRepository.java [hunk 2]
```diff
@@ -52,4 +54,26 @@ public List<StatusDefinitions> lookupListOfObsoleteStatusDefinitions(String prog
         .map(ApplicationStatusesModel::getStatusDefinitions)
         .collect(Collectors.toList());
   }
+
+  public void updateStatusDefinitions(String programName, StatusDefinitions statusDefinitions) {
```
Comment (avaleske) [inline server/app/repository/ApplicationStatusesRepository.java:58]: **suggestion, optional, not blocking**: Depending on how we're calling this, a single `createOrUpdateStatusDefinitions()` method could make the callsites cleaner.

File: server/test/repository/ApplicationStatusesRepositoryTest.java [hunk 3]
```diff
@@ -85,4 +89,31 @@ public void canQueryForOboseleteApplicationStatuses() {
...
+
+    StatusDefinitions statusDefinitionsResult2 = repo.lookupActiveStatusDefinitions(programName);
+    assertStatusDefinitions(statusDefinitionsResult2, "Reapply");
+  }
+
+  public void assertStatusDefinitions(
+      StatusDefinitions statusDefinitionsResult, String statusText) {
+    assertThat(statusDefinitionsResult.getStatuses().size()).isEqualTo(1);
+    assertThat(statusDefinitionsResult.getStatuses().get(0).statusText()).isEqualTo(statusText);
+  }
```
Comment (avaleske) [inline server/test/repository/ApplicationStatusesRepositoryTest.java:118]: **suggestion, optional, not-blocking**: Tests don't need to follow DRY principles as much as regular code, since the primary goal is readability. imo leaving these asserts in each test, even if the code is repetitive, is better cause it makes it easier to see what the test is doing.

**Review by avaleske — APPROVED** [review]
a few thoughts but overall lgtm!

File: server/test/repository/ApplicationStatusesRepositoryTest.java [hunk 4]
```diff
@@ -85,4 +89,31 @@ public void canQueryForOboseleteApplicationStatuses() {
...
+    ProgramModel program =
+        ProgramBuilder.newActiveProgram("Updateprogram" + uniqueProgramId, "description").build();
+    String programName = program.getProgramDefinition().adminName();
+    StatusDefinitions statusDefinitions = new StatusDefinitions(ImmutableList.of(APPROVED_STATUS));
+    ApplicationStatusesModel applicationStatusesModel =
+        new ApplicationStatusesModel(
+            programName, statusDefinitions, StatusDefinitionsLifecycleStage.ACTIVE);
+    applicationStatusesModel.save();
+    StatusDefinitions statusDefinitionsResult = repo.lookupActiveStatusDefinitions(programName);
+    assertStatusDefinitions(statusDefinitionsResult, "Approved");
```
Comment (avaleske) [inline server/test/repository/ApplicationStatusesRepositoryTest.java:105]: **nit, non-blocking**: I might add a line between lines 103 and 104 to make it clear this is a "pre-assert" step that's a little distinct from the "arrange" step before it.

File: server/test/repository/ApplicationStatusesRepositoryTest.java (hunk 3 above)
Comment (swatkat1) [reply server/test/repository/ApplicationStatusesRepositoryTest.java:118]: I agree with you! Let me move it back into each tests

File: server/app/repository/ApplicationStatusesRepository.java (hunk 2 above)
Comment (swatkat1) [reply server/app/repository/ApplicationStatusesRepository.java:58]: Create has to be different as it would have the update() query.

Comment (avaleske) [reply server/app/repository/ApplicationStatusesRepository.java:58]: Yeah, inside the method it would have check if the statuses existed for the program and, if they did, call update and if they didn't call create.

_very_ optional thought though, I don't know what your callsites for this look like so I don't know if it's easier to hide that complexity in the Repository or let it be at the callsite.
