### PR TITLE
Don't set email as name when creating profiles

### LINKED ISSUE #8344: Logging in with Auth0 will fill email in for the universal name question
**Describe the bug**
When creating an account through auth0, the universal name question gets filled in with email. This is when the user creates an account with a username and password specifically because when signing in with google, a name is provided. 

**To Reproduce**

1. Go to staging or another environment with auth0
2. Click on log in and log in or create an account
3. When redirected back to civiform, click on the PAI proram (or another program with a universal name question)
4. See email in name field

**Expected behavior**
Name doesn't get filled in since there is no name coming from auth provider. Or if the email matches the name when it comes from auth provider, don't set it

**Screenshots**
See name filled in with email
Screenshot 2024-08-15 at 3 19 37 PM

**Additional context**
This was reported by charlotte as something that came up in their user studies. We'd like to fix it before launch.

### PR DESCRIPTION
**Pull request by devin-civi**
### Description

Fixes #8344, we no longer populate applicant name with email if the auth provider fills in the name attribute with the same value as the email attribute. With this change, name is now empty if no name is provided, so we no longer populate an email  in the universal question first name field. Added a new "getApplicantDisplayName" which instead looks for name, and falls back to email if it's not there. 

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [ ] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #8344

### CODE REVIEW

**Comment by devin-civi** [comment]
* **#8557** <a href="https://app.graphite.dev/github/pr/civiform/civiform/8557?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devin-civi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: server/app/models/AccountModel.java [hunk 1]
```diff
@@ -177,14 +177,14 @@ public void removeAdministeredProgram(ProgramDefinition program) {
...
   /**
    * Returns the name, as a string, of the most-recently created Applicant associated with this
-   * Account. There is no particular reason for an Account to have more than one Applicant - this
-   * was a capability we built but did not use - so the ordering is somewhat arbitrary /
-   * unnecessary.
+   * Account. Or the email if no name is associated with the applicant. There is no particular
+   * reason for an Account to have more than one Applicant - this was a capability we built but did
+   * not use - so the ordering is somewhat arbitrary / unnecessary.
    */
   public String getApplicantName() {
```
Comment (devin-civi) [inline server/app/models/AccountModel.java:184]: Hmm, was just taking a quick look before sending this out, and I wonder if I should rename this to getApplicantDisplayName() as well?

**Review by dkatzz — APPROVED** [review]
Do you think its worth adding a browser test in the applicant flow that logs in using auth0 and validates that the email shows as the display name at the top, but when they go to fill out a program with a name question, that question is not pre-filled?

Otherwise this LGTM! Thanks for fixing this - Charlotte will be really excited!
