### PR TITLE
[A11y North Star] Add aria label to footer for application to indicate email link opens in a new tab

### LINKED ISSUE #9917: [a11y] [WCAG 2.4.4]: The screen reader does not announce that a link will open in another tab.
OBSERVED RESULTS:
--
When navigating the TestCity CiviForm page with enable screen reader, the link 'civiform-dev@exygy.com' is read as 'civiform-dev@exygy.com Visited link'. However, when pressing 'Enter' on the link, it opens in a new tab, but the screen reader does not announce that the link will open in a new tab beforehand.

USER IMPACT:
--
The Screen reader users may have difficulty understanding the purpose of a link if it’s not clear from the link text or surrounding context, leading to confusion or frustration.

EXPECTED RESULTS:
--
When navigating the TestCity CiviForm page with enable screen reader, the link 'civiform-dev@exygy.com' should be announced with information that it will open in a new tab, such as 'civiform-dev@exygy.com, opens in a new tab'.

STEPS TO REPRODUCE:
--
0. Enable ChromeVox using "CONTROL+ALT+Z".
1. Go to [TestCity CiviForm](https://ns.civiform.dev/programs)
2. Select english language
3. Apply for "Minimal Sample Program"
4. Select the 'Start an application' button
5. Go through application flow and submit 
6. Locate the link 'For technical support: civiform-dev@exygy.com' in the footer of the page
7. Note that the screen reader announces it only as a link, but when you select it, a new tab will open.

SCREENCAST:
--
- Chromebook+ChromeVox:[Evidence](https://drive.google.com/file/d/1SoqDg00Rk64vyK8eP_Ljho8xA2rXArvQ/view?usp=drive_link&resourcekey=0-F0EMtGBc8Q2ZumfU-_iJvQ)
- Windows+NVDA:[Evidence](https://drive.google.com/file/d/1XNPSvuIj3e6S4SH_G8qWodqnMSi5HWta/view?usp=drive_link&resourcekey=0-AkuaIpUdMzt9NGxijlWaNA)
                                

ADDITIONAL INFORMATION:
--
Same behaviour is observed in Not eligible program page: \
Screencast:Chromebook+Chromevox[here]( https://drive.google.com/file/d/1vpcrxbA1rtOSeCh2rYSwl20hVnHXmL7K/view?usp=drive_link )

**Wcag Rule:**

[WCAG 2.4.4](https://www.w3.org/TR/WCAG22/#link-purpose-in-context)

**Enviroment details:**

Machine: Chromebook Version 13.3

Browser: Chrome (132.0.6834.208 (Official Build) (64-bit))

Machine: Windows 11 Enterprise 23H2

Screen reader: ChromeVox, NVDA

Bug Filling Time: 20 mins

### PR DESCRIPTION
**Pull request by tallulahkay**
### Description

Added an aria-label to the footer email link and new tab program details link on the eligibility page.

Note: Lots of screenshots got updated because the footer is all over!

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`

### Instructions for manual testing

0. Enable a screen reader.
1. Go to Civiform
2. Apply for "Minimal Sample Program"
3. Select the 'Start an application' button
4. Locate the link 'For technical support: [civiform-dev@exygy.com](mailto:civiform-dev@exygy.com)' in the footer of the page
5. Confirm that the screen reader announces it as a link that opens in a new tab

### Issue(s) this completes

Fixes #9917;

### CODE REVIEW

**Review by shane-exygy — APPROVED** [review]

File: server/app/services/MessageKey.java [hunk 1]
```diff
@@ -275,7 +275,7 @@ public enum MessageKey {
   LINK_CREATE_ACCOUNT_FROM_OVERVIEW("link.createAccountFromOverview"), // North Star only
   LINK_EDIT("link.edit"),
   LINK_ANSWER("link.answer"),
-  ARIA_LABEL_SUPPORT_EMAIL("ariaLabel.supportEmail"), // North Star only
+  ARIA_LABEL_SUPPORT_EMAIL("ariaLabel.technicalSupport"), // North Star only
```
Comment (shane-exygy) [inline server/app/services/MessageKey.java:278]: **issue (blocking):** This should be alphabetically in the list as best as possible.

File: server/conf/i18n/messages [hunk 2]
```diff
@@ -65,6 +65,9 @@ toast.errorMessageOutline=Error: {0}
 button.close=Close
 # Button text that will navigate the applicant to a page where they can review previous answers
 button.review=Review
+# An aria-label for screen readers that helps provide context for the support email. The support email is a variable,
```
Comment (shane-exygy) [inline server/conf/i18n/messages:68]: **suggestion (non-blocking):** 
```suggestion
# An aria-label for screen readers that helps provide context for the support email. The variable is an email address.
```

Comment (shane-exygy) [reply server/conf/i18n/messages:68]: Suggest removing the second line.  The translators understand how substitutions work, so I'm not sure this adds clarity.

File: server/conf/i18n/messages [hunk 3]
```diff
@@ -65,6 +65,9 @@ toast.errorMessageOutline=Error: {0}
...
+# so this might say "For technical support, contact example@example.com (opens in a new tab)".
+ariaLabel.technicalSupport=For technical support, contact {0} (opens in a new tab)
```
Comment (shane-exygy) [inline server/conf/i18n/messages:70]: **issue (blocking):** I think this should be prefixed "footer" and named something like technicalSupportAriaLabel

It then can be organized better in this file next to the visible string.

While there are two ariaLabel prefix examples they appear to be exceptions.  The prevalent pattern is to use the existing pattern of the prefix as a page-location (footer.)/component(label.) namespace rather.

Comment (shane-exygy) [reply server/conf/i18n/messages:70]: Also: It occurs to me that the "opens in new tab" text is not correct for email links as it depends on how your email provider is configured, it often launches and external application.

I'm unsure who our a11y guru is but suggest asking Shreya or Melanie what is best.

Perhaps "opens externally".

File: server/conf/i18n/messages (hunk 2 above)
Comment (tallulahkay) [reply server/conf/i18n/messages:68]: I'm just following the existing pattern here

File: server/conf/i18n/messages (hunk 3 above)
Comment (tallulahkay) [reply server/conf/i18n/messages:70]: @shreyachatterjee00 @dkatzz what do you think? The issue specifically recommends "opens in a new tab". would it be better to use "opens externally"?

File: server/conf/i18n/messages (hunk 2 above)
Comment (tallulahkay) [reply server/conf/i18n/messages:68]: I think the important information I'm trying to get across is what the variable will be. They know how a variable works, but they don't know what will be coming in as a variable. It changes the context if it's an email, a name, a string, a timestamp, etc. I think you read it like "this is an explanation of a variable" but I meant it as "this is what the variable is"

File: server/conf/i18n/messages (hunk 3 above)
Comment (dkatzz) [reply server/conf/i18n/messages]: I'm actually not sure and I'm not seeing a lot of resources about mailto links specifically when looking at a11y docs. Adding @melanie-exygy in case she knows but I will also comment on the internal issue and see if the a11y reviewer has a more specific recommendation. Thanks @shane-exygy for flagging

Comment (shane-exygy) [reply server/conf/i18n/messages]: @dkatzz Same, I was wondering if this was perhaps a false positive from the reviewers.

It seems fairly expected that email links will open outside the current page, I'm not sure I've ever seem otherwise.

Comment (melanie-exygy) [reply server/conf/i18n/messages]: My suggestion is that we make it clear what this link is, both for sighted users and screen reader users.  We could do that with an email icon that has alt text.  The alt text should describe the action that will take place when the user clicks the link.  So, maybe "email support team".

**Comment by tallulahkay** [comment]
@shane-exygy I implemented the solution we landed on in [this thread](https://civiform.slack.com/archives/C06H50QQ45P/p1743712075594669)

File: server/app/services/MessageKey.java [hunk 4]
```diff
@@ -162,6 +162,7 @@ public enum MessageKey {
   CONTENT_OTHER_PROGRAMS_TO_APPLY_FOR("content.otherProgramsToApplyFor"),
   CONTENT_ELIGIBILITY_CRITERIA("content.eligibilityCriteria"),
   CONTENT_ELIGIBILITY_CRITERIA_V2("content.eligibilityCriteria.v2"), // North Star only
+  CONTENT_ELIGIBILITY_CRITERIA_V3("content.eligibilityCriteria.v3"), // North Star only
```
Comment (shane-exygy) [inline server/app/services/MessageKey.java:165]: **issue (blocking):** The eligibility changes seem unrelated to the email link, is that the case?

File: server/app/views/applicant/NavigationFragment.html [hunk 5]
```diff
@@ -343,17 +343,14 @@
...
-                  + 'rel=\'noopener noreferrer\'>'
-                  + ${supportEmail}
-                  + '</a>'"
-                th:utext="#{footer.technicalSupport(${supportLink})}"
+              <a
+                th:href="'mailto:' + ${supportEmail} + '\' '"
+                class="usa-footer__contact-info expanding-div usa-link"
+                rel="noopener noreferrer"
+                target="_blank"
+                th:utext="#{footer.technicalSupport.v2(${supportEmail})}"
```
Comment (melanie-exygy) [inline server/app/views/applicant/NavigationFragment.html:351]: **question (non-blocking):** Do you know why this needs to be unescaped?  I tried it with `th:text` and everything seemed fine.

File: server/app/views/applicant/NavigationFragment.html [hunk 6]
```diff
@@ -343,17 +343,14 @@
...
-                th:with="supportLink='<a class=\'usa-link\' '
-                  + 'href=\'mailto:' + ${supportEmail} + '\' '
-                  + 'target=\'_blank\' '
-                  + 'rel=\'noopener noreferrer\'>'
-                  + ${supportEmail}
-                  + '</a>'"
-                th:utext="#{footer.technicalSupport(${supportLink})}"
+              <a
+                th:href="'mailto:' + ${supportEmail} + '\' '"
+                class="usa-footer__contact-info expanding-div usa-link"
```
Comment (melanie-exygy) [inline server/app/views/applicant/NavigationFragment.html:348]: **suggestion (non-blocking):** I don't think `expanding-div` is having any effect here, so you could remove it.

File: server/app/views/applicant/NavigationFragment.html (hunk 5 above)
Comment (tallulahkay) [reply server/app/views/applicant/NavigationFragment.html:351]: probably was necessary for the previous implementation when passing a link in! I'll remove it

Comment (melanie-exygy) [reply server/app/views/applicant/NavigationFragment.html]: That's probably it.  Thanks!

**Review by melanie-exygy — APPROVED** [review]
