### PR TITLE
Fix JS error during file upload on azure

### LINKED ISSUE #3896: JS error on applicant file upload page
**Describe the bug**
This bug is not visible to user and doesn't block any user flows. It happens only on azure. Seems like a harmless JS error that I found during improving error detection in tests. Error

```
azure_upload.ts:44 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at AzureUploadController.attemptUpload (azure_upload.ts:44:48)
    at HTMLFormElement.<anonymous> (azure_upload.ts:20:12)
```

**To Reproduce**

1. Go to https://staging-azure.civiform.dev/
2. Login as guest.
3. Go to "Upload your file" program.
4. Go to the question and click "Save and next" without uploading a file. 
5. JS error in console.

### PR DESCRIPTION
**Pull request by nbeloglazov**
### Description

During file upload on azure JS code doesn't check whether user actually chose a file which leads to the following error:

```
azure_upload.ts:44 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at AzureUploadController.attemptUpload (azure_upload.ts:44:48)
    at HTMLFormElement.<anonymous> (azure_upload.ts:20:12)
```

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes #3896

### CODE REVIEW

File: server/app/assets/javascripts/azure_upload.ts [hunk 1]
```diff
@@ -36,6 +36,11 @@ class AzureUploadController {
       throw new Error('Attempted to upload to null container')
     }
     const azureUploadProps = this.getAzureUploadProps(uploadContainer)
+    if (azureUploadProps.file == null) {
+      // No file selected by the user. Validation is done in file_upload.ts so
```
Comment (jessbumblebee) [inline server/app/assets/javascripts/azure_upload.ts:40]: Does the validation also including error messaging for the user along the lines of "no file selected, please choose a file befores starting an upload."?

Comment (nbeloglazov) [reply server/app/assets/javascripts/azure_upload.ts:40]: Yes, it does. it shows a hidden div containing error message.

**Review by jessbumblebee — APPROVED** [review]
