### PR TITLE
Address validation outside service area

### LINKED ISSUE #7944: Applicants are submitting ineligible Trees for Neighborhoods applications when their address is outside of Seattle
**Describe the bug**
The trees for neighborhoods program is only eligible to residents of Seattle. This program includes the following eligibility criteria. 

Image

However, two applicants were able to submit applications with addresses outside the service area on 7/1/24 at 2024/07/01 12:33:16 PM PDT and 2024/07/01 03:09:56 PM PDT. 

Image

**Expected behavior**
Applicants with addresses outside the City of Seattle service area should not be able to submit and application to Trees for Neighborhoods.

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

Expands the ability to check address eligibility outside the service area. The former `service_area` property stored on the applicant/application address answer has been converted from a double delimited string (ex. `a_b_1,d_e_2`) to being represented as a typed array.

For backwards compatibility, the api will flatten the value back to a string. This was already documented in #7134. We need to see if any CEs are currently relying on that.

A job converting existing `service_area` string will come as a separate PR; both will be merged together.

## Release notes

- Eligibility checks can now check if addresses are outside a configured service area.
- Eligibility checks for address service area handle more than just alphanumeric characters

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary

### Issue(s) this completes

Fixes #7944; #8389

### CODE REVIEW

File: server/app/services/CfJsonDocumentContext.java [hunk 1]
```diff
@@ -218,6 +219,31 @@ public void putRepeatedEntities(Path path, ImmutableList<String> entityNames) {
     }
   }
 
+  /**
+   * Puts an array at a given path, building parent objects as needed.
+   *
+   * @param path the {@link Path} where the array should be added.
+   * @param entityNames a {@link List} containing service area results.
+   */
+  public void putServiceAreaInclusionEntities(
```
Comment (devin-civi) [inline server/app/services/CfJsonDocumentContext.java:228]: Seems like this would live better on ApplicantData since it's referencing scalars specific to that. (And same for read)

File: server/app/services/CfJsonDocumentContext.java [hunk 2]
```diff
@@ -218,6 +219,31 @@ public void putRepeatedEntities(Path path, ImmutableList<String> entityNames) {
...
+      Path path, ImmutableList<ServiceAreaInclusion> entityNames) {
```
Comment (devin-civi) [inline server/app/services/CfJsonDocumentContext.java:229]: Optional nit: It isn't clear to me why this is called entityNames since it seems to include a lot more.

File: server/app/services/applicant/ServiceAreaUpdateResolver.java [hunk 3]
```diff
@@ -158,15 +178,87 @@ private Boolean doesUpdateContainCorrectedAddress(
...
+
+  /**
+   * Attempts to find the index for a service_area array.
+   *
+   * @param updateMapKey Key from the updateMap in path form. Example:
+   *     `applicant.question_name.service_area[0].service_area_id`.
+   *     --------------------------------------^
+   * @return the int value of the index or -1 if errors/no matches found
+   */
+  private int extractIndexFromPath(String updateMapKey) {
```
Comment (devin-civi) [inline server/app/services/applicant/ServiceAreaUpdateResolver.java:200]: Optional: Did you consider parsing this as a path and using the built in arrayIndex() method on that (and does that work? :) If that works I prefer it because there is less custom code, but it's just a preference.

**Review by devin-civi — APPROVED** [review]

File: server/app/services/applicant/ServiceAreaUpdateResolver.java (hunk 3 above)
Comment (gwendolyngoetz) [reply server/app/services/applicant/ServiceAreaUpdateResolver.java]: Great catch! Completely spaced on that method

File: server/app/services/CfJsonDocumentContext.java [hunk 4]
```diff
@@ -241,7 +241,7 @@ public void putNull(Path path) {
    *     "$.applicant.children[3].favorite_color.text".
    * @param value the value to place; values of type Map will create the equivalent JSON structure
    */
-  private void put(Path path, Object value) {
+  protected void put(Path path, Object value) {
```
[the remark this answers is not in the document]
Comment (gwendolyngoetz) [reply server/app/services/CfJsonDocumentContext.java]: I realized there's already a putArray that is public so I swapped over to that an set put back to private.

I think it makes sense to leave readList as being protected so subclasses can get a typed array without having to add something specific to `CfJsonDocumentContext`.

File: server/app/services/applicant/ApplicantData.java [hunk 5]
```diff
@@ -388,4 +392,42 @@ private Optional<String> getAccountEmail() {
...
+  /**
+   * Puts an array at a given path, building parent objects as needed.
+   *
+   * @param path the {@link Path} where the array should be added.
+   * @param entityNames a {@link List} containing service area results.
+   */
+  public void putServiceAreaInclusionEntities(
+      Path path, ImmutableList<ServiceAreaInclusion> entityNames) {
+    if (entityNames.isEmpty()) {
+      put(path, ImmutableList.of());
```
[the remark this answers is not in the document]
Comment (gwendolyngoetz) [reply server/app/services/applicant/ApplicantData.java]: There's a private putArrayIfMissing on `CfJsonDocumentContext`. I don't know if we want to expose more stuff. I'm fine leaving it as `putArray` with an empty collection. Thoughts?

**Comment by gwendolyngoetz** [comment]
Realized I was incorrectly getting the scalar names since they matched. Fixed that.
