### PR TITLE
Handle ConcurrentModificationException in MetricsController

### LINKED ISSUE #9640: Metrics Endpoint Causing Errors
This starts happening at an unknown time. So far I have been unable to repro it locally. It may be load related or memory related. Needs more investigation.

Internal server error, for (GET) [/metrics] ->

> play.api.UnexpectedException: Unexpected exception[ConcurrentModificationException: null]	 
>     at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384)	 
>     at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)	 
>     at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245)	 
>     at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181)	 
>     at controllers.ErrorHandler.onServerError(ErrorHandler.java:127)	 
>     at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33)	 
>     at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482)	 
>     at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474)	 
>     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)	 
>     at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)	 
>     at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)	 
>     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)	 
>     at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)	 
>     at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)	 
>     at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)	 
>     at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)	 
>     at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)	 
>     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)	 
>     at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)	 
>     at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) 
> 
> play.api.UnexpectedException: Unexpected exception[ConcurrentModificationException: null] 
>     at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384) 
>     at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala) 
>     at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245) 
>     at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181) 
>     at controllers.ErrorHandler.onServerError(ErrorHandler.java:127) 
>     at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33) 
>     at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482) 
>     at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474) 
>     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490) 
>     at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73) 
>     at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110) 
>     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) 
>     at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94) 
>     at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110) 
>     at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59) 
>     at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57) 
>     at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) 
>     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) 
>     at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) 
>     at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 
> Caused by: java.util.ConcurrentModificationException: null	 
>     at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)	 
>     at java.base/java.util.ArrayList$Itr.next(Unknown Source)	 
>     at io.ebeaninternal.server.transaction.TransactionManager.visitMetrics(TransactionManager.java:424)	 
>     at io.ebeaninternal.server.core.DefaultServer.visitMetrics(DefaultServer.java:2094)	 
>     at io.ebeaninternal.server.core.DefaultMetaInfoManager.visitMetrics(DefaultMetaInfoManager.java:33)	 
>     at io.ebeaninternal.server.core.DefaultMetaInfoManager.visitBasic(DefaultMetaInfoManager.java:44)	 
>     at io.ebeaninternal.server.core.DefaultMetaInfoManager.collectMetrics(DefaultMetaInfoManager.java:38)	 
>     at controllers.monitoring.MetricsController.getMetrics(MetricsController.java:67)	 
>     at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$520(Routes.scala:5254)	 
>     at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:152)	 
>     at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:125)	 
>     at play.core.j.JavaAction$$anon$1.$anonfun$call$1(JavaAction.scala:128)	 
>     at play.api.mvc.BodyParser$.$anonfun$parseBody$4(Action.scala:241)	 
>     at scala.Option.getOrElse(Option.scala:201)	 
>     at play.api.mvc.BodyParser$.parseBody(Action.scala:239)	 
>     at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:136)	 
>     at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)	 
>     at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:192)	 
>     at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)	 
>     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
> 

**Additional context**

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

Adds better error handling and a retry when trying to collect server metrics for Prometheus.

> This exception can often be reproduced if you start running the full browser test suite and then spam calling `/metrics` until it sometimes will throw.
> 
> Basically this state can happen when calling `database.metaInfo().collectMetrics()` method and the metrics are either being updated or a lock can't be immediately gotten.
> 
> I'm trying to avoid using synchronize to force a lock on the database object as I'm concerned about adversely affecting performance.
> 
> Since the `/metrics` endpoint is called very frequently any data from a failed call gets rolled into the next successful call to `/metrics`.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Issue(s) this completes

Fixes #9640

### CODE REVIEW

File: server/app/controllers/monitoring/MetricsController.java [hunk 1]
```diff
@@ -97,11 +96,44 @@ public Result getMetrics() {
...
+    } catch (Exception e) {
+      LOGGER.error(e.getMessage());
     }
 
-    return ok(writer.toString()).as(TextFormat.CONTENT_TYPE_004);
+    return internalServerError();
+  }
+
+  /**
+   * Attempt to collect server metrics. Will make one extra attempt in the event of a
```
Comment (shane-exygy) [inline server/app/controllers/monitoring/MetricsController.java:129]: **question (blocking):** Why make an additional request when the assumption is that the client is making a lot of requests already (and will make additional requests anyway)?  This seemingly will double the request load in a situation where the system is not ready to accept the request which under load could lead to the system being less able to handle other requests 

This retry and the handling above feel like alternative approaches for the problem, which then would seem to mean that one is unnecessary, my inclination is to not do this retry given the other code.

If we knew there were situations where single requests were being made in long time spans this seems more appropriate.

File: server/app/controllers/monitoring/MetricsController.java [hunk 2]
```diff
@@ -97,11 +96,44 @@ public Result getMetrics() {
                     .inc((double) metric.total());
               });
 
+      var writer = new StringWriter();
       TextFormat.write004(writer, collectorRegistry.metricFamilySamples());
-    } catch (IOException e) {
-      throw new UncheckedIOException(e);
```
Comment (shane-exygy) [inline server/app/controllers/monitoring/MetricsController.java:102]: **question:** Is anything expecting to get this response which will no longer be sent?

File: server/app/controllers/monitoring/MetricsController.java [hunk 3]
```diff
@@ -97,11 +96,44 @@ public Result getMetrics() {
...
+      return ok(writer.toString()).as(TextFormat.CONTENT_TYPE_004);
+    } catch (ConcurrentModificationException e) {
+      // This exception can often be reproduced if you start running the full browser test
```
Comment (shane-exygy) [inline server/app/controllers/monitoring/MetricsController.java:103]: **suggestion:** 
```suggestion
      // This exception can often be triggered if you start running the full browser test
```

File: server/app/controllers/monitoring/MetricsController.java [hunk 4]
```diff
@@ -97,11 +96,44 @@ public Result getMetrics() {
...
+      // suite and then spam calling `/metrics` until it sometimes will throw.
```
Comment (shane-exygy) [inline server/app/controllers/monitoring/MetricsController.java:104]: **suggestion:** 
```suggestion
      // suite and then spam calling `/metrics`.
```

File: server/app/controllers/monitoring/MetricsController.java [hunk 5]
```diff
@@ -97,11 +96,44 @@ public Result getMetrics() {
...
+      //
+      // Basically this state can happen when calling `database.metaInfo().collectMetrics()`
+      // method and the metrics are either being updated or a lock can't be immediately gotten.
+      //
+      // I'm trying to avoid using synchronize to force a lock on the database object as I'm
```
Comment (shane-exygy) [inline server/app/controllers/monitoring/MetricsController.java:109]: **suggestion:** 
```suggestion
      // Avoid using synchronize to force a lock on the database object as it may adversely affecting performance.
```

File: server/app/controllers/monitoring/MetricsController.java (hunk 2 above)
Comment (gwendolyngoetz) [reply server/app/controllers/monitoring/MetricsController.java:102]: Not that I could see. I think it's probably just because IOException is checked and was yelling for not being caught. Before this was just throwing and letting the global handler log the error. There's nothing with the IOException on the writer that matters at this point.

File: server/app/controllers/monitoring/MetricsController.java (hunk 1 above)
Comment (gwendolyngoetz) [reply server/app/controllers/monitoring/MetricsController.java]: Yeah good point. It was a last minute thought, but it definitely doesn't add much value. Removed!

**Review by shane-exygy — APPROVED** [review]

**Review by EmiliaPaz — APPROVED** [review]
