### PR TITLE
Preserve option admin name casing in CSV export and update column header format

### LINKED ISSUE #6605: Fix option admin names collisions due to case insensitivity during CSV export
**Describe the bug**
Anytime a new Admin name is created for an multiselect question, we should not only check for its existence but also include case sensitivity check with existing ones.

**To Reproduce**

1. Create a multiselect question with two or three options with admin names like Red_color and Green_color
2. Add another option with admin name like red_color (case is different)
3. Create a program with this question and publish. Login as an applicant and sumit an application to this program.
4. Login as Program Admin and hit CSV export. you will see a timeout issue due to the export keys being the same.

**Expected behavior**
The second option red_color should not be permitted by the system as it has the same admin name as the previous option. 

**Screenshots**
image

Error message - 
```
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: applicant.enumhousehold_member[1].interest_in_programs.recreation & aquatics programs (all ages)=SELECTED and applicant.enumhousehold_member[1].interest_in_programs.recreation & aquatics programs (all ages)=NOT_AN_OPTION_AT_PROGRAM_VERSION
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:378)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:372)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:246)
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587)
	at services.export.CsvExporter.exportRecord(CsvExporter.java:118)
	at services.export.CsvExporterService.exportCsv(CsvExporterService.java:193)
	at services.export.CsvExporterService.getProgramAllVersionsCsv(CsvExporterService.java:108)
	at controllers.admin.AdminApplicationController.downloadAll(AdminApplicationController.java:187)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$229(Routes.scala:4080)
	at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:150)
	at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:149)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:119)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at org.pac4j.play.java.SecureAction.lambda$internalCall$1(SecureAction.java:100)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:141)
```

### PR DESCRIPTION
**Pull request by avaleske**
### Description

Refactor CsvExporter to preserve option admin name casing during export.

Previously, all option admin names were lowercased during the CSV export, causing collisions and the data to appear differently then in the JSON export. Now, option admin name cases are preserved.

See the [Fix for case-insensitive option admin name collision](https://docs.google.com/document/d/15jyNeTn7NItfBM3n2SqvWebbY3WD7E5dD_hIkiuhU-k/edit) doc for more

Details:
- Updates CSV columns for checkbox options to use the heading format `question name (selections - option_admin_name)`
- The `Column` in the CsvExportConfig now optionally includes the option admin name, to support checkbox questions. Before, we were adding the column name to the end of the path, causing it to be lowercased because `Path`s are all lowercase.
- `CsvExporter.exportRecord()` now builds a map of `<Path, AnswerData>` instead of `<Path, String>` when exporting records. It now fetches the answer text out of the `AnswerData` when exporting the record, instead of beforehand when building the map.
- The full `AnswerData` and the column name are enough to fill the value for checkbox question columns, so we do need to need to bring `checkboxQuestionNameToOptionsMap` into `exportRecord()`

In `CsvExporterService`
- Rename `answerMap` to `representativeAnswerMap`, as well as other similar data structures, to emphasize that this is not a map of _all_ answers, but rather a single answer for each question so that we can get a complete list of the columns we'll need
- Refactor the large for-loops into streams where possible
- We remove `checkboxQuestionNameToOptionsMap` because we don't need to cache the result of the query. Each question is only visited once, rather than once per application as we had previously assumed.

Also
- Adds a label to the `getAllHistoricOptionAdminNames()` query in ExportServiceRepository
- `FileUploadQuestion.getAllPaths()` now returns the file key path
- Removes the unnecessary wrapper around `CsvExportConfig`

## Release notes

n/a

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary

#### Database evolutions

Read the guidelines [here](https://github.com/civiform/civiform/wiki/Database#writing-database-evolutions)

- [n/a] Assigned two reviewers
- n/a ] Guarded against already existing resources using `IF NOT EXISTS` and `IF EXISTS`
- [n/a] Downs created to undo changes in Ups

#### User visible changes

- [n/a] Followed steps to [internationalize new strings](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#internationalization-for-application-strings)
  - [n/a] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [n/a] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [n/a] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [n/a] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [n/a] Manually tested at 200% size
- [n/a] Manually evaluated tab order

#### New Features

- [n/a] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [n/a] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [n/a] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

Try creating a question with colliding admin names and export it.

### Issue(s) this completes

Fixes #6605, #6573

cc @swatkat1

### CODE REVIEW

**Comment by avaleske** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #6674** <a href="https://app.graphite.dev/github/pr/civiform/civiform/6674?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/civiform/civiform/6674?utm_source=stack-comment).

File: server/app/repository/ExportServiceRepository.java [hunk 1]
```diff
@@ -19,41 +18,42 @@ public ExportServiceRepository() {
...
-                + "  WHERE lifecycle_stage IN ('obsolete', 'active') "
-                + "  AND name = :currentQuestion "
-                + ") AS all_options "
-                + "GROUP BY all_options.admin_name "
-                + "ORDER BY MIN(all_options.create_time), MIN(all_options.id) ASC")
-        .setParameter("currentQuestion", questionName)
-        .findList()
-        .stream()
-        .forEachOrdered(sqlRow -> allOptions.add(sqlRow.getString("admin_name")));
+    ImmutableList<String> allOptions =
```
Comment (swatkat1) [inline server/app/repository/ExportServiceRepository.java:30]: Can we switch back to linkedhashset to preserve order every time?

File: server/app/services/export/CsvExporter.java [hunk 2]
```diff
@@ -208,15 +161,52 @@ public void exportRecord(
...
+            .createMultiSelectQuestion()
+            .getSelectedOptionAdminNames()
+            .orElse(ImmutableList.of());
+
+    ImmutableList<String> allOptionsShownInQuestionVersion =
+        answerData.applicantQuestion().createMultiSelectQuestion().getOptions().stream()
+            .map(LocalizedQuestionOption::adminName)
+            .collect(ImmutableList.toImmutableList());
+
+    if (!allOptionsShownInQuestionVersion.contains(column.optionAdminName().get())) {
```
Comment (swatkat1) [inline server/app/services/export/CsvExporter.java:201]: pls convert to lowercase before comparison

File: server/app/repository/ExportServiceRepository.java [hunk 3]
```diff
@@ -19,41 +18,42 @@ public ExportServiceRepository() {
...
+        database
+            .sqlQuery(
+                "SELECT"
+                    + "  all_options.admin_name "
+                    + "FROM ( "
+                    + "  SELECT "
+                    + "    q.create_time, "
+                    + "    jsonb_array_elements(q.question_options) ->>'adminName' AS admin_name, "
```
[the remark this answers is not in the document]
Comment (swatkat1) [reply server/app/repository/ExportServiceRepository.java:38]: this query works @avaleske SELECT
   LOWER(all_options.admin_name)
FROM
 (SELECT
    q.create_time as create_time,
    jsonb_array_elements(q.question_options) ->>'adminName' AS admin_name,
    jsonb_array_elements(q.question_options) ->>'id' AS id
  FROM questions q
  INNER JOIN versions_questions vq ON  vq.questions_id = q.id
  INNER JOIN versions v ON vq.versions_id = v.id
  WHERE lifecycle_stage IN ('obsolete', 'active')
  AND name = 'Interest in programs20232024'
) AS all_options
GROUP BY LOWER(all_options.admin_name)
ORDER BY MIN(all_options.create_time), MIN(all_options.id)  ASC;

[the remark this answers is not in the document]
Comment (avaleske) [reply server/app/repository/ExportServiceRepository.java:38]: See the comment above, we don't need to lowercase admin names any more.

File: server/app/repository/ExportServiceRepository.java (hunk 1 above)
Comment (avaleske) [reply server/app/repository/ExportServiceRepository.java:30]: Since the query has a GROUP BY we're already guaranteed to have a set of unique admin names, so we don't need to use the `LinkedHashSet` to de-dupe, and `ImmutableList` also preserves order.

File: server/app/services/export/CsvExporter.java (hunk 2 above)
Comment (swatkat1) [reply server/app/services/export/CsvExporter.java:201]: But CSV exports always lowercase - applicant.enumhousehold_member[1].interest_in_programs.recreation & aquatics programs (all ages)=SELECTED and applicant.enumhousehold_member[1].interest_in_programs.recreation & aquatics programs (all ages)=NOT_AN_OPTION_AT_PROGRAM_VERSION. Casing doesn't affectCVS exports

**Review by gwendolyngoetz — APPROVED** [review]

**Review by swatkat1 — COMMENTED** [review]
Pulled your branch and tested it. It is good! Thanks.

**Review by swatkat1 — APPROVED** [review]

**Review by gwendolyngoetz — APPROVED** [review]

**Review by swatkat1 — APPROVED** [review]

**Comment by avaleske** [comment]
We got confirmation at the governance committee meeting that this won't break anything for civic entities, so I'm merging this now.
