### PR TITLE
[A11y] Correctly announce links created by markdown

### LINKED ISSUE #9919: [a11y][WCAG 4.1.2]: Name of the link is not announced by the screen reader.
Observed Results:
--
When focus is on " preschool@seattle.gov" link, chrome vox is announcing as "Link opens in a new tab, press search + space to activate" in "Eligibility Test Program" page

Screencast: Chromebook + Chromevox[here]( https://drive.google.com/file/d/1kAeAtvJ3-RAXSpWbAG8rT1eQJSIPnC6m/view?usp=drive_link ) \
Screencast: Windows + NVDA[here]( https://drive.google.com/file/d/1B4biBe2vb7h7eIEeLWrf-YRpm5TpKLAl/view?usp=drive_link )

User Impact:
-----
Users who depend on assistive technologies like screen reader will face difficulty if name of the links are not announcing.

Expected Results:
--
When focus is on "preschool@seattle.gov" link, chromevox should announce as " preschool@seattle.gov" link opens in new tab, press search + space to activate"

Steps to Reproduce:
-------
0. Enable Chromevox using Ctrl+Alt+Z
1. Launch the URL[here]( https://ns.civiform.dev/programs )
2. Click "View and Apply" at "Eligibility test program".
3. Navigate to link at "How to apply" region and observe the screen reader verbalization over that link

WCAG Details:
--
[WCAG 4.1.2][Name, Role and Value]( https://www.w3.org/WAI/WCAG22/quickref/?versions=2.0#name-role-value )

Additional Information
--
NA

Environment Details:
--

Machine: chromebook 13.3/Windows \
Browser: Version 132.0.6834.208 (Official Build) (64-bit) \
Screenreader: Chromevox/NVDA 2024.4.2135031 \
Bug Filling Time: 15 mins.

### PR DESCRIPTION
**Pull request by rockycodes**
### Description

This PR primarily fixes how aria labels are added to links in markdown. It removes the custom aria label setting on links, which allows for the link text to be read aloud, and adds the "opens in a new tab" text to an aria label on the SVG. 

This PR also fixes several places where we were using the wrong method to format text in North Star views, refactors some call sites on the admin side to use the simpler version `formatText`, and adds more detailed method comments to `TextFormatter`.

#### General

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Instructions for manual testing

1. As an admin, create a program and add a long description that includes a link in markdown
2. Publish the program
3. As an applicant, turn on a screen reader, tab to the link and confirm the link text is read out loud + the "opens in a new tab" text.
4. Change the language and confirm the "opens in a new tab" text is translated.

### Issue(s) this completes

Fixes #9919

### CODE REVIEW

File: server/app/views/CiviFormMarkdown.java [hunk 1]
```diff
@@ -48,10 +48,11 @@ private static class CiviFormAttributeProvider implements AttributeProvider {
     @Override
     public void setAttributes(Node node, String tagName, Map<String, String> attributes) {
       if (node instanceof Link) {
+        Link linkNode = (Link) node;
         attributes.put("class", StyleUtils.removeStyles(ApplicantStyles.LINK, "text-sm"));
         attributes.put("target", "_blank");
         attributes.put("rel", "noopener noreferrer");
-        attributes.put("aria-label", ariaLabel);
+        attributes.put("aria-label", linkNode.getDestination() + " " + ariaLabel);
```
Comment (rockycodes) [inline server/app/views/CiviFormMarkdown.java:55]: This is the only logic change -- the rest of the updates are tests.

File: server/test/views/components/TextFormatterTest.java [hunk 2]
```diff
@@ -278,10 +282,8 @@ public void formatTextWithAriaLabel_addsAriaLabel() {
         TextFormatter.formatTextWithAriaLabel(
             "[link](https://www.example.com)", false, false, "test aria label");
 
-    assertThat(content.get(0).render()).contains("aria-label=\"test aria label\"");
-
-    // Set the aria label back to the default for the other tests
-    TextFormatter.resetAriaLabelToDefault();
```
Comment (rockycodes) [inline server/test/views/components/TextFormatterTest.java:284]: Having these reset calls at the end of these tests caused confusing cascading failures when these tests failed. I moved the reset calls to the start of the tests that need them.

File: server/app/views/CiviFormMarkdown.java (hunk 1 above)
Comment (melanie-exygy) [reply server/app/views/CiviFormMarkdown.java:55]: suggestion (non-blocking):  Normally, we would want the link text to be descriptive of the content of the page we're going to.  So, using the URI as the link text isn't ideal.  If the admin hasn't specified link text, maybe a compromise would be to trim the scheme off of the URI?  I was also thinking that we could trim the path off, but not sure about that.  What do you think?

suggestion(blocking):  If the admin has specified link text by doing this: `[More information on the Fresh Bucks program](https://www.cityofseattle.gov/fresh-bucks/details)`, the screen reader should read the link text rather than the link destination.  I suspect it won't do that as long as we have an aria-label of "opens in a new tab".  That's because the name of a link is calculated in this order:  'aria-labelled-by', 'aria-label', text contained between the opening <a> and closing </a> elements.  The solution would be to add "opens in a new tab" as hidden text, rather than as an aria-label.  For that, all you need to do is add the class `usa-sr-only`.  Then, the screen reader should read the link text and "opens in a new tab".

File: server/app/views/components/TextFormatter.java [hunk 3]
```diff
@@ -108,9 +118,12 @@ private static String preserveEmptyLines(String text) {
 
   private static String addIconToLinks(String markdownText) {
     String closingATag = "</a>";
+
     String svgIconString =
         Icons.svg(Icons.OPEN_IN_NEW)
             .withClasses("shrink-0", "h-5", "w-auto", "inline", "ml-1", "align-text-top")
+            .attr("aria-label", ", " + ariaLabel)
+            .attr("aria-hidden", false)
```
Comment (rockycodes) [inline server/app/views/components/TextFormatter.java:126]: This is the change we talked about to add the "opens in a new tab" label to the svg.

File: server/app/views/admin/migration/AdminImportViewPartial.java [hunk 4]
```diff
@@ -286,14 +286,11 @@ private DomContent renderQuestion(
             .with(
                 newOrDuplicateIndicator,
                 div()
-                    .with(
-                        TextFormatter.formatText(
-                            question.getQuestionText().getDefault(), false, false))
+                    .with(TextFormatter.formatText(question.getQuestionText().getDefault()))
```
Comment (rockycodes) [inline server/app/views/admin/migration/AdminImportViewPartial.java:289]: I refactored a couple of places on the admin side to use the simpler `formatText` method.

File: server/app/views/CiviFormMarkdown.java (hunk 1 above)
Comment (rockycodes) [reply server/app/views/CiviFormMarkdown.java]: Per our offline convo, I fixed this so the screen reader will read out the text in between the A tags and applied the "opens in a new tab" label to the svg.

File: server/app/views/questiontypes/CheckboxQuestionFragment.html [hunk 5]
```diff
@@ -34,7 +34,7 @@
     <div
       class="usa-checkbox cf-multi-option-question-option"
       th:each="option,iterator: ${multiSelectQuestion.getOptions()}"
-      th:with="inputId='checkbox-' + ${question.getContextualizedPath()} + '-' + ${option.id()}"
+      th:with="inputId='checkbox-' + ${question.getContextualizedPath()} + '-' + ${option.id()},ariaLabel=#{link.opensNewTabSr}"
```
Comment (melanie-exygy) [inline server/app/views/questiontypes/CheckboxQuestionFragment.html:37]: **suggestion (non-blocking):** I think we need a more specific name, maybe `linkAriaLabel` or `ariaLabelNewTab`?

File: server/app/views/applicant/NorthStarApplicantUpsellView.java [hunk 6]
```diff
@@ -89,10 +89,14 @@ public String render(UpsellParams params) {
...
-        TextFormatter.formatTextToSanitizedHTML(
+        TextFormatter.formatTextToSanitizedHTMLWithAriaLabel(
             params.customConfirmationMessage().getOrDefault(locale),
             /* preserveEmptyLines= */ false,
-            /* addRequiredIndicator= */ false);
+            /* addRequiredIndicator= */ false,
+            params
+                .messages()
+                .at(MessageKey.LINK_OPENS_NEW_TAB_SR.getKeyName())
+                .toLowerCase(Locale.ROOT));
```
Comment (melanie-exygy) [inline server/app/views/applicant/NorthStarApplicantUpsellView.java:99]: **question (non-blocking):** Can you help me understand why we need `toLowerCase`?

File: server/app/views/applicant/NorthStarAnswerData.java [hunk 7]
```diff
@@ -26,8 +26,8 @@ public int questionIndex() {
     return answerData.questionIndex();
   }
 
-  public String questionHtml() {
-    return answerData.applicantQuestion().getFormattedQuestionText();
+  public String questionHtml(String ariaLabel) {
```
Comment (melanie-exygy) [inline server/app/views/applicant/NorthStarAnswerData.java:29]: **suggestion (non-blocking):** Same comment as below about a more precise name.

File: browser-test/src/applicant/navigation/application_navigation_flow.test.ts [hunk 8]
```diff
@@ -147,7 +147,7 @@ test.describe('Applicant navigation flow', () => {
       )
       // text links are formatted correctly with an icon
       expect(cardHtml).toContain(
-        '<a href="https://www.example.com" class="text-blue-900 font-bold opacity-75 underline hover:opacity-100" target="_blank" aria-label="opens in a new tab" rel="nofollow noopener noreferrer">website<svg',
+        '<a href="https://www.example.com" class="text-blue-900 font-bold opacity-75 underline hover:opacity-100" target="_blank" rel="nofollow noopener noreferrer">website<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" stroke="currentColor" stroke-width="1%" aria-hidden="false" viewBox="0 0 24 24" class="shrink-0 h-5 w-auto inline ml-1 align-text-top" aria-label=", opens in a new tab">',
```
Comment (melanie-exygy) [inline browser-test/src/applicant/navigation/application_navigation_flow.test.ts:150]: **question (non-blocking):** Any idea why there are all the extra attributes like `stroke="currentColor"`?

File: server/app/views/applicant/NorthStarApplicantUpsellView.java (hunk 6 above)
Comment (rockycodes) [reply server/app/views/applicant/NorthStarApplicantUpsellView.java:99]: Good question and I'm honestly not sure? Maybe it was needed at some point before we had translations and got left in 🤔 Or maybe it was a copy/paste error from the beginning. But either way I'm pretty sure we don't need it since the string is lower case. I've got an issue going to clean up some of these methods, so I can add a task there to delete the `toLowerCase`.

File: server/app/views/components/TextFormatter.java [hunk 9]
```diff
@@ -108,9 +118,12 @@ private static String preserveEmptyLines(String text) {
 
   private static String addIconToLinks(String markdownText) {
     String closingATag = "</a>";
+
     String svgIconString =
         Icons.svg(Icons.OPEN_IN_NEW)
             .withClasses("shrink-0", "h-5", "w-auto", "inline", "ml-1", "align-text-top")
+            .attr("aria-label", ", " + ariaLabel)
```
[the remark this answers is not in the document]
Comment (rockycodes) [reply server/app/views/components/TextFormatter.java]: Success! I added `role` to the list of allowed attributes in our html sanitizer policy.

File: server/app/views/questiontypes/CheckboxQuestionFragment.html (hunk 5 above)
Comment (rockycodes) [reply server/app/views/questiontypes/CheckboxQuestionFragment.html]: Good call. Updated.

**Review by melanie-exygy — APPROVED** [review]
