### PR TITLE
Fix tidashboard timeout

### LINKED ISSUE #6813: Loading TI Dashboard in Prod Times Out
We're getting the following error on Seattle prod when a TI user logs in and gets redirected to the TI Dashboard `/admin/tiDash?page=1`.

Looks related to the ProgramModel.

It's also slow when a CiviForm Admin tries to load `/admin/tiGroups` may or may not be related.

The rest of the application seems to be working fine.

```
play.api.UnexpectedException: Unexpected exception[RuntimeException: javax.persistence.PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.] 
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358) 
    at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala) 
    at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:244) 
    at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:180) 
    at controllers.ErrorHandler.onServerError(ErrorHandler.java:106) 
    at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32) 
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441) 
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433) 
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490) 
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63) 
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100) 
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) 
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94) 
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100) 
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) 
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) 
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) 
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) 
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) 
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) 

Caused by: java.lang.RuntimeException: javax.persistence.PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms. 
    at org.pac4j.play.java.SecureAction.call(SecureAction.java:79) 
    at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:175) 
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687) 
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467) 
    at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64) 
    at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109) 
    at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71) 
    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429) 
    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338) 
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312) 
    at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176) 
    at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:231) 
    at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159) 
    at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522) 
    at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448) 
    at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440) 
    at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:764) 
    at akka.stream.scaladsl.Source.runWith(Source.scala:118) 
    at akka.stream.javadsl.Source.runWith(Source.scala:1075) 
    at play.libs.streams.Accumulator$FlattenSubscriber.lambda$handler$1(Accumulator.java:285) 

Caused by: javax.persistence.PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms. 
    at io.ebeaninternal.server.transaction.TransactionFactoryBasic.createReadOnlyTransaction(TransactionFactoryBasic.java:34) 
    at io.ebeaninternal.server.transaction.TransactionManager.createReadOnlyTransaction(TransactionManager.java:337) 
    at io.ebeaninternal.server.core.DefaultServer.createReadOnlyTransaction(DefaultServer.java:2177) 
    at io.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:221) 
    at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1462) 
    at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1442) 
    at io.ebeaninternal.server.core.DefaultBeanLoader.executeQuery(DefaultBeanLoader.java:154) 
    at io.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:137) 
    at io.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:544) 
    at io.ebeaninternal.server.loadcontext.DLoadBeanContext$LoadBuffer.loadBean(DLoadBeanContext.java:207) 
    at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:875) 
    at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:852) 
    at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:946) 
    at models.ProgramModel._ebean_get_programDefinition(ProgramModel.java:6) 
    at models.ProgramModel._ebean_set_programDefinition(ProgramModel.java:1) 
    at models.ProgramModel.loadProgramDefinition(ProgramModel.java:267) 
    at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) 
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
    at java.base/java.lang.reflect.Method.invoke(Unknown Source) 
    at io.ebeaninternal.server.deploy.BeanLifecycleAdapterFactory$PostLoadAdapter.invoke(BeanLifecycleAdapterFactory.java:279) 

Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms. 
    at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695) 
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) 
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) 
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) 
    at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:158) 
    at io.ebeaninternal.server.transaction.TransactionFactoryBasic.createReadOnlyTransaction(TransactionFactoryBasic.java:27) 
    at io.ebeaninternal.server.transaction.TransactionManager.createReadOnlyTransaction(TransactionManager.java:337) 
    at io.ebeaninternal.server.core.DefaultServer.createReadOnlyTransaction(DefaultServer.java:2177) 
    at io.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:221) 
    at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1462) 
    at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1442) 
    at io.ebeaninternal.server.core.DefaultBeanLoader.executeQuery(DefaultBeanLoader.java:154) 
    at io.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:137) 
    at io.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:544) 
    at io.ebeaninternal.server.loadcontext.DLoadBeanContext$LoadBuffer.loadBean(DLoadBeanContext.java:207) 
    at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:875) 
    at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:852) 
    at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:946) 
    at models.ProgramModel._ebean_get_programDefinition(ProgramModel.java:6) 
    at models.ProgramModel._ebean_set_programDefinition(ProgramModel.java:1) 


```

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

Fix the TI Dashboard Timeout. Swapping back to the full program definition option. It performs plenty fine. The shallow version of getting a program never loads for some reason. We can do further work later, but this will unblock.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

Fixes #6813

### CODE REVIEW

File: server/app/views/applicant/TrustedIntermediaryDashboardView.java [hunk 1]
```diff
@@ -369,11 +373,24 @@ private DivTag renderCardApplications(AccountModel account) {
...
-                    programRepository
-                        .getShallowProgramDefinition(application.getProgram())
+                application -> {
+                  try {
+                    return programService
+                        .getFullProgramDefinition(application.getProgram().id)
                         .localizedName()
-                        .getDefault())
+                        .getDefault();
+                  } catch (ProgramNotFoundException e) {
```
Comment (melanie-exygy) [inline server/app/views/applicant/TrustedIntermediaryDashboardView.java:382]: praise:  Good idea to be extra cautious and put in some exception handling.

**Review by melanie-exygy — APPROVED** [review]

File: server/app/views/applicant/TrustedIntermediaryDashboardView.java [hunk 2]
```diff
@@ -369,11 +373,24 @@ private DivTag renderCardApplications(AccountModel account) {
     String programs =
         newestApplicantApplications.stream()
             .map(
-                application ->
-                    programRepository
-                        .getShallowProgramDefinition(application.getProgram())
+                application -> {
+                  try {
+                    return programService
```
Comment (dkatzz) [inline server/app/views/applicant/TrustedIntermediaryDashboardView.java:378]: **suggestion (blocking):** hypothetically we don't need the full program definition, but this is this fixing the timeout issue because its getting the full program definition from the cache. Instead of using the full program definition, we can consider caching and using the shallow program definition (https://github.com/civiform/civiform/pull/6823/files). I'd hate for us to start using the full program definition as a workaround and then it would exacerbate the issue for CEs that don't have caching turned on (because that becomes even more calls without cache). Thoughts?

Comment (dkatzz) [reply server/app/views/applicant/TrustedIntermediaryDashboardView.java:378]: Resolving since we chatted offline and this works when the cache is disabled too. Thanks @gwendolyngoetz!

**Review by dkatzz — APPROVED** [review]
