### PR TITLE
Hide tabs when there are no disabled programs

### LINKED ISSUE #9380: We show the "Disabled" tab when there are no disabled programs
**Describe the bug**
In the program dashboard, we show the `in use` and `disabled` tabs, even if there are no programs that are disabled. Our QA tester found this confusing, so we may want to consider hiding this unless there are programs that are disabled.

**To Reproduce**

1. Login as a CiviForm admin
2. See `in use` and `disabled` tabs
3. Click `disabled` tab and it is empty, which is confusing

**Expected behavior**
Tabs don't appear if there are no disabled programs

**Screenshots**
Screenshot 2024-12-04 at 2 30 41 PM
Screenshot 2024-12-04 at 2 30 50 PM

### PR DESCRIPTION
**Pull request by codekarma**
### Description

Hide the "In Use"/"Disabled" tabs from the Admin program list view when there are no disabled programs.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`

#### User visible changes

- [x] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [x] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [x] Manually tested at 200% size
- [x] Manually evaluated tab order

### Instructions for manual testing
- Open program admin page
- Ensure that there are no existing programs
- Add a program that is not disabled.
- Make sure that "In Use/Disabled" tabs is not visible. 
- Add a new programs that is disabled.
- Verify that on Admin program list page, the "In Use/Disabled" tabs are now visible.
- Click on "Disabled" tab link to verify that the disabled program is listed.
- Click on "In Use" tab link to verify that the in-use program(non-disabled) is listed.

### Issue(s) this completes

Fixes #9380

### CODE REVIEW

File: server/app/repository/VersionRepository.java [hunk 1]
```diff
@@ -549,6 +550,19 @@ public Optional<ProgramModel> getProgramByNameForVersion(
...
+  public boolean anyDisabledPrograms() {
+    return anyDisabledPrograms(Optional.of(getActiveVersion()))
+        || anyDisabledPrograms(getDraftVersion());
+  }
+
+  private boolean anyDisabledPrograms(Optional<VersionModel> maybeVersion) {
+    return getProgramsForVersion(maybeVersion).stream()
+        .anyMatch(
+            p ->
+                programRepository.getShallowProgramDefinition(p).displayMode()
```
Comment (dkatzz) [inline server/app/repository/VersionRepository.java:562]: **suggestion:** Let's retrieve the program definition from cache if it exists - https://github.com/civiform/civiform/blob/15421bf65ddcd30b1d7dad57ad3a840a4ccfa4e2/server/app/repository/ProgramRepository.java#L153. It will be there for all active programs, so that should save us some queries.

File: server/test/repository/VersionRepositoryTest.java [hunk 2]
```diff
@@ -1094,4 +1094,19 @@ public void getPrograms_doesNotUseCacheForDraftVersion() {
 
     assertThat(programsByVersionCache.get(version1Key).isPresent()).isFalse();
   }
+
+  @Test
```
Comment (dkatzz) [inline server/test/repository/VersionRepositoryTest.java:1098]: **suggestion:** Could we add another test `testAnyDisabledPrograms_activeProgramDisabled`, which asserts this returns true for active programs and then we can name this `testAnyDisabledPrograms_draftProgramDisabled`?

**Review by dkatzz — COMMENTED** [review]
Looks great! Just a couple of comments

File: server/app/repository/VersionRepository.java (hunk 1 above)
Comment (codekarma) [reply server/app/repository/VersionRepository.java:562]: getProgramsForVersion already fetching Programs from cache and I updated the getShallowProgramDefinition() to first check the cache.

**Review by melanie-exygy — APPROVED** [review]

**Review by dkatzz — APPROVED** [review]
