### PR TITLE
During account merging, rollback merge if there's an exception.

### LINKED ISSUE #11304: Multiple Applicants are created for a Single account
**Describe the bug**
Seattle has noticed that many applicants are created for a single account. 
It is not sure how or why it is generated, but this is causing some user consistency, and the code always looks for oldest applicant and this approach needs to be fixed.

Example - 
Account#1 -->Applicant1 --> 1 draft application
Account#1 --> Applicant2 --> 1 Active application

Civiform always picks Applicant1 for all of Account#1 needs and abandons Applicant#2 which has an active application attached to it. 

**To Reproduce**
Steps to reproduce the behavior: - 

**Expected behavior**
Either of the two things should happen
1. We should stop creating additional applicant rows for a given account OR
2.  We should be able to merge one applicant to the other applicant

**Screenshots**
Currently it is happening about 50-60 times a month. Seattle prod data on month over month occurrence of multiple applicants 

Image

select count(*),DATE_TRUNC('month', time) AS month from (
select * from (select 
account_id, 
max(when_created) as time, 
count(distinct id)as countApp 
from applicants group by account_id) where countApp>1)
group by DATE_TRUNC('month', time)
order by DATE_TRUNC('month', time) desc; 

**Additional context**

### PR DESCRIPTION
**Pull request by shane-exygy**
### Description

Handle exceptions in the merge flow by not changing the user data.  This is done by wrapping the code in the main merging method `CiviFormProfileMerger::mergeProfiles` in a transaction.

A main use case for this fix is #11304 who's technical components are described further in #12379. Note while this PR is good to have regardless, the motivating example is a deployment auth provider that doesn't adhere to OIDC standard which then results in the exceptions.

A high level summary is:

`mergeProfiles` is composed of two code flows in the following order:
1. It's own flow to merge Applicant data
2. a Callback from the caller that merges Profile data.

The core issue is that during 2 a merge function like`CiviformOidcProfileCreator::mergeCiviFormProfile` can and does validation and throws an Exception that is intended to halt the merge flow, however the existing `CiviFormProfileMerger::mergeProfiles` has no backoff mechanism to undo the data merging that already occurred.

This PR:
1. Updates 1 above by moving the Async wrapper in `AccountRepository::mergeApplicantAndGuestProfile`, which runs the changes in the DatabaseContext, to the higher call stack level in  `CiviFormProfileMerger::mergeProfiles`, this now includes 2 above in the DatabaseContext. `mergeProfiles` is the only upstream user of it.  This also moves all of 1's call stack into the DatabaseContext.
2. Adds a Transaction around the entire merge flow in `CiviFormProfileMerger::mergeProfiles` inside the Async wrapper.  This will catch issues in either step 1 or 2 (EG: `CiviformOidcProfileCreator::mergeCiviFormProfile`) above and prevent the entire merge flow from applying changes if there is one.

Note: child transactions in effect do nothing and the parent manages everything.

Aside from the Test update, most of the other files are just plumbing a `DatabaseExecutionContext` down to `CiviFormProfileMerger` from classes with @Inject to create it.

#### Manual testing


The test flow was 
1. Using the existing code, Login (8208) and apply setting the name including Middle name. This sets it in Account primary fields and Applicant Question Answer data.
1a. Change the authority_id in the database to anything else so it is a mismatch with the login system.
2. As a Guest (8209) apply, setting No middle name.
3. As a Guest, using the existing Code, Login as the User.
4. As a different guest (8210) repeat 2&3 with this PR in place.

For both, the user was presented with an error page because the authority ID doesn't match the Account.

The Below is a merged view of Accounts and Applicants

For Guest 8209 we can see the negative behavior that the Applicants were merged:
* Applicant 8209 is associate with Account 8208
* Account 8209 is orphaned
* Applicant 8209 has data copied from 8208: Specifically the Middle Name as bolded in it's applicant data.

For Guest 8210 we can see the desired behavior: None of the above is true.
* The Applicant and Account are associated with each other and not 8208. No data from 8208 was copied to 8210

```
account | applicant |  id  | preferred_locale |                                                                                                                                                                                                                                                                                                                                                                                                       object                                                                                                                                                                                                                                                                                                                                                                                                       | account_id |      when_created       | first_name | middle_name | last_name | email_address | country_code | phone_number | date_of_birth | suffix | applications | application_ids 
---------+-----------+------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-------------------------+------------+-------------+-----------+---------------+--------------+--------------+---------------+--------+--------------+-----------------
    8208 |      8208 | 8208 | en-US            | {"applicant": {"sample_id_question": {"id": "324234324", "updated_at": 1770328400916, "program_updated_in": 10}, "sample_name_question": {"last_name": "M", "first_name": "Shane", "updated_at": 1770328400916, "middle_name": "middle name", "program_updated_in": 10}, "sample_text_question": {"text": "sdf", "updated_at": 1770328400916, "program_updated_in": 10}, "sample_email_question": {"email": "sdfs@df.com", "updated_at": 1770328400916, "program_updated_in": 10}, "sample_number_question": {"number": 3, "updated_at": 1770328400916, "program_updated_in": 10}}}                                                                                                                                                                                                                                |       8208 | 2026-02-05 21:51:44.688 | Shane      | middle name | M         |               |              |              |               |        |            2 | 823 824
    8208 |      8209 | 8209 | en-US            | {"applicant": {"sample_id_question": {"id": "324234324", "updated_at": 1770328400916, "program_updated_in": 10}, "sample_name_question": {"last_name": "Guest LN", "first_name": "Guest", "updated_at": 1770328498369, "MIDDLE_NAME": "middle name", "program_updated_in": 11}, "sample_text_question": {"text": "sdf", "updated_at": 1770328400916, "program_updated_in": 10}, "sample_email_question": {"email": "sdfs@df.com", "updated_at": 1770328400916, "program_updated_in": 10}, "sample_number_question": {"number": 3, "updated_at": 1770328400916, "program_updated_in": 10}, "sample_file_upload_question": {"updated_at": 1770328484797, "file_key_list": ["applicant-8209/program-11/block-1/applicant-8182%252Fprogram-8%252Fblock-1%252Fapplicant-8183.png (1).png"], "program_updated_in": 11}}} |       8208 | 2026-02-05 21:54:31.431 | Guest      |             | Guest LN  |               |              |              |               |        |            1 | 825
    8209 |           |      |                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |            |                         |            |             |           |               |              |              |               |        |            0 | 
    8210 |      8210 | 8210 | en-US            | {"applicant": {"sample_name_question": {"last_name": "Guest LN", "first_name": "Guest FN", "updated_at": 1770329043568, "program_updated_in": 11}, "sample_file_upload_question": {"updated_at": 1770329030982, "file_key_list": ["applicant-8210/program-11/block-1/Screenshot 2025-10-11 at 10.23.25 PM (6).png"], "program_updated_in": 11}}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |       8210 | 2026-02-05 22:03:31.483 | Guest FN   |             | Guest LN  |               |              |              |               |        |            1 | 826
```


The following shows the normal merge flow without the exception. The data has the same qualities in 8209 above, but they are currently WAI in this case.

Before merge
```
 account | applicant |  id  | preferred_locale |                                                                                 object                                                                                  | account_id |      when_created       | first_name | middle_name  | last_name | email_address | country_code | phone_number | date_of_birth | suffix | applications | application_ids 
---------+-----------+------+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-------------------------+------------+--------------+-----------+---------------+--------------+--------------+---------------+--------+--------------+-----------------
    8211 |      8211 | 8211 | en-US            | {"applicant": {"sample_name_question": {"last_name": "M", "first_name": "Shane", "updated_at": 1770395694495, "middle_name": "Logged in MN", "program_updated_in": 5}}} |       8211 | 2026-02-06 16:34:29.216 | Shane      | Logged in MN | M         |               |              |              |               |        |            1 | 827
    8212 |      8212 | 8212 | en-US            | {"applicant": {"sample_name_question": {"last_name": "Guest LN", "first_name": "Guest FN", "updated_at": 1770395711793, "program_updated_in": 5}}}                      |       8212 | 2026-02-06 16:35:04.055 | Guest FN   |              | Guest LN  |               |              |              |               |        |            1 | 828
```

After Merge:

```
 account | applicant |  id  | preferred_locale |                                                                                      object                                                                                       | account_id |      when_created       | first_name | middle_name  | last_name | email_address | country_code | phone_number | date_of_birth | suffix | applications | application_ids 
---------+-----------+------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-------------------------+------------+--------------+-----------+---------------+--------------+--------------+---------------+--------+--------------+-----------------
    8211 |      8211 | 8211 | en-US            | {"applicant": {"sample_name_question": {"last_name": "M", "first_name": "Shane", "updated_at": 1770395694495, "middle_name": "Logged in MN", "program_updated_in": 5}}}           |       8211 | 2026-02-06 16:34:29.216 | Shane      | Logged in MN | M         |               |              |              |               |        |            1 | 827
    8211 |      8212 | 8212 | en-US            | {"applicant": {"sample_name_question": {"last_name": "Guest LN", "first_name": "Guest FN", "updated_at": 1770395711793, "middle_name": "Logged in MN", "program_updated_in": 5}}} |       8211 | 2026-02-06 16:35:04.055 | Guest FN   |              | Guest LN  |               |              |              |               |        |            1 | 828
    8212 |           |      |                  |                                                                                                                                                                                   |            |                         |            |              |           |               |              |              |               |        |            0 | 
```

## Release notes

Improves error handling in the guest merge flow. If an error is encountered data will no longer be merged.

### Checklist

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if this PR includes functionality changes and neither you nor the primary reviewer is an admin)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Instructions for manual testing

For regression testing, doing any standard guest login evaluation will suffice.  This PR should in no way affect the happy path for guest login.

For in depth technical testing see the higher level Manual Testing section which indicates what I did.

### Issue(s) this completes

Fixes #11304, #12379

### CODE REVIEW

File: server/app/auth/oidc/CiviformOidcProfileCreator.java [hunk 1]
```diff
@@ -42,12 +43,15 @@ public abstract class CiviformOidcProfileCreator extends OidcProfileCreator {
...
+      OidcConfiguration configuration,
+      OidcClient client,
+      OidcClientProviderParams params,
+      DatabaseExecutionContext dbExecutionContext) {
     super(Preconditions.checkNotNull(configuration), Preconditions.checkNotNull(client));
     this.profileFactory = Preconditions.checkNotNull(params.profileFactory());
     this.accountRepositoryProvider = Preconditions.checkNotNull(params.accountRepositoryProvider());
     this.civiFormProfileMerger =
-        new CiviFormProfileMerger(profileFactory, accountRepositoryProvider);
+        new CiviFormProfileMerger(profileFactory, accountRepositoryProvider, dbExecutionContext);
```
Comment (rockycodes) [inline server/app/auth/oidc/CiviformOidcProfileCreator.java:54]: question (maybe blocking): In your PR description you said

```
Moves the Async wrapper in CiviformOidcProfileCreator::mergeCiviFormProfile which runs the changes in the DatabaseContext, to the higher call stack level in CiviFormProfileMerger::mergeProfiles
```

but I'm not seeing any changes to `mergeCiviFormProfile` in this file. What am I missing?

**Review by rockycodes — CHANGES_REQUESTED** [review]
Looks good! Just one clarifying comment about if there should be a change to `CiviformOidcProfileCreator::mergeCiviFormProfile`

**Review by rockycodes — APPROVED** [review]

File: server/app/auth/oidc/CiviformOidcProfileCreator.java (hunk 1 above)
Comment (shane-exygy) [reply server/app/auth/oidc/CiviformOidcProfileCreator.java:54]: Good catch, there isn't an async here and I just confused myself it seems.  I updated the section you pulled that comment from, in effect removing that line, but restructuring it too; and reverified it was correct.

**Review by rockycodes — APPROVED** [review]

File: server/app/auth/CiviFormProfileMerger.java [hunk 2]
```diff
@@ -72,15 +91,13 @@ private CiviFormProfile mergeApplicantAndGuestProfile(
       ApplicantModel applicantInDatabase, CiviFormProfile sessionGuestProfile) {
     // Merge guest applicant data with already existing account in database.
     // TODO(#11304#issuecomment-3233634460): this merges the older account
-    // into the newer which is likely incorrect.
+    // into the newer which is incorrect.
```
Comment (swatkat1) [inline server/app/auth/CiviFormProfileMerger.java:94]: [Non-blocking] - Is merging older into newer still incorrect?

Comment (shane-exygy) [reply server/app/auth/CiviFormProfileMerger.java:94]: Yes, this PR doesn't change that and that will be the core of the "fixing merging" work.

I just wanted to remove the ambiguity in saying it "likely" is incorrect, because it is from our desires now.
