### PR TITLE
Remove program details link if no program detail url is specified.

### LINKED ISSUE #8599: Search engines are indexing URLs with program ids, which break
**Describe the bug**
Google/Bing is indexing /program/:id: program pages with a specific ID, which breaks

For example: https://myarciviform.arkansas.gov/programs/471 is indexed, and errors with `Program 471 not found`

### PR DESCRIPTION
**Pull request by devin-civi**
### Description

This removes the program details link if no program detail url is specified for the program. This link is currently in two places, on program cards, and on the ineligible page. 

The reasoning for this is the page that it leads to doesn't have any extra information, is only visible in this one special case, and doesn't have a stable link (it's based on the versioned program ID) which breaks search engine indexing (Issue #8599)

This change doesn't remove the code for the underlying (now unused) page. A following PR will include that, as well as a redirect back to home when that route is accessed.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).

#### User visible changes

- [x] Made equivalent changes in Thymeleaf for applicant-facing features and changes (or created an issue in the [Northstar epic](https://github.com/orgs/civiform/projects/1/views/94) to track that it's missing from Thymeleaf)

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #8599

### CODE REVIEW

**Comment by devin-civi** [comment]
* **#8651** <a href="https://app.graphite.dev/github/pr/civiform/civiform/8651?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devin-civi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by devin-civi** [comment]
* **#8651** <a href="https://app.graphite.dev/github/pr/civiform/civiform/8651?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devin-civi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: server/app/views/applicant/NorthStarApplicantIneligibleView.java [hunk 1]
```diff
@@ -77,15 +77,17 @@ public String render(Params params) {
...
-    String linkHref =
-        program.externalLink().isEmpty()
-            ? applicantRoutes.show(params.profile(), params.applicantId(), program.id()).url()
-            : program.externalLink();
-    String linkText =
-        params.messages().at(MessageKey.LINK_PROGRAM_DETAILS.getKeyName()).toLowerCase(Locale.ROOT);
-    String linkHtml =
-        "<a href=\"" + linkHref + "\" target=\"_blank\" class=\"usa-link\">" + linkText + "</a>";
-    context.setVariable("programLinkHtml", linkHtml);
+    String linkHref = program.externalLink();
```
Comment (rockycodes) [inline server/app/views/applicant/NorthStarApplicantIneligibleView.java:80]: suggestion (blocking): leave this as is for now with a TODO. i will be building off of this in the north start work i'm about to be doing.

**Review by rockycodes — CHANGES_REQUESTED** [review]
I haven't done a super in depth review of this yet because I have some bigger picture questions. My preference would be to address this issue by setting the program urls to be the program admin name rather than id, but was that not a viable solution?

If this PR is the way to go, I want to make sure we have sign off from product/design since it will change the look and behavior of the home page. I also want to request that you leave any north star code as it is (but feel free to add a todo) since I'll be working on that soon and removing the external url option.

**Comment by devin-civi** [comment]
Changing Rocky to primary reviewer since this affects her work. And as mentioned on chat this can wait until next week if needed I think.

File: server/app/views/applicant/NorthStarApplicantIneligibleView.java (hunk 1 above)
Comment (rockycodes) [reply server/app/views/applicant/NorthStarApplicantIneligibleView.java:80]: Is it an option to leave this as is for now with a TODO? Same question for the other north star changes. Since the public can't access these views yet, I'm hoping leaving them as is won't affect anything.

File: server/app/views/applicant/ProgramCardViewRenderer.java [hunk 2]
```diff
@@ -223,25 +223,24 @@ public LiTag createProgramCard(
     programData.with(title, description);
 
     // Use external link if it is present else use the default Program details page
```
Comment (rockycodes) [inline server/app/views/applicant/ProgramCardViewRenderer.java:225]:
```suggestion
    // Create the "Program details" link if an external link if it is present
```

File: server/test/controllers/applicant/ApplicantProgramsControllerTest.java [hunk 3]
```diff
@@ -151,12 +151,11 @@ public void test_deduplicate_inProgressPrograms() {
             .join();
 
     assertThat(result.status()).isEqualTo(OK);
-    // A program's name appears in the index view page content 3 times:
+    // A program's name appears in the index view page content 2 times:
     //  1) Program card title
-    //  2) Program details aria-label
-    //  3) Apply button aria-label
+    //  2) Apply button aria-label
```
Comment (rockycodes) [inline server/test/controllers/applicant/ApplicantProgramsControllerTest.java:156]: suggestion (maybe blocking): Add an external url to this program so that we can still test that the program name shows up in the aria label (unless this is already tested elsewhere).

**Review by rockycodes — CHANGES_REQUESTED** [review]
looks good! my biggest question is if we could leave the North Start stuff as is.

File: server/app/views/applicant/NorthStarApplicantIneligibleView.java (hunk 1 above)
Comment (rockycodes) [reply server/app/views/applicant/NorthStarApplicantIneligibleView.java:80]: No biggie if not, I can add it back in when I get there.

**Review by devin-civi — COMMENTED** [review]
Sorry I forgot to send out these comments

File: server/test/controllers/applicant/ApplicantProgramsControllerTest.java (hunk 3 above)
Comment (rockycodes) [reply server/test/controllers/applicant/ApplicantProgramsControllerTest.java:156]: Ohhh I see what you mean! Ok I think that aria-label thing is tested elsewhere so this I agree this is not needed.

**Review by rockycodes — APPROVED** [review]
