### PR TITLE
Fix AWS policy condition error on file upload question when SAVE_ON_ALL_ACTIONS flag is on

### LINKED ISSUE #6737: With SAVE_ON_ALL_ACTIONS flag on, file upload doesn't work if you click "Review" or "Previous"
After submitting  https://github.com/civiform/civiform/pull/6651, some tests in `file.test.ts` started failing, but only [on staging](https://github.com/civiform/civiform-staging-deploy/actions/runs/8052441929), not locally or on GitHub actions.

The problem is that when you upload a file then click "Review" or "Previous", AWS sends this error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Invalid according to Policy: Policy Condition failed: ["eq", "$success_action_redirect", "https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/NEXT_BLOCK"]</Message>
<RequestId>YN2BF2JC815X9K46</RequestId>
<HostId>9T43He5YU7Yc6ttnf+sHrP+tLvTLF/Gn3gDSY1bRsMaJVBh7uOo/ohdJbNQwreSIw37RSttLspo=</HostId>
</Error>
```

What I think's happening: For AWS file uploads to work as part of HTML forms, we provide a lot of hidden inputs to send extra info to AWS. There's two inputs relevant to this issue.

The first input that's relevant is `success_action_redirect`, which specifies where AWS should redirect the user after the file has been uploaded to AWS:

```
<input type="hidden" name="success_action_redirect" value="https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/NEXT_BLOCK">
```

The second input that's relevant is `Policy`, which specifies conditions that the request must meet (see [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/HTTPPOSTForms.html#HTTPPOSTConstructPolicy)).

```
<input type="hidden" name="Policy" value="eyJleHBpcmF0aW9uIjoiMjAyNC0wMi0yNlQyMDo1ODozNS43NzRaIiwiY29uZGl0aW9ucyI6W3siYnVja2V0IjoiZXh5Z3ktY2l2aWZvcm0tZmlsZXMtczMifSxbInN0YXJ0cy13aXRoIiwiJGtleSIsImFwcGxpY2FudC02MDMyOTYvcHJvZ3JhbS05MjE0OC9ibG9jay03LyJdLFsiY29udGVudC1sZW5ndGgtcmFuZ2UiLCIxIiwiMTA0ODU3NjAwIl0seyJzdWNjZXNzX2FjdGlvbl9yZWRpcmVjdCI6Imh0dHBzOi8vc3RhZ2luZy1hd3MuY2l2aWZvcm0uZGV2L3Byb2dyYW1zLzkyMTQ4L2Jsb2Nrcy83L3VwZGF0ZUZpbGUvdHJ1ZS9ORVhUX0JMT0NLIn0seyJ4LWFtei1jcmVkZW50aWFsIjoiQVNJQVVPSlNFQTZXVDRYVVlaRTUvMjAyNDAyMjYvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJ9LHsieC1hbXotYWxnb3JpdGhtIjoiQVdTNC1ITUFDLVNIQTI1NiJ9LHsieC1hbXotZGF0ZSI6IjIwMjQwMjI2VDAwMDAwMFoifSx7IngtYW16LXNlY3VyaXR5LXRva2VuIjoiSVFvSmIzSnBaMmx1WDJWakVOMy8vLy8vLy8vLy93RWFDWFZ6TFdWaGMzUXRNU0pITUVVQ0lEd0o5Nkx0T3JrQkN1eGIyaytGaEJURjh0enBHYnk0M0FMYnRHeklXSFJnQWlFQWt4Z2RKQTJaOTdlUy9EV0REQzVLdUJEQ2tjYVJxbGRvMDRjQ1NoTkFSY0lxL0FNSXh2Ly8vLy8vLy8vL0FSQUFHZ3d6TURVMU9EUTJOekEyTXpjaURIdmdkcUZ5RGZjQk1lMTR6U3JRQXlIeklYaXJHUTAzNnpoOU4wOHFGVU1ieXVFbzVGbnhGUlVGUitTem5odDZMdkdGRDdHTFdMWUdoa2RqNXZVVEc2VUozTXVsbndoTkNYZ0QwbE45VXNCa3ZobmttbzdCeGpxcUlwaEk4K2srd2VGOWpob29tM0RPeThVaU5PQUJ5cE9VUFZCRENKQ1FCbGcxRDhLeTVVTnlGZWRkc0ZLT0p2Y3J6MkRMWmNxWnJITzcxbzgwY2VMUWdTL1ZKWXdDVTUySVhFRU9TVFNuUnJQdkczc082REpMM3lLdExLaE5lNGJpZ2lxa0tpRjIxRkRBSWg4ZDQ0dkI0WGVKUkFHd3FRWGhSblU2SS9JVWxQNGhFK1BBR0ZXOUhoSmlhZGdpYlR2bnQ2b09vU2ZiaElMY1E2bW5IVmhldEZGWGhQQmFkMSs0bDQzSFhkeWF5ZytCV0VaejRrU09Wd0FOeEpZdm1obDJBNDY2OXN6NkpZd3R6bFRlSWhyU0xhckJ6VlZ6c2NsbWFmYnZSRVFkMHhzQlB6OFVrS0t2bXo4dlhIcGphT1h4d3J3dTZXTDl4YzJFYnk2dVFDejFVem1Xek1EaFN2Umd1Z0dwOUNXakRFeHdueFJxQXQzb3BwYnRRYUZuZldIVzJVWkZqOWhubXBrTHpHbyt5cXFwekZsMTREclpjbEtFTElka3RxeEszZ1o1TWJuUmhhL2NyOXhWWXFsRE9yYVUxbERWaWsyM2FWM2ZDbmprdE5lZlozVU5PeG9nM3AyTytReDMrdWVXWFc2MnpZNk5uS2kxb2Rrem9UR0lwSUlKa3VJZ1ZYaFVNT0xxODY0R09xVUJFNHNpSlBVeW96dE9Gb0xpdUM4R0FQc1FGTVdNY3AyOW5hVGUrTVpCWTNQWUVCYlMzaFF1L0h0MWZ1VGJadkRzMGR5Rjh4YzdkSzhHYStGandrRWM2NFlWQzhuTnNMR0djQmdqZnpxYm15b1BoeHIybjltZEUzOGR6MUZDWTZDM044V0svbzRpaUFFRldMRHh3UlZpRVJ6YTY4WVlBTVYrNEg2QjNZVWFDOE1ReERqQXlRUkNCTGVmWnJhWUsvTDlEcS94QnowbzRyYmwxQ0JHS1ZVSmoxR3lxOEFoIn1dfQ==">
```

This `Policy` input embeds a lot of things, [including the success_action_redirect](https://github.com/civiform/civiform/blob/8314f7442c9e93ed60bb3260f2a37ed1ab71417b/server/app/services/cloud/aws/SignedS3UploadRequest.java#L246-L256).

https://github.com/civiform/civiform/pull/6651 manually modified the `<input type="hidden" name="success_action_redirect">` element to redirect to the correct place depending on what button the user clicked ("Review" / "Previous" / "Save & next"). However, it didn't modify the `<input type="hidden" name="Policy">` input. So AWS compares the `success_action_redirect` value in the raw `success_action_redirect <input>` to the `success_action_redirect` value encoded within the `Policy` `<input>`, sees that they're different, and prevents the file upload. This is intentional on AWS's part, because they don't want a malicious user to be able to change the `success_action_redirect` client-side. We'll need to figure out a different strategy for implementing this.

### PR DESCRIPTION
**Pull request by caitlinshk**
### Description

When the `SAVE_ON_ALL_ACTIONS` flag is on, we want to make sure we save user data whenever the user clicks any button -- "Save&next", "Review", or "Previous". PR https://github.com/civiform/civiform/pull/6651 updated the file upload question to save the file on all button clicks, and it did this by using JavaScript to change the `<input name="success_action_redirect">` part of the file upload form to redirect to different places depending on which button was clicked:
 - "Review" button: https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/REVIEW_PAGE
 - "Previous" button: https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/PREVIOUS_BLOCK
 - "Save&next" button: https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/NEXT_BLOCK

This all worked on a local server, which uses LocalStack as a fake AWS backend. However, it's failing on staging environments, which use the real AWS backend. The error AWS sends us is a policy condition failure:

```
<Error>
<Code>AccessDenied</Code>
<Message>Invalid according to Policy: Policy Condition failed: ["eq", "$success_action_redirect", "https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/NEXT_BLOCK"]</Message>
<RequestId>YN2BF2JC815X9K46</RequestId>
<HostId>9T43He5YU7Yc6ttnf+sHrP+tLvTLF/Gn3gDSY1bRsMaJVBh7uOo/ohdJbNQwreSIw37RSttLspo=</HostId>
</Error>
```

**Here's what's happening:** The file upload form has a lot of hidden input fields that AWS uses to verify that a file upload request is legitimate. The two input fields we care about for this are:
 - `<input name="success_action_redirect">`, which contains the URL that AWS should send the user to once the file upload succeeds
 - `<input name="Policy">`, which is a base-64 encoded string of policy requirements that AWS should enforce like security tokens, maximum content size, etc. One of the policy requirements is that [the `success_action_redirect` URL should exactly match the redirect URL we specify](https://github.com/civiform/civiform/blob/8314f7442c9e93ed60bb3260f2a37ed1ab71417b/server/app/services/cloud/aws/SignedS3UploadRequest.java#L246-L256).
 
If the `success_action_redirect` URL embedded inside the `<input name="Policy">` element doesn't match the `success_action_redirect` URL listed in the  `<input name="success_action_redirect">` element, then AWS throws this policy condition error. This is intentional and for security reasons: A malicious actor could manually edit the  `<input name="success_action_redirect">` element to be a URL that they own, and then they would be able to see the file names that are being uploaded to our AWS bucket.

But, now that we need to redirect the user to different places depending on what button they clicked, we can't have the policy require an exact match.

**Here's how this PR fixes it:** Luckily, AWS lets us be a bit flexible with the `success_action_redirect` URL in the Policy: We can say that the `success_action_redirect` URL just has to start with a certain prefix. **This PR updates the Policy to make the `success_action_redirect` URL be prefix-matching instead of exact-matching for the file upload question.** We set the prefix to be `https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true`, and that allows the JavaScript to append `/NEXT_BLOCK`, `/PREVIOUS_BLOCK`, or `/REVIEW_PAGE` to the end of the `<input name="success_action_redirect">` element without causing an AWS policy condition failure.

 
#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

#### New Features

- [x] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [x] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

I deployed this change to my custom deploy at https://caitlinshk-dev.civiform.dev and tested these cases:

1. To test with the flag on:
   -  Enable the SAVE_ON_ALL_ACTIONS flag.
   - As an applicant, apply to a program with a file upload question.
   - Upload a file then click "Review".
   - Verify you don't see the error shown in https://github.com/civiform/civiform/issues/6737.
   - Verify you're taken to the review page and that your file was successfully saved.
   - Do the same test for the "Previous" and "Review" buttons.

2. To test "Save&next" with the flag off:
   -  Disable the SAVE_ON_ALL_ACTIONS flag.
   - As an applicant, apply to a program with a file upload question.
   - Upload a file then click "Save&next".
   - Verify you don't see the error shown in https://github.com/civiform/civiform/issues/6737.
   - Verify you're taken to the next page that your file was successfully saved.
   
3. To test "Previous"/"Review" with the flag off:
   -  Disable the SAVE_ON_ALL_ACTIONS flag.
   - As an applicant, apply to a program with a file upload question.
   - Upload a file then click "Previous".
   - Verify you don't see the error shown in https://github.com/civiform/civiform/issues/6737.
   - Verify you're taken to the right page.
   - Verify the file you uploaded **wasn't** saved (since that's the old behavior).
   - Do the same test for the "Review" button.

I also ran `BASE_URL=https://caitlinshk-dev.civiform.dev bin/run-browser-tests-local file.test.ts`, which runs the previously-failing browser tests on my custom deploy, and all tests passed.

### Issue(s) this completes

Fixes #6737

### CODE REVIEW

**Comment by caitlinshk** [comment]
Current dependencies on/for this PR:
* **#6744** <a href="https://app.graphite.dev/github/pr/civiform/civiform/6744?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/civiform/civiform/6744?utm_source=stack-comment).

File: server/app/controllers/applicant/ApplicantRequestedAction.java [hunk 1]
```diff
@@ -19,4 +19,18 @@ public enum ApplicantRequestedAction {
...
+
+  /**
+   * Removes the applicant-requested action from the end of the provided {@code url} and returns the
+   * stripped URL, or returns the original URL if it doesn't end in an applicant-requested action.
+   */
+  public static String stripActionFromEndOfUrl(String url) {
+    for (ApplicantRequestedAction action : ApplicantRequestedAction.values()) {
+      String actionString = "/" + action.name();
+      if (url.endsWith(actionString)) {
+        return url.substring(0, url.indexOf(actionString));
```
Comment (avaleske) [inline server/app/controllers/applicant/ApplicantRequestedAction.java:31]: Would it be better to use the `Uri` standard library class to modify the URL, in case it happens to have a query string or other params on the end that we want to preserve?

Or will that never happen here?

**Review by avaleske — APPROVED** [review]
Makes sense to me!

As a question, but not a request to rework this:
Would this have been a good use-case for HTMX? On click, could HTMX request a new form with a new token, merge it into the existing dom, and then submit the form to AWS?

File: server/test/controllers/applicant/ApplicantRequestedActionTest.java [hunk 2]
```diff
@@ -0,0 +1,62 @@
+package controllers.applicant;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+import org.junit.Test;
+
+public class ApplicantRequestedActionTest {
```
Comment (avaleske) [inline server/test/controllers/applicant/ApplicantRequestedActionTest.java:7]: Do we need a test for if there are query params or an anchor tag as part of the URL?

**Review by avaleske — APPROVED** [review]

**Comment by caitlinshk** [comment]
> Would this have been a good use-case for HTMX? On click, could HTMX request a new form with a new token, merge it into the existing dom, and then submit the form to AWS?

Possibly! HTMX wouldn't request an entire new `<form>` because that would throw away the file that the user uploaded. But HTMX could request just new `<input name="success_action_redirect">` and `<input name="Policy">` elements and swap those in (if swapping is allowed).

File: server/app/controllers/applicant/ApplicantRequestedAction.java (hunk 1 above)
Comment (caitlinshk) [reply server/app/controllers/applicant/ApplicantRequestedAction.java]: At the moment I don't think it can happen here but I think this is a good idea, updated.

File: server/test/controllers/applicant/ApplicantRequestedActionTest.java (hunk 2 above)
Comment (caitlinshk) [reply server/test/controllers/applicant/ApplicantRequestedActionTest.java:7]: Good idea, updated!
