### PR TITLE
Service area conversion job

### LINKED ISSUE #7944: Applicants are submitting ineligible Trees for Neighborhoods applications when their address is outside of Seattle
**Describe the bug**
The trees for neighborhoods program is only eligible to residents of Seattle. This program includes the following eligibility criteria. 

Image

However, two applicants were able to submit applications with addresses outside the service area on 7/1/24 at 2024/07/01 12:33:16 PM PDT and 2024/07/01 03:09:56 PM PDT. 

Image

**Expected behavior**
Applicants with addresses outside the City of Seattle service area should not be able to submit and application to Trees for Neighborhoods.

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

Job to convert applicant and application json data. The conversion looks for `service_area` keys and converts them from a double delimited string to a json object array.

This is needed in order to sanely make doing out of service area eligibility checks work.

#### From

```json
{
  "applicant": {
    "applicant_address": {
      "service_area": "Bloomington_NotInArea_1234,Seattle_InArea_4567"
    }
  }
}
```

#### To

```json
{
  "applicant": {
    "applicant_address": {
      "service_areas": [
        {
          "timestamp": 1234,
          "service_area_id": "Bloomington",
          "service_area_state": "NOT_IN_AREA"
        },
        {
          "timestamp": 4567,
          "service_area_id": "Seattle",
          "service_area_state": "IN_AREA"
        }
      ],
    }
  }
}
```

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).

#### Durable jobs

Read the docs [here](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates)

- [x] Assigned two reviewers
- [x] Included a rollback plan and a job to undo the data changes if appropriate

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #7944; #8389

### CODE REVIEW

**Review by rockycodes — APPROVED** [review]
This lgtm! Just a few non-blocking comments/suggestions.

File: server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java [hunk 1]
```diff
@@ -0,0 +1,369 @@
...
+              "updated_at": 1726495893773,
+              "service_area": "Bloomington_NotInArea_1234,Seattle_InArea_4567",
+              "well_known_id": 4326,
+              "program_updated_in": 2139
+            }
+          }
+        }
+        """;
+
+    //
```
Comment (avaleske) [inline server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java:154]: missing comment?

Comment (avaleske) [reply server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java:154]: here and elsewhere

File: server/app/durablejobs/jobs/ConvertAddressServiceAreaToArrayJob.java [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+  }
+
+  @Override
+  public void run() {
+    logger.info("Run - Begin");
+
+    try (Transaction jobTransaction = database.beginTransaction(TxIsolation.SERIALIZABLE)) {
+      int errorCount = 0;
+
+      // Filter to only include rows what have a service_area key that is a string type. Vastly
```
[the remark this answers is not in the document]
Comment (gwendolyngoetz) [reply server/app/durablejobs/jobs/ConvertAddressServiceAreaToArrayJob.java:56]: Spot of tea?

File: server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java [hunk 3]
```diff
@@ -0,0 +1,369 @@
...
+        new Object[] {"a_InArea_1", "a", ServiceAreaState.IN_AREA, 1L},
+        new Object[] {"a_b_InArea_1", "a_b", ServiceAreaState.IN_AREA, 1L},
+        new Object[] {"a_b_c_d_1_2-_1_InArea_1", "a_b_c_d_1_2-_1", ServiceAreaState.IN_AREA, 1L});
+  }
+
+  @Test
+  @Parameters(method = "canConvertStringToArrayParameters")
+  public void canConvertStringToArray(
+      String value, String serviceAreaId, ServiceAreaState state, Long timestamp) {
+    var row = ConvertAddressServiceAreaToArrayJob.buildServiceAreaArrayFromString(value);
```
[the remark this answers is not in the document]
Comment (gwendolyngoetz) [reply server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java:48]: No specific reason.

File: server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java [hunk 4]
```diff
@@ -0,0 +1,369 @@
...
+        .isTrue();
+
+    // Assert getting the typed list returns expected values
+    var serviceAreas = newApplicationData.readServiceAreaList(serviceAreaPath);
+    assertThat(serviceAreas.isPresent()).isTrue();
+    assertThat(serviceAreas.get().size()).isEqualTo(2);
+
+    var bloomington =
+        serviceAreas.get().stream()
+            .filter(x -> x.getServiceAreaId().equals("Bloomington"))
```
Comment (avaleske) [inline server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java:357]: **thought, non-blocking**: in general I don't _love_ having the expected values outside of the test method, since then you have to go look somewhere else to see everything that the test is looking for, but I don't feel strongly enough in this case to ask you to refactor it, esp since this is a one-off thing.

File: server/app/durablejobs/jobs/ConvertAddressServiceAreaToArrayJob.java [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+                .collect(ImmutableList.toImmutableList());
+
+        JsonNode newJsonNode = objectMapper.valueToTree(items);
+
+        // Singular "service_area"
+        ((ObjectNode) questionJsonNode).remove(serviceAreaName);
+
+        // Plural "service_areas"
+        ((ObjectNode) questionJsonNode)
+            .set(Scalar.SERVICE_AREAS.name().toLowerCase(Locale.ROOT), newJsonNode);
```
Comment (avaleske) [inline server/app/durablejobs/jobs/ConvertAddressServiceAreaToArrayJob.java:122]: **question, non-blocking** would it be worth using Path.create() utils so any future SWEs looking at this code follow that pattern, instead of relying on knowing that paths are supposed to be lowercase?

**Review by avaleske — APPROVED** [review]

File: server/app/durablejobs/jobs/ConvertAddressServiceAreaToArrayJob.java (hunk 5 above)
Comment (gwendolyngoetz) [reply server/app/durablejobs/jobs/ConvertAddressServiceAreaToArrayJob.java]: Yes. This was an oversight. Done.

File: server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java (hunk 4 above)
Comment (gwendolyngoetz) [reply server/test/durablejobs/jobs/ConvertAddressServiceAreaToArrayJobTest.java:361]: Yeah, I get where you're coming from. In this case I'm more concerned with being certain everything is uniform.
