### PR TITLE
fix: PDF and JSON exports to filter displayable options (#11595)

### LINKED ISSUE #11595: PDF preview and JSON export show all Yes/No options regardless of admin configuration
**Describe the bug**
When an admin configures a Yes/No question with only specific options selected (e.g., only Yes/No), the PDF preview and JSON export incorrectly display all 4 options (Yes, No, Not sure, Maybe) instead of only the configured options.

**To Reproduce**

1. Create Yes/No question with only Yes/No selected (Not sure and Maybe unchecked)
2. Publish program
3. Click "Download PDF preview" button
4. Observe PDF shows all 4 options
5. Export program as JSON
6. Observe JSON includes all 4 options

**Expected behavior**

- PDF preview should only show admin-selected options
- JSON export should only include options where `displayInAnswerOptions=true`
- Export/preview should match what applicants see

**Actual Behavior**

- PDF preview shows all 4 options
- JSON export includes all 4 options
- Display doesn't respect admin configuration

**Affected Components**:

- PDF generation logic for Yes/No questions
- JSON export serialization
- displayInAnswerOptions field filtering in exports

**Related to**:

Issue #10778 (Admin control of options)
Issue #11250 Export/preview functionality

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by osajulian-dev**
### Description
This PR fixes a data integrity issue where applicants could submit invalid/removed Yes/No options after an admin updates the question configuration.
- Add getDisplayableOptionsForLocaleOrDefault() to MultiOptionQuestionDefinition
- Add getDisplayableOptionAdminNames() to MultiOptionQuestionDefinition
- Add getDisplayableOptions() methods to SingleSelectQuestion and MultiSelectQuestion
- Update PdfExporter to use getDisplayableOptions()
- Update QuestionJsonSampler to use getDisplayableOptions() for sample data
- Update ApiDocsView to use getDisplayableOptionAdminNames() for current options

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [X] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [X] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [X] Added an additional reviewer from `civiform/eng-admin` as FYI (if the primary reviewer is not an admin and this PR includes functionality changes)
- [X] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

#### Database evolutions

Read the guidelines [here](https://github.com/civiform/civiform/wiki/Database#writing-database-evolutions)

- [ ] Assigned two reviewers
- [ ] Guarded against already existing resources using `IF NOT EXISTS` and `IF EXISTS`
- [ ] Downs created to undo changes in Ups
- [ ] Every comment in script should begin with -- and not # --- unless it denotes Ups or Downs. See [here](https://www.playframework.com/documentation/2.9.x/Evolutions) for details.
- [ ] Tested both the Downs and the Ups scripts manually (When testing, include all comments from the evolution in your test script to ensure any syntax errors in the comments are caught.)
- [ ] Data migrations aren't being done (please use a [Durable Job](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates) if doing a data migration)
- [ ] Update the model documentation in our [wiki](https://github.com/civiform/civiform/wiki/Database) if necessary

#### Durable jobs

Read the docs [here](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates)

- [ ] Assigned two reviewers
- [ ] Included a rollback plan and a job to undo the data changes if appropriate

#### User visible changes

- [ ] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) any new strings
  - [ ] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [ ] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Made equivalent changes in Thymeleaf for applicant-facing features and changes (or created an issue in the [Northstar epic](https://github.com/orgs/civiform/projects/1/views/94) to track that it's missing from Thymeleaf)
- [ ] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order
- [ ] Performed manual accessibility tests for any applicant-facing changes or any new admin-facing features. See [manual-accessibility-testing](https://github.com/civiform/civiform/wiki/Accessibility#manual-accessibility-testing)
- [ ] Manually tested with a right-to-left language

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

1. Create a Yes/No question with all 4 options enabled (Yes, No, Maybe, Not sure)
2. Add to a program and publish
3. Admin: Disable "Maybe" and "Not sure" options (uncheck displayInAnswerOptions)
4. Generate PDF preview - verify only "Yes" and "No" appear
5. Check API docs - verify "Current options" shows only "Yes" and "No"
6. Check JSON API sample data - verify only uses "Yes" or "No" values

### Issue(s) this completes

Fixes #11595

### CODE REVIEW

File: server/app/services/export/QuestionJsonSampler.java [hunk 1]
```diff
@@ -496,7 +496,7 @@ public void addSampleData(
         SampleDataContext sampleDataContext, ApplicantQuestion applicantQuestion) {
       ApplicantData applicantData = sampleDataContext.getApplicantData();
       ImmutableList<LocalizedQuestionOption> questionOptions =
-          applicantQuestion.createMultiSelectQuestion().getOptions();
+          applicantQuestion.createMultiSelectQuestion().getDisplayableOptions();
```
Comment (melanie-exygy) [inline server/app/services/export/QuestionJsonSampler.java:499]: question (non-blocking):  I'm testing the json export locally with and without this line change, but I don't see a difference in the json.  In both cases, the json has all options, but "displayInAnswerOptions" is false for the two options that I didn't select as an admin.  Is this change affecting the behavior somewhere else that I haven't thought of testing?

Comment (osajulian-dev) [reply server/app/services/export/QuestionJsonSampler.java:499]: There are actually two different JSON exports

  1. Applicant Data API Export (What this PR fixes)

- Endpoint: /api/v1/programs/{slug}/applications
- What it shows: Only the selected answer (e.g., "yes") - not the full list of options
- Fix applied: The sample data in API docs now uses getDisplayableOptions() to select from only visible options

2.  Program Migration Export (What you might be seeing)

-   Endpoint: Admin → Programs → Export Program
-  What it shows: The full question definition including ALL options with their displayInAnswerOptions field
-  Intentional behavior: This needs to show all options (including hidden ones) so the configuration can be fully recreated in another environment

Which JSON export were you looking at when you saw all options? If it was the program migration export, then that's actually correct behavior - we want admins to see the full configuration there. If it was the applicant data API, could you share more details about what you're seeing?

Regarding the browser test suggestion - that's a great idea! Would you like me to add a test that verifies:
  1. PDF exports only show displayable options?
  2. API sample data only uses displayable options?

Comment (melanie-exygy) [reply server/app/services/export/QuestionJsonSampler.java:499]: Ah, I see.  Yes, I was looking at the program migration export.

As for the browser tests, I don't think either PDF export or the API are part of browser tests because they both depend on additional tools (an API client or a PDF viewer).
