### PR TITLE
fix: Add backend validation and UI fixes for program overview

### LINKED ISSUE #9858: [Program Overview] Fast Follows
1. Backend doesn’t check short description length, only FE.  If you use DevTools and make the short description longer than 100 chars it is accepted.  
2. Each step title allows unlimited characters, we should bound it at a certain #. 
3. Short description can be a input element instead of text area.  
4. Short description does not wrap on the program card properly if there are no natural wrapping characters (use a string of all numbers to repro).

### PR DESCRIPTION
**Pull request by osajulian-dev**
### Description
This PR addresses three bugs related to the Program Overview feature:                                                                                                                                                                   
                                                                                                                                                                                                                            **Backend validation for short description** - Added server-side validation to enforce 100 character limit (frontend had validation but backend did not)                                                                             
                                                                                                                                                                                                                                     **Backend validation for step titles** - Added server-side validation to enforce 1000 character limit to match frontend                                                                                                              
                                                                                                                                                                                                                                          **Short description field type** - Changed from textarea to single-line input element since short descriptions should not contain line breaks                                                                        

### Checklist

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [X] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [X] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if this PR includes functionality changes and neither you nor the primary reviewer is an admin)
- [X] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Instructions for manual testing

- Create a program and verify short description field is now a single-line input (not textarea)
- Use DevTools to bypass frontend maxlength on short description, submit >100 chars, verify backend rejects with error
- Use DevTools to bypass frontend maxlength on step title, submit >1000 chars, verify backend rejects with error

### Issue(s) this completes

Fixes #9858

### CODE REVIEW

File: server/app/services/program/ProgramService.java [hunk 1]
```diff
@@ -940,6 +945,12 @@ ImmutableSet.Builder<CiviFormError> checkApplicationStepErrors(
             CiviFormError.of(
                 String.format("Application step %s is missing a title", Integer.toString(i + 1))));
       }
+      if (title.length() > 1000) {
```
Comment (dkatzz) [inline server/app/services/program/ProgramService.java]: **thought:** 1000 feels long for a title - was that upper bound provided by someone?

Comment (osajulian-dev) [reply server/app/services/program/ProgramService.java]: The issue notes step titles need a limit but doesn't specify a number. I chose 1000 as a conservative upper bound. Happy to lower it - would 200 or 300 be more appropriate for a title field?

Comment (dkatzz) [reply server/app/services/program/ProgramService.java]: @rockycodes and @shreyachatterjee00 any thoughts here? Maybe we copy the short description limit and do 100?

Comment (rockycodes) [reply server/app/services/program/ProgramService.java]: The application step titles should be short, so 100 sounds good to me. We can always up it if it's too short.
