### PR TITLE
Disallow duplicate question keys during import

### LINKED ISSUE #10552: [Program Migration] disallow conflicting JSON path admin names during import
**Describe the bug**
We [currently check](https://github.com/civiform/civiform/blob/fb32527db04cef0d97a6adb2d1b9b9314d48d429/server/app/services/migration/ProgramMigrationService.java#L228) that imported admin names do not conflict with any admin names in the DB. This query strips all non-letter characters (e.g. `foo-bar1-02` is really just `foobar`). 

We should do this same calculation against newly added questions in the import flow to ensure they do not conflict with each other. Right now, we only compare them to the exact string, not to the stripped letters-only version.

**To Reproduce**
1. Import a program with questions that have admin names such as `foo-bar01` and `foo-bar02`
2. Try to fill out that screen that contains those questions
3. Observe the browser error

### PR DESCRIPTION
**Pull request by ezraeinhorn624**
### Description

Add a validation method in the `ProgramMigrationService` to disallow importing questions whose keys (JSON API keys) conflict with each other, or with an existing question. If the key conflicts with an existing question, it is allowed as long the admin name also matches, so it can be handled "smartly" by the duplicate-handling logic. #9628

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Instructions for manual testing

Try importing two questions in the same program with admin names `foo_bar01` and `foobar23`. 

Try saving a question named `foo_bar01` and then importing a question named `foobar23`, and a question named `foo_bar01`

### Issue(s) this completes

Fixes #10552

### CODE REVIEW

**Comment by ezraeinhorn624** [comment]
* **#10554** <a href="https://app.graphite.dev/github/pr/civiform/civiform/10554?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/civiform/civiform/10554?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: server/app/services/migration/ProgramMigrationService.java [hunk 1]
```diff
@@ -155,6 +156,51 @@ public ErrorAnd<ProgramMigrationWrapper, String> deserialize(
     }
   }
 
+  /**
+   * Question keys (names stripped of non-letter characters) in the imported JSON must be unique
```
Comment (auzlee) [inline server/app/services/migration/ProgramMigrationService.java:160]: slight nit: "names stripped of non-letter characters" is partially true. it's stripped of non-letter or space characters, and then spaces are converted to underscores.

(this has the slightly odd result of stripping underscores, and then converting spaces into underscores)

File: server/app/services/migration/ProgramMigrationService.java [hunk 2]
```diff
@@ -155,6 +156,51 @@ public ErrorAnd<ProgramMigrationWrapper, String> deserialize(
...
+    Map<String, ImmutableList<String>> questionKeysToNames = new HashMap<>();
+    for (QuestionDefinition question : questions) {
+      Optional<QuestionModel> conflictingQ = questionRepository.findConflictingQuestion(question);
+      if (conflictingQ.isPresent()
+          && !conflictingQ.get().getQuestionDefinition().getName().equals(question.getName())) {
+        throw new RuntimeException(
+            String.format(
+                "Question key %s (Admin ID \"%s\" stripped of non-letter characters) is already in"
+                    + " use by question %s. Please change the Admin ID so it either matches the"
+                    + " existing one, or compiles to a different key.",
```
Comment (auzlee) [inline server/app/services/migration/ProgramMigrationService.java:176]: nit: I don't think "question key" is a user-facing phrase. I think we use `admin name` for the key, "question name" for the admin-facing name in the admin UI, and "question text" for the applicant-facing question text.

**Review by auzlee — APPROVED** [review]
nits about phrasing but otherwise lgtm

**Review by rockycodes — APPROVED** [review]
lgtm pending austin's suggestions for language updates

File: server/app/services/migration/ProgramMigrationService.java [hunk 3]
```diff
@@ -155,6 +156,51 @@ public ErrorAnd<ProgramMigrationWrapper, String> deserialize(
...
+          });
+    }
+    ImmutableList<ImmutableList<String>> duplicateKeys =
+        questionKeysToNames.values().stream()
+            .filter(names -> names.size() > 1)
+            .collect(ImmutableList.toImmutableList());
+    if (!duplicateKeys.isEmpty()) {
+      throw new RuntimeException(
+          String.format(
+              "Question keys (Admin IDs stripped of non-letter characters) must be unique."
```
[the remark this answers is not in the document]
Comment (ezraeinhorn624) [reply server/app/services/migration/ProgramMigrationService.java]: Standardized the text with docs and correct semantics.

File: server/app/services/migration/ProgramMigrationService.java (hunk 1 above)
Comment (ezraeinhorn624) [reply server/app/services/migration/ProgramMigrationService.java]: Fixed

**Review by rockycodes — APPROVED** [review]
