### PR TITLE
Fix login / select language page titles to be more accessible

### LINKED ISSUE #3545: (WCAG 2.1) Login and language selection page titles are not well defined
Required to meet WCAG 2.1 guidelines. Identified during an accessibility audit against WCAG 2.1.

**WCAG SC**: [2.4.2. Page Titled](https://www.w3.org/TR/WCAG21/#page-titled)

**Observed results**: The Login (Login) and Select language (Application Information: CiviForm) pages do not have proper page titles with well-defined context.

**How to fix**: Currently the titles read "Login" and "Application Information: CiviForm". We should update the text to "Login - CiviForm" and "Select Language - CiviForm".

### PR DESCRIPTION
**Pull request by clouser2**
#### Login page
We had logic to suffix the page title with text depending on the layout (e.g. `- CiviForm` for applicants and `- CiviForm Admin Console` for program/CiviForm admins).

Our login page wasn't make use of either of those specific layouts. This pushes the "suffix the page title" logic down to the `BaseHtmlLayout` class with a default value of "CiviForm".

Note: While here, I also filed #3548 to track the fact that the "Login" text is not localized.

#### Select language
This had an incorrect set of text. Since it wasn't localized, I also removed it from the translations files and inlined it directly with a comment. Finally, I moved the `<h1>` SR-only tag above the content that it was describing for clarity.

## Release notes:

Updating the titles for the login page and language selection page to be more accessible.

### Checklist

- [X] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [X] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)

Fixes #3545

### CODE REVIEW

File: server/app/views/applicant/ApplicantInformationView.java [hunk 1]
```diff
@@ -73,15 +73,15 @@ public Content render(
         submitButton(submitText).withClasses(ApplicantStyles.BUTTON_SELECT_LANGUAGE);
     formContent.with(formSubmit);
 
+    // No translation needed since this appears before applicants select their preferred language,
+    // so we always use the default.
+    String title = "Select lanaguage";
```
Comment (jeanniefu) [inline server/app/views/applicant/ApplicantInformationView.java:78]: nit: typo in language

**Review by jeanniefu — APPROVED** [review]
Thanks for picking this up and fixing!!

File: server/app/views/applicant/ApplicantInformationView.java (hunk 1 above)
Comment (clouser2) [reply server/app/views/applicant/ApplicantInformationView.java]: Good find!
