### PR TITLE
Correct path for applicant_date_of_birth and fix existing data

### LINKED ISSUE #5901: InvalidPathException Around Eligibility
### Details

I'm getting an exception on our staging site and reproducible on my local machine. A backup of the staging database is in the [#seattle channel on Slack](https://civiform.slack.com/archives/C035N9KCR0U/p1698800084943609). 

It appears to be throwing on [this line of the ReadOnlyApplicantProgramServiceImpl](
https://github.com/civiform/civiform/blob/71b887997c7cf0269c2453388b1dc7d0e7d38b90/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L342) around Eligibility.

### Does not occur in these cases

- If you attempt to apply as a regular applicant
- If you clear the database (/dev/seed) and use the generated programs it makes

### Deployed Versions

- Staging uses the latest snapshot image
- Prod and Test are on v1.141.0 and don't appear to have the issue occur

### Repro Steps

- Run the app
- Go to dev tools -> trusted intermediary
- Scroll down to the client list and click on Applicant Dashboard for `Dino, Big`
- Click apply to the `Release testing` program
- You'll see an exception

### Exception
```
! @83d5n94aj - Internal server error, for (GET) [/applicants/2458/programs/214/review] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 1696204800000]]
        at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$2(HttpErrorHandler.scala:381)
        at scala.Option.map(Option.scala:242)
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:380)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:373)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:244)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:180)
        at controllers.ErrorHandler.onServerError(ErrorHandler.java:106)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
Caused by: java.lang.RuntimeException: com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 1696204800000
        at controllers.applicant.ApplicantProgramReviewController.lambda$review$6(ApplicantProgramReviewController.java:168)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
        ... 7 common frames omitted
Caused by: com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 1696204800000
        at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:67)
        at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:90)
        at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:80)
        at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:90)
        at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:80)
        at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:66)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:107)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:88)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:77)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:103)
        at services.CfJsonDocumentContext.evalPredicate(CfJsonDocumentContext.java:591)
        at services.applicant.predicate.PredicateEvaluator.evaluateLeafNode(PredicateEvaluator.java:55)
        at services.applicant.predicate.PredicateEvaluator.evaluate(PredicateEvaluator.java:35)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.evaluatePredicate(ReadOnlyApplicantProgramServiceImpl.java:444)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.isBlockEligible(ReadOnlyApplicantProgramServiceImpl.java:150)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.isQuestionEligibleInBlock(ReadOnlyApplicantProgramServiceImpl.java:339)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.lambda$isApplicationNotEligible$2(ReadOnlyApplicantProgramServiceImpl.java:130)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
```

### PR DESCRIPTION
**Pull request by rockycodes**
### Description

This PR updates the "Well known path" for `applicant_date_of_birth` to include the nested `date` field.

This PR also adds a Durable Job that will update `applicant_date_of_birth` in all existing Applicant Data objects to include the nested `date` field. Although this Durable Job only really needs to run once, I utilized the existing infrastructure to set it up as recurring. Once this is merged, I'll plan to wait a month to allow plenty of time for the job to run and then I'll remove the job, the deprecated data path, and the conditional logic to handle both data paths.

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [x] Created unit and/or browser tests which fail without the change (if possible)

### Instructions for manual testing

1. Check out the main branch, log in as a TI, and add a client
2. Check out this branch, log in as a TI, and add a client
3. Check that DOBs for both clients are showing up in the TI client list view
4. Log in as a program admin and create a program that includes the seeded "Applicant Date of Birth" question
5. (Optional) Apply as a TI on behalf of the first client you added. The answer to the "date of birth" question should be blank and attempting to edit it should result in an error.
6. Stop the server and edit the code so the new job will run on server start:
Add this to `RecurringJobExecutionTimeResolvers.java`
```
public static final class Immediately implements RecurringJobExecutionTimeResolver {
    @Override
    public Instant resolveExecutionTime(Clock clock) {
      return LocalDateTime.now(clock)
          .toInstant(ZoneId.systemDefault().getRules().getOffset(Instant.now()));
    }
  }
```
In `DurableJobModule.java`, edit the registration of the `FIX_APPLICANT_DOB_DATA_PATH` job to:
```
    durableJobRegistry.register(
        DurableJobName.FIX_APPLICANT_DOB_DATA_PATH,
        persistedDurableJob -> new FixApplicantDobDataPathJob(persistedDurableJob),
        new RecurringJobExecutionTimeResolvers.Immediately());
``` 
7. Restart the server and wait a minute for the job to run
8. Apply as a TI on behalf of the first client you added. The answer to the "date of birth" question should be filled in and you should be able to edit it.

### Issue(s) this completes

Fixes #5901

### CODE REVIEW

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+  }
+
+  @Override
+  public PersistedDurableJob getPersistedDurableJob() {
+    return persistedDurableJob;
+  }
+
+  @Override
+  public void run() {
+    List<Applicant> applicants = database.find(Applicant.class).findList();
```
Comment (rockycodes) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: I feel like there must be a way to make this more performant, but I had a hard time figuring it out. I attempted to query only for applicants that have the `applicant_date_of_birth` path in the json object, but I ran into the same problem as Swathi because our "json" is stored as a string and I couldn't figure out how to write it in raw sql.

File: server/app/modules/DurableJobModule.java [hunk 2]
```diff
@@ -89,6 +90,11 @@ public DurableJobRegistry provideDurableJobRegistry(
             new UnusedAccountCleanupJob(accountRepository, nowProvider, persistedDurableJob),
         new RecurringJobExecutionTimeResolvers.SecondOfMonth2Am());
 
+    durableJobRegistry.register(
+        DurableJobName.FIX_APPLICANT_DOB_DATA_PATH,
+        persistedDurableJob -> new FixApplicantDobDataPathJob(persistedDurableJob),
+        new RecurringJobExecutionTimeResolvers.Sunday2Am());
```
Comment (rockycodes) [inline server/app/modules/DurableJobModule.java:96]: What do you think about my plan to make this a recurring weekly job and clean it up in a month to ensure it had the chance to run for everyone?

File: server/app/services/applicant/ApplicantData.java [hunk 3]
```diff
@@ -147,7 +147,11 @@ public boolean updateDidFailAt(Path path) {
   }
 
   public Optional<LocalDate> getDateOfBirth() {
-    return readDate(WellKnownPaths.APPLICANT_DOB);
+    Path dobPath = WellKnownPaths.APPLICANT_DOB;
```
Comment (rockycodes) [inline server/app/services/applicant/ApplicantData.java:150]: This is used to show the DOB on the TI client list page. Since we'll have a mix of both data structures for awhile, we need to handle both cases. I'll remove this when I remove the job.

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 1 above)
Comment (bion) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: See comment here on how to cast the string to jsonb inside the postgres query: https://github.com/civiform/civiform/blob/main/server/app/repository/ProgramRepository.java#L361-L366

Comment (bion) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: suggestion (blocking): Loading all of the applicants into memory may be enough to cause an outage. Use a streaming query for O(1) memory consumption: https://ebean.io/docs/query/streaming

**Review by bion — CHANGES_REQUESTED** [review]

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 1 above)
Comment (swatkat1) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: postgres=# select  ((object #>> '{}')::jsonb)::json#>'{applicant,applicant_date_of_birth}' from applications;
                                   ?column?                                    
-------------------------------------------------------------------------------
 
 
 
 {"date": 1693094400000, "updated_at": 1699467429935, "program_updated_in": 4}
 {"date": 1690675200000, "updated_at": 1699467457146, "program_updated_in": 4}
(5 rows)

Comment (swatkat1) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: Try something like below Rocky - select  ((object #>> '{}')::jsonb)::json#>'{applicant,applicant_date_of_birth,date}' from applications;

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+    applicants.forEach(
+        (applicant) -> {
+          ApplicantData applicantData = applicant.getApplicantData();
+          if (applicantData.getDateOfBirth().isPresent()
+              && !applicantData.hasPath(WellKnownPaths.APPLICANT_DOB)) {
```
Comment (bion) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:40]: question (blocking): should this also check to see if anything is present at `WellKnownPaths.APPLICANT_DOB_DEPRECATED`?

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 1 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: Thank you both so much! I re-wrote this using your suggestions and am feeling much better about it.

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 4 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: That is what `applicantData.getDateOfBirth().isPresent()` is doing.

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+
+  @Override
+  public PersistedDurableJob getPersistedDurableJob() {
+    return persistedDurableJob;
+  }
+
+  @Override
+  public void run() {
+    String sql =
+        "select * from applicants where ((object #>>"
```
Comment (swatkat1) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: Hi Rocky- Here is the formatted query - "SELECT *
FROM applicants
WHERE ((object #>> '{}')::jsonb)::json @> '{applicant, applicant_date_of_birth}' IS NOT NULL"

Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:35]: Ah ok. This version works, but is that just for readability?

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+import java.time.LocalDate;
+import models.Applicant;
+import models.PersistedDurableJob;
+import services.WellKnownPaths;
+import services.applicant.ApplicantData;
+
+/**
+ * Finds applicant data objects with applicant_date_of_birth set to a number and changes it to a
+ * nest object.
+ */
```
Comment (bion) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:16]: suggestion (blocking): please add the "why" in addition to the "what"

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+  @Override
+  public PersistedDurableJob getPersistedDurableJob() {
+    return persistedDurableJob;
+  }
+
+  @Override
+  public void run() {
+    String sql =
+        "select * from applicants where ((object #>>"
+            + " '{}')::jsonb)::json#>'{applicant,applicant_date_of_birth}' is not null";
```
Comment (bion) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:36]: suggestion (non-blocking, if-minor): Could you add additional criteria to the `where` clause to reduce the number of applicants in the result set?

File: server/app/modules/DurableJobModule.java (hunk 2 above)
Comment (bion) [reply server/app/modules/DurableJobModule.java:96]: SGTM

suggestion (non-blocking): run it nightly instead of once a week to reduce time to incident resolution.

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+                  && !applicantData.hasPath(WellKnownPaths.APPLICANT_DOB)) {
+                LocalDate dob = applicantData.getDateOfBirth().get();
+                // Clear the old path off the json data before inserting the new one
+                applicantData
+                    .getDocumentContext()
+                    .delete(WellKnownPaths.APPLICANT_DOB_DEPRECATED.toString());
+                applicantData.setDateOfBirth(dob.toString());
+                applicant.save();
+              }
+            });
```
Comment (bion) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:54]: suggestion (blocking): add a test for this job that ensures only the expected applications get updated

**Review by bion — CHANGES_REQUESTED** [review]

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 7 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:36]: What additional criteria do you recommend?

Comment (swatkat1) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:36]: should we filter out be certain dates? Say only applicantdata createTime<12/31/2023

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+              // Check that the applicant has a value for dob and that the path
+              // is the deprecated path
+              if (applicantData.getDateOfBirth().isPresent()
+                  && !applicantData.hasPath(WellKnownPaths.APPLICANT_DOB)) {
+                LocalDate dob = applicantData.getDateOfBirth().get();
+                // Clear the old path off the json data before inserting the new one
+                applicantData
+                    .getDocumentContext()
+                    .delete(WellKnownPaths.APPLICANT_DOB_DEPRECATED.toString());
+                applicantData.setDateOfBirth(dob.toString());
```
[the remark this answers is not in the document]
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:53]: done

File: server/app/modules/DurableJobModule.java (hunk 2 above)
Comment (rockycodes) [reply server/app/modules/DurableJobModule.java]: done

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 5 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: done

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 6 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: done

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 8 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: done

**Review by swatkat1 — APPROVED** [review]
I am pretty good with this PR. May be adding filter by date can improve the query but I don't see it as blocking. I am good for approving this.

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+  @Override
+  public PersistedDurableJob getPersistedDurableJob() {
+    return persistedDurableJob;
+  }
+
+  @Override
+  public void run() {
+    String sql =
+        "SELECT * FROM applicants WHERE ((object"
+            + " #>>'{}')::jsonb)::json#>'{applicant,applicant_date_of_birth}' IS NOT NULL";
```
Comment (bion) [inline server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java:38]: suggestion (if-minor): instead of `IS NOT NULL` filter on type of the value at `'{applicant,applicant_date_of_birth}'` being a number

File: server/test/durablejobs/jobs/FixApplicantDobDataPathJobTest.java [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+    FixApplicantDobDataPathJob fixApplicantDobDataPathJob = new FixApplicantDobDataPathJob(job);
+
+    fixApplicantDobDataPathJob.run();
+
+    Database database = DB.getDefault();
+    List<Applicant> applicants = database.find(Applicant.class).findList();
+
+    // The applicant with the correct dob path should not have been updated
+    assertThat(applicants.get(0).getApplicantData().asJsonString())
+        .isEqualTo(applicantWithCorrectPath.getApplicantData().asJsonString());
```
Comment (bion) [inline server/test/durablejobs/jobs/FixApplicantDobDataPathJobTest.java:44]: suggestion (non-blocking): instead of querying for the list and referencing by implicit order, call `refresh()` on the models so it's clear which one you're referencing.

**Review by bion — CHANGES_REQUESTED** [review]

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 7 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: done! filtered by `applicant, applicant_date_of_birth is not null` AND `applicant, applicant_date_of_birth, date is null`

File: server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java (hunk 10 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java]: done! filtered by {applicant, applicant_date_of_birth} is not null AND {applicant, applicant_date_of_birth, date} is null

File: server/test/durablejobs/jobs/FixApplicantDobDataPathJobTest.java (hunk 11 above)
Comment (rockycodes) [reply server/test/durablejobs/jobs/FixApplicantDobDataPathJobTest.java]: done!

File: server/app/repository/AccountRepository.java [hunk 12]
```diff
@@ -331,4 +333,19 @@ public int deleteUnusedGuestAccounts(int minAgeInDays) {
 
     return database.sqlUpdate(sql).execute();
   }
+
+  /**
+   * For use in {@link FixApplicantDobDataPathJob}. This will return applicants who have the
+   * incorrect path for applicant_date_of_birth where applicant_date_of_birth points directly to a
+   * number. eg. {applicant:{applicant_date_of_birth: 1038787200000}}
+   */
```
Comment (swatkat1) [inline server/app/repository/AccountRepository.java:414]: a level of nesting is missing in the comment { "applicant_date_of_birth" : {"date" : 100xxx}

File: server/app/durablejobs/RecurringJobExecutionTimeResolvers.java [hunk 13]
```diff
@@ -55,4 +55,16 @@ public Instant resolveExecutionTime(Clock clock) {
           .toInstant();
     }
   }
+
+  /** Nightly at 2am local time */
+  public static final class Nightly2Am implements RecurringJobExecutionTimeResolver {
```
Comment (bion) [inline server/app/durablejobs/RecurringJobExecutionTimeResolvers.java:60]: suggestion (blocking): please add a test case to https://github.com/civiform/civiform/blob/main/server/test/durablejobs/RecurringJobExecutionTimeResolversTest.java#L10

**Review by bion — CHANGES_REQUESTED** [review]

File: server/app/repository/AccountRepository.java (hunk 12 above)
Comment (rockycodes) [reply server/app/repository/AccountRepository.java:414]: This is demonstrating the incorrect data case. Where the nested "date" is missing.

File: server/app/durablejobs/RecurringJobExecutionTimeResolvers.java (hunk 13 above)
Comment (rockycodes) [reply server/app/durablejobs/RecurringJobExecutionTimeResolvers.java:60]: good call, this uncovered that it was setting it to run at 2am that same day (so always in the past). i bumped it forward a day so it's starting at 2am that night.

Comment (bion) [reply server/app/durablejobs/RecurringJobExecutionTimeResolvers.java:60]: Oh good 😅

**Review by bion — APPROVED** [review]
