### PR TITLE
Fix issue where users could not add newlines to questions.

### LINKED ISSUE #5173: Unable to create a new line when creating/editing a static text question as a CF admin.
**Describe the bug**
Unable to create a new line when creating/editing a static text question as a CF admin.  This means that it isn't possible to create a bullet point list, an accordion or to format the text into multiple lines.

**To Reproduce**

1. Sign in as a CF admin.
2. Go to [Questions List](https://staging-aws.civiform.dev/admin/questions)
3. Click on "Create new question"
4. Select "Static text" from the dropdown.
5. In the "Question text displayed to the applicant" section, try pressing "return" to go to a new line.
6. Notice that nothing happens and it isn't possible to create a new line.

**Expected behavior**
An admin user is able to create a multiple-line question.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: iOS
- Browser:  Chrome and Firefox

### PR DESCRIPTION
**Pull request by reemaka**
### Description

Fix issue where users were unable to create a new line when creating/editing a static text question as a CF admin.

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

#### General

Read the full guidelines for PRs [here](https://docs.civiform.us/contributor-guide/developer-guide/technical-contribution-guide#guidelines-for-pull-requests)

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release | database >
### Issue(s) this completes

Fixes #5173

### CODE REVIEW

File: server/app/assets/javascripts/main.ts [hunk 1]
```diff
@@ -282,7 +282,13 @@ function disableEnterToSubmitBehaviorOnForms() {
     const target = (e.target as HTMLElement).tagName.toLowerCase()
     // if event originated from a button or link - it should proceed with
     // default action.
-    if (target !== 'button' && target !== 'a' && e.key === 'Enter') {
+    // For textareas, the default should also proceed to allow newlines.
```
Comment (dkatzz) [inline server/app/assets/javascripts/main.ts:285]: **suggestion:** Maybe combine with existing comment above?

**Review by dkatzz — APPROVED** [review]
