### PR TITLE
Refresh enumerator entity add button status on page load

### LINKED ISSUE #7733: Enumerator response add button disable logic is not applied on page load
**Describe the bug**
When filling out an enumerator question in an application, the add button is re-enabled erroneously when you click "Save and next" with an empty entity.

**To Reproduce**

1. Set up a program with an enumerator question 
2. Preview the program as applicant
3. Add an enumerator entity and leave it empty
5. Observe that the Add button is disabled
6. Click "Save and next"
7. Observe that an error shows asking you to enter a value for each line
8. Observe that the Add button is re-enabled

**Expected behavior**
The add button should remain disabled as long as there is an empty entity.

**Screenshots**
Expected: 
image

Actual:
image

### PR DESCRIPTION
**Pull request by jeffpw-goog**
### Description

Refresh enumerator entity add button status on page load

Also refactor refreshAddButtonStatus so that it works when run on a page without an enumerator, and combines the two selector calls into one.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Issue(s) this completes

Fixes #7733

### CODE REVIEW

File: server/app/assets/javascripts/enumerator.ts [hunk 1]
```diff
@@ -169,21 +171,18 @@ function setFocusAfterEnumeratorRemoval() {
...
-  const enumeratorQuestion = assertNotNull(
-    document.querySelector('.cf-question-enumerator'),
+  const enumeratorInputValues = Array.from(
+    document.querySelectorAll(
+      '.cf-question-enumerator input[data-entity-input]',
+    ),
+  ).map((item) => (item as HTMLInputElement).value)
+
+  // validate that there are no empty inputs.
+  const addButton = <HTMLInputElement>(
```
Comment (melanie-exygy) [inline server/app/assets/javascripts/enumerator.ts:181]: suggestion (non-blocking):  Is there a need to cast this button as an input element?  Also, It would be best to stay consistent in the way you cast.  So, either using `as` or `<>`, but not mixing both.

File: server/app/assets/javascripts/enumerator.ts [hunk 2]
```diff
@@ -4,6 +4,8 @@
 import {addEventListenerToElements, assertNotNull} from './util'
 
 export function init() {
+  refreshAddButtonStatus()
```
Comment (melanie-exygy) [inline server/app/assets/javascripts/enumerator.ts:7]: praise:  Clever solution to just check for empty inputs on page load.

File: browser-test/src/end_to_end_enumerators.test.ts [hunk 3]
```diff
@@ -354,6 +354,18 @@ test.describe('End to end enumerator test', () => {
           page.locator('#enumerator-field-add-button'),
         ).toHaveAttribute('disabled')
       })
+
+      await test.step('Add button is still disabled after trying to save', async () => {
+        await applicantQuestions.clickNext()
+        // Verify that the error message is visible.
+        await expect(
+          page.locator('.cf-applicant-question-errors:visible'),
+        ).toContainText('Error: Please enter a value for each line.')
```
Comment (melanie-exygy) [inline browser-test/src/end_to_end_enumerators.test.ts:363]: suggestion (non-blocking):  As much as possible, it's best to avoid relying on text either for locators or assertions because if that text changes, we'll have to update the test.  You could use `.toBeVisible()` instead.

File: browser-test/src/end_to_end_enumerators.test.ts [hunk 4]
```diff
@@ -354,6 +354,18 @@ test.describe('End to end enumerator test', () => {
...
+
+        await expect(
+          page.locator('#enumerator-field-add-button'),
+        ).toHaveAttribute('disabled')
```
Comment (melanie-exygy) [inline browser-test/src/end_to_end_enumerators.test.ts:367]: suggestion(non-blocking):  We started trying to use Playwright [auto-retrying assertions](https://playwright.dev/docs/test-assertions), so rather than `.toHaveAttribute('disabled')`, you could use `toBeDisabled()`

File: browser-test/src/end_to_end_enumerators.test.ts (hunk 3 above)
Comment (jeffpw-goog) [reply browser-test/src/end_to_end_enumerators.test.ts]: Interesting point - the unit tests already validate the error message text and that the errors occur at the right times, so the browser tests are somewhat duplicative in that sense (I copied this from a test around line 200). So I guess the question is how much should the browser tests test - a screenshot with a single error case (or two at once, maybe) could validate that (and how) error messages are presented in general.

But actually in this case I added this more so that the test reads clearly and to confirm that the page is in the expected state when validating that the add button is disabled (i.e. we're not actually on the next page where it is disabled for other reasons). I guess toBeVisible with a comment is sufficient to cover that. Updated to do that.

Thanks!

**Review by melanie-exygy — APPROVED** [review]
