### PR TITLE
Explicitly set height for <select> tags

### LINKED ISSUE #3792: The State dropdown in the UI is slightly misaligned
**Describe the bug**
The State dropdown in the UI is slightly misaligned

**To Reproduce**
While the applicant fills an address question, it is observed to be slightly misaligned. This is dues to the inherent feature of "SelectWithLabel". Since the solution is non-trival, a little indepth look at the UI components is needed.

**Expected behavior**
The dropdown should be aligned to the City and Zip textboxes.

**Screenshots**
image

**Additional context**
This is part of fixing the issue https://github.com/civiform/civiform/issues/1485

### PR DESCRIPTION
**Pull request by greg-hyde**
### Description

select elements were rendering shorter than input elements, despite using the same CSS classes. line-height was changing the height of the input element but not the select element. This PR explicitly sets the height on those elements, which has no effect on input elements but increases the height of select elements (eg the state dropdown) to match.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [x] Created unit and/or browser tests which fail without the change (if possible)

### Issue(s) this completes

Fixes #3792

### CODE REVIEW

File: server/app/views/style/BaseStyles.java [hunk 1]
```diff
@@ -95,6 +95,13 @@ public final class BaseStyles {
   /** For use on an `input` of type "radio". */
   public static final String RADIO = CHECKBOX;
 
+  /** For use on a `select` element. */
+  public static final String SELECT = StyleUtils.joinStyles(BaseStyles.INPUT, "h-11.5");
+
+  /** For use on a `select` element. */
+  public static final String SELECT_WITH_ERROR =
```
Comment (azhangggggg) [inline server/app/views/style/BaseStyles.java:102]: Could you update the javadoc for `SELECT_WITH_ERROR` to differentiate itself from `SELECT`?

Comment (greg-hyde) [reply server/app/views/style/BaseStyles.java:102]: done

**Review by azhangggggg — APPROVED** [review]
