### PR TITLE
Fix eligibility condition operator help text display bugs

### LINKED ISSUE #7440: Help text is repeated for each value input box in predicate editor
**Describe the bug**
The operator help text on the eligibility and visibility condition editor is repeated for each value when there is more than one.

**To Reproduce**

1. Create a program with a date and a name question on the same screen
2. Click "Edit eligibility condition" for that screen
3. Select at least the date and name questions and click "Add condition"
4. Select "first name" and "is one of" for the name question, and "date" and "age is between" for the date question.
5. Click "Add values"

**Expected behavior**
The help text for the operator only needs to be shown once, and takes up unnecessary screen space when repeated.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by jeffpw-goog**
### Description

* Update the browser test to include 5 questions to manifest spacing issues
* Update the browser test to include a dropdown question, because it supports the "is one of" operator but doesn't want the help text
* Fix the spacing issues.
* Fix the list-value help text to not show for multi-select scalars
* Update the screenshot scope to include the scalar/operator section so that it's easier to see what it should look like

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [X] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Issue(s) this completes

Fixes #7440

### CODE REVIEW

File: server/app/views/admin/programs/ProgramPredicateConfigureView.java [hunk 1]
```diff
@@ -443,7 +443,7 @@ private DivTag renderQuestionHeaders(
                         .withData("question-id", String.valueOf(qd.getId())),
                     createScalarDropdown(qd, Optional.of(leafNode)),
                     createOperatorDropdown(qd, Optional.of(leafNode)))
-                .withClasses(COLUMN_WIDTH, iff(columnNumber++ != 1, "ml-16")));
+                .withClasses(COLUMN_WIDTH, "shrink-0", iff(columnNumber++ != 1, "ml-16")));
       }
     } else {
       int columnNumber = 1;
```
Comment (melanie-exygy) [inline server/app/views/admin/programs/ProgramPredicateConfigureView.java:449]: suggestion (non-blocking):  It might be helpful to set `columnNumber` to `0` here like you did on line 289, just for consistency.

**Review by melanie-exygy — APPROVED** [review]

**Review by melanie-exygy — APPROVED** [review]

**Review by ssandbekkhaug — APPROVED** [review]
