### PR TITLE
Fix name formatting for PDF export.

### LINKED ISSUE #5066: Export to PDF Includes text "Optional" in Name and File Name
**Describe the bug**
When exporting a PDF it is including the text Optional in the name displayed within the file and the file name. It looks like a toString is being called on an optional java object.

**To Reproduce**

In the admin section view the applications of a program
Click on one to view the details
Click the "Export to PDF" button

**Expected behavior**

The name in the pdf and the file name should not include "Optional".

**Screenshots**

### Guest Account
image

### Non-guest Account
image

### PR DESCRIPTION
**Pull request by yotommy**
### Description

Previously the applicant name in an exported PDF looked like `"Optional[applicant name]"` or `"Optional.empty"`. This change fixes the formatting and handles the missing `Optional` case explicitly. The formatted name is contained in the PDF contents as well as forming part of the file name.

A PDF generated with this fix is attached.

## Release notes

Fixes the applicant name in the generated PDF contents and file name.

#### General

Read the full guidelines for PRs [here](https://docs.civiform.us/contributor-guide/developer-guide/technical-contribution-guide#guidelines-for-pull-requests)

- [x] Added the correct label: bug
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary
  - n/a

#### User visible changes

- [ ] Followed steps to [internationalize new strings](https://docs.civiform.us/contributor-guide/developer-guide/internationalization-i18n#internationalization-for-application-strings)
  - n/a
- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
  - n/a
- [ ] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
  - n/a
- [ ] Manually tested at 200% size
  - n/a
- [ ] Manually evaluated tab order
  - n/a

### Issue(s) this completes

Fixes #5066

[User, Test (1)-2023-07-10T11_20_41.181890.pdf](https://github.com/civiform/civiform/files/12005148/User.Test.1.-2023-07-10T11_20_41.181890.pdf)

### CODE REVIEW

File: server/test/services/export/AbstractExporterTest.java [hunk 1]
```diff
@@ -154,6 +154,7 @@ protected void createFakeApplications() throws Exception {
     Account admin = resourceCreator.insertAccount();
     Applicant applicantOne = resourceCreator.insertApplicantWithAccount();
     Applicant applicantTwo = resourceCreator.insertApplicantWithAccount();
+    applicantTwo.getApplicantData().setUserName("Civiform", null, "User");
```
Comment (bion) [inline server/test/services/export/AbstractExporterTest.java:157]: **suggestion (blocking):** 
```suggestion
    applicantTwo.getApplicantData().setUserName("CiviForm", /* middleName= */ null, "User");
```

**Review by bion — APPROVED** [review]
