### PR TITLE
Click to download files on summary page

### LINKED ISSUE #8985: Download files on the "Application Summary" page
# Problem

"As an applicant, I want to download files that I previously uploaded."

Today, on the North Star "Application Summary" page, clicking on a file name does NOT download the file.

## To reproduce

1. As admin, create a program that has a file upload question (or use an existing program)
2. As applicant, apply to that program
3. Upload a file
4. Click "Continue"
5. Go to the application summary page
6. Click the file name of the file you uploaded

## Expected behavior
User downloads the file

## Actual behavior
Nothing happens

# Notes
Mocks in https://github.com/civiform/civiform/issues/7935

# Done when

- [ ] The file name text is underlined
- [ ] User can click on file name to download the file

### PR DESCRIPTION
**Pull request by ssandbekkhaug**
### Description

Applicant can click file names to download files on the North Star summary page.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible) (Better browser tests are blocked by #8143)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).

#### User visible changes

- [x] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) any new strings
  - [x] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [x] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [x] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [x] Made equivalent changes in Thymeleaf for applicant-facing features and changes (or created an issue in the [Northstar epic](https://github.com/orgs/civiform/projects/1/views/94) to track that it's missing from Thymeleaf)
- [x] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [x] Manually tested at 200% size
- [x] Manually evaluated tab order
- [x] Manually tested with a screen reader if the feature is applicant-facing. See [screen reader testing](https://github.com/civiform/civiform/wiki/Testing#screen-reader-testing)

### Issue(s) this completes

Fixes #8985

### CODE REVIEW

**Comment by ssandbekkhaug** [comment]
* **#9105** <a href="https://app.graphite.dev/github/pr/civiform/civiform/9105?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ssandbekkhaug and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dkatzz — COMMENTED** [review]
Exciting update! Can you add tests to cover this new functionality in northstar?

**Comment by ssandbekkhaug** [comment]
> Exciting update! Can you add tests to cover this new functionality in northstar?

Unfortunately not yet. Uploading files in browser tests in blocked by #8143

File: server/app/views/applicant/NorthStarAnswerData.java [hunk 1]
```diff
@@ -62,6 +64,24 @@ private ImmutableList<String> fileNames() {
...
+    ArrayList<String> urls = new ArrayList<String>();
+
+    AnswerData data = this.answerData;
+    if (!data.encodedFileKeys().isEmpty()) {
+      for (int i = 0; i < data.encodedFileKeys().size(); i++) {
+        String encodedFileKey = data.encodedFileKeys().get(i);
+        String fileUrl = controllers.routes.FileController.show(applicantId, encodedFileKey).url();
+        urls.add(fileUrl);
+      }
+    } else if (data.encodedFileKey().isPresent()) {
```
Comment (dkatzz) [inline server/app/views/applicant/NorthStarAnswerData.java:77]: **question:** Will this single encoded file key be removed once multi-file upload is fully launched? If so, could we maybe add a TODO to remove it with https://github.com/civiform/civiform/issues/7493 included?

Comment (ssandbekkhaug) [reply server/app/views/applicant/NorthStarAnswerData.java:77]: Done

**Review by dkatzz — APPROVED** [review]

**Review by dkatzz — APPROVED** [review]

File: browser-test/src/support/applicant_questions.ts [hunk 2]
```diff
@@ -522,11 +522,13 @@ export class ApplicantQuestions {
...
-  async downloadSingleQuestionFromReviewPage() {
+  async downloadSingleQuestionFromReviewPage(northStarEnabled = false) {
     // Assert that we're on the review page.
-    expect(await this.page.innerText('h2')).toContain(
-      'Program application summary',
-    )
+    if (northStarEnabled) {
+      await expect(this.page.getByText('Review and submit')).toBeVisible()
+    } else {
+      expect(this.page.innerText('h2')).toContain('Program application summary')
```
Comment (gwendolyngoetz) [inline browser-test/src/support/applicant_questions.ts:530]:
```suggestion
    expect(await this.page.innerText('h2')).toContain('Program application summary')
```

Comment (gwendolyngoetz) [inline browser-test/src/support/applicant_questions.ts:530]:
```suggestion
      expect(await this.page.innerText('h2')).toContain('Program application summary')
```

**Review by gwendolyngoetz — CHANGES_REQUESTED** [review]

File: browser-test/src/support/applicant_questions.ts (hunk 2 above)
Comment (gwendolyngoetz) [reply browser-test/src/support/applicant_questions.ts]: Your commit has expect and await swapped

Comment (ssandbekkhaug) [reply browser-test/src/support/applicant_questions.ts]: I thought `await expect(...)` is preferred?

https://playwright.dev/docs/best-practices#use-web-first-assertions

Comment (gwendolyngoetz) [reply browser-test/src/support/applicant_questions.ts]: It is, but that entire line would need to be rewritten to use newer methods that support it. Given it will eventually go away when northstar goes live I wouldn't bother.

Comment (gwendolyngoetz) [reply browser-test/src/support/applicant_questions.ts]: Oh! you did bother. Nice job! :)

**Review by gwendolyngoetz — APPROVED** [review]
