### PR TITLE
fixing Create-new-question dropdown (as the scroll bar isn't working)

### LINKED ISSUE #3365: create-new-question is not scrollable
**Describe the bug**
create-new-question is not scrollable

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by swatkat1**
### Description

Dropdown for "create-new-question" doesn't have a scroll option. So Admins cannot choose other options.

## Release notes:

Dropdown for "create-new-question" doesn't have a scroll option. So Admins cannot choose other options.

### Checklist

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)

Fixes #3365 ; 

Screenshots
Before:
image

After:
image

### CODE REVIEW

File: server/app/views/components/CreateQuestionButton.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public static DivTag renderCreateQuestionButton(String questionCreateRedirectUrl
                 Styles.BG_WHITE,
                 Styles.TEXT_GRAY_600,
                 Styles.SHADOW_LG,
-                Styles.ABSOLUTE,
```
Comment (clouser2) [inline server/app/views/components/CreateQuestionButton.java:38]: I *believe* that the "absolute" class is required for positioning the dropdown appropriately next to the content.

I think the source of the problem is actually that we set 'overflow-hidden' in `QuestionBank.questionBankPanel`. Do you mind restoring the "absolute" tag here and removing the "overflow-hidden" tag in `QuestionBank.questionBankPanel`? If that works, there should be no need to set "overflow-auto".

**Review by clouser2 — CHANGES_REQUESTED** [review]

File: server/app/views/components/CreateQuestionButton.java (hunk 1 above)
Comment (swatkat1) [reply server/app/views/components/CreateQuestionButton.java:38]: that works too!

**Review by clouser2 — APPROVED** [review]
