### PR TITLE
Using deep link does not create duplicate applications

### LINKED ISSUE #2969: Error Submitting Due to more than one Draft Application
**Describe the bug**

User reported they were unable to submit an application and got a generic error show in a banner.

From the logs:
```
r.ApplicationRepository - java.util.concurrent.CompletionException: java.lang.RuntimeException: Found more than one DRAFT application for applicant 18874, program 830.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Found more than one DRAFT application for applicant 18874, program 830.
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Found more than one DRAFT application for applicant 18874, program 830.
at repository.ApplicationRepository.submitApplicationInternal(ApplicationRepository.java:98)
at repository.ApplicationRepository.lambda$submitApplication$1(ApplicationRepository.java:78)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
... 2 more
```

I fixed this issue by setting the lifecycle_stage on the older application to 'obsolete', but that won't fix the source that is causing the issue. Unfortunately I don't have anymore info at this time on what may have contributed towards an application getting in this state.

**To Reproduce**

Currently unknown

**Expected behavior**
Applications submit successfully. Duplication applications can't get created.

**Desktop (please complete the following information):**

- Browser: Chrome

**Additional context**

### PR DESCRIPTION
**Pull request by bion**
### Description

This fixes a bug wherein an applicant could have multiple drafts for the same program. This would happen when:

1. applicant answers a question for version A of a program, creating draft application A
1. CF admin publishes a new version of the program, version B
1. applicant navigates to the program using its deep link (e.g. from the index page), the deep link (previously) always links to the most recent version of the program, now version B
1. applicant answers a question for version B of the program, creating a second draft
1. applicant attempts to submit their application, encounter an error due to logic that asserts only one draft of a program at a time

The fix implemented here is to change the logic for deep links to redirect to the version of the program the applicant already has a draft application for, if one exists.

## Release notes:

Bugfix: duplicate draft applications when applicant uses deep links to updated program.

### Checklist

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)

fixes #2969

### CODE REVIEW

File: server/app/controllers/applicant/RedirectController.java [hunk 1]
```diff
@@ -69,37 +72,71 @@ public CompletionStage<Result> programByName(Http.Request request, String progra
...
+                            controllers.applicant.routes.ApplicantInformationController.edit(
+                                applicantId))
+                        .withSession(
+                            request.session().adding(REDIRECT_TO_SESSION_KEY, request.uri())));
               }
 
-              return redirect(
-                  controllers.applicant.routes.ApplicantProgramReviewController.preview(
-                      applicant.id, programFuture.join().id));
+              return getProgramVersionForApplicant(applicantId, programSlug)
```
Comment (azizova-leyla) [inline server/app/controllers/applicant/RedirectController.java:95]: it feels potentially error prone to do the check in RedirectController. if we ever have another entry point the check will need to be duplicated. Is it possible to abstract it more and use the same helper here and in the normal flow?

Comment (bion) [reply server/app/controllers/applicant/RedirectController.java:95]: > if we ever have another entry point

It's hard to think of a scenario where we would -- the deep link is intended to be the canonical front door to a program for the applicant.

> Is it possible to abstract it more and use the same helper here and in the normal flow?

The tricky part here is "in the normal flow". There's a number of different routes that include the explicit program version ID, so we'd need to guard each of them. Doable, but a much larger scope of effort I don't see how an applicant would even get to one of those routes without being redirected by this controller.

I'm happy to discuss this more. If we decide we want to put deeper guards against this happening in the future I suggest we do it as a follow up though so that this fix can go out sooner.

File: server/app/controllers/api/ProgramApplicationsApiController.java [hunk 2]
```diff
@@ -91,7 +91,7 @@ public CompletionStage<Result> list(
             .orElse(new IdentifierBasedPaginationSpec<>(pageSize, Long.MAX_VALUE));
 
     return programService
```
Comment (clouser2) [inline server/app/controllers/api/ProgramApplicationsApiController.java:93]: Not blocking: Semi-unrelated to this change, but part of a pet project of mine. Assuming it doesn't cause any compile errors, mind marking this class as final to make the choice for subclassing explicit rather than implicit?

File: server/app/controllers/applicant/RedirectController.java [hunk 3]
```diff
@@ -46,20 +49,20 @@ public RedirectController(
...
     this.profileUtils = checkNotNull(profileUtils);
-    this.programRepository = checkNotNull(programRepository);
+    this.programService = checkNotNull(programService);
     this.upsellView = checkNotNull(upsellView);
     this.messagesApi = checkNotNull(messagesApi);
     this.languageUtils = checkNotNull(languageUtils);
   }
 
-  public CompletionStage<Result> programByName(Http.Request request, String programName) {
+  public CompletionStage<Result> programByName(Http.Request request, String programSlug) {
```
Comment (clouser2) [inline server/app/controllers/applicant/RedirectController.java:65]: Blocking: Can this be renamed to `programBySlug()`? Otherwise, I'm confused about the variable name change.

File: server/app/controllers/applicant/RedirectController.java [hunk 4]
```diff
@@ -69,37 +72,71 @@ public CompletionStage<Result> programByName(Http.Request request, String progra
...
-
-              Applicant applicant = applicantFuture.join();
+    return profile
+        .get()
+        .getApplicant()
+        .thenComposeAsync(
+            (Applicant applicant) -> {
               // Attempt to set default language for the applicant.
               applicant = languageUtils.maybeSetDefaultLocale(applicant);
+              final long applicantId = applicant.id;
```
Comment (clouser2) [inline server/app/controllers/applicant/RedirectController.java:82]: Not blocking: Any particular reason to stash this off here rather than just accessing it on the Applicant object at the callsite?

File: server/app/controllers/applicant/RedirectController.java [hunk 5]
```diff
@@ -69,37 +72,71 @@ public CompletionStage<Result> programByName(Http.Request request, String progra
...
+  private CompletionStage<Optional<ProgramDefinition>> getProgramVersionForApplicant(
+      long applicantId, String programSlug) {
+    return applicantService
+        .relevantPrograms(applicantId)
+        .thenApplyAsync(
+            (ImmutableMap<LifecycleStage, ImmutableList<ProgramDefinition>> relevantPrograms) ->
+                relevantPrograms.values().stream()
+                    .flatMap(Collection::stream)
+                    .filter(program -> program.slug().equals(programSlug))
+                    .findAny(),
```
Comment (clouser2) [inline server/app/controllers/applicant/RedirectController.java:136]: In the case where the applicant DOES have existing draft applications in multiple program versions, it seems that this call might return a "random" program version. In reality, we should likely make the version returned here the same as the one from @azizova-leyla  bug fix (e.g. the most recent program version). I also may be misunderstanding things here :).

File: server/app/controllers/applicant/RedirectController.java [hunk 6]
```diff
@@ -69,37 +72,71 @@ public CompletionStage<Result> programByName(Http.Request request, String progra
...
+                        .withSession(
+                            request.session().adding(REDIRECT_TO_SESSION_KEY, request.uri())));
               }
 
-              return redirect(
-                  controllers.applicant.routes.ApplicantProgramReviewController.preview(
-                      applicant.id, programFuture.join().id));
+              return getProgramVersionForApplicant(applicantId, programSlug)
+                  .thenComposeAsync(
+                      (Optional<ProgramDefinition> programForExistingApplication) -> {
```
Comment (azizova-leyla) [inline server/app/controllers/applicant/RedirectController.java:97]: I don't see a filter for draft applications anywhere. How does this work? Wouldn't ` relevantPrograms() `return all active programs as well and the else clause will never get executed?

**Review by clouser2 — CHANGES_REQUESTED** [review]

File: server/app/controllers/applicant/RedirectController.java (hunk 4 above)
Comment (bion) [reply server/app/controllers/applicant/RedirectController.java:82]: variables defined in an outer scope and referenced in lambdas must be final, applicant can't be final because we reassign it on the line above

File: server/app/controllers/applicant/RedirectController.java (hunk 6 above)
Comment (bion) [reply server/app/controllers/applicant/RedirectController.java:97]: Super good point, thanks for the catch

File: server/app/controllers/applicant/RedirectController.java (hunk 3 above)
Comment (bion) [reply server/app/controllers/applicant/RedirectController.java]: done

**Review by clouser2 — APPROVED** [review]

File: server/app/controllers/api/ProgramApplicationsApiController.java (hunk 2 above)
Comment (bion) [reply server/app/controllers/api/ProgramApplicationsApiController.java:93]: done

File: server/app/controllers/applicant/RedirectController.java (hunk 5 above)
Comment (bion) [reply server/app/controllers/applicant/RedirectController.java]: fixed while pairing

File: server/app/controllers/applicant/RedirectController.java [hunk 7]
```diff
@@ -69,37 +72,74 @@ public CompletionStage<Result> programByName(Http.Request request, String progra
...
+                    controllers.applicant.routes.ApplicantProgramReviewController.preview(
+                        applicantId, activeProgramDefinition.id())),
+            httpContext.current());
+  }
+
+  private CompletionStage<Optional<ProgramDefinition>> getProgramVersionForApplicant(
+      long applicantId, String programSlug) {
+    // Find all applicant's DRAFT applications for programs of the same slug
+    // redirect to the newest program version with a DRAFT application.
+    // TODO(#2573): clean this up, don't compare on program ID
```
Comment (azizova-leyla) [inline server/app/controllers/applicant/RedirectController.java:131]: how's #2573 relevant here? you're not comparing on program ids.

**Review by azizova-leyla — APPROVED** [review]

File: server/app/controllers/applicant/RedirectController.java (hunk 7 above)
Comment (bion) [reply server/app/controllers/applicant/RedirectController.java:131]: We are on line 138.

Brett's PR for #2573 has query code that will make this less janky and allow us to compare on the actual applications
