### PR TITLE
Only validate new admin names

### LINKED ISSUE #6103: Option admin name validation is being applied to existing admin names
**Describe the bug**
Option admin name validation is being applied to existing admin names

Reported by @paripatel07 

**To Reproduce**

1. Edit a question with an option admin names that has spaces in it
2. Try to save the question
3. See that the validation is failing

**Expected behavior**
Validation should only apply to new admin names

**Screenshots**
image

### PR DESCRIPTION
**Pull request by avaleske**
### Description

Updates option admin name validation to only validate _new_ option admin names, so existing admin names don't have to be changed when updating a question.

Details:
- Updates `QuestionDefintion#validate()` to optionally take the previous question definition
- Only validates that new option admin names match the requirements in #5839, allowing existing admin names to be saved when the question is updated

## Release notes

Updates option admin name validation to only validate _new_ option admin names, so existing admin names don't have to be changed when updating a question.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary

#### User visible changes

- [n/a] Followed steps to [internationalize new strings](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#internationalization-for-application-strings)
- [n/a] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [n/a] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [n/a] Manually tested at 200% size
- [n/a] Manually evaluated tab order

#### New Features

- [n/a] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [n/a] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [n/a] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

- Manually create a question option with an invalid admin name (either via the DB or disabling the checking code)
- Try updating the question and ensure the validation doesn't catch the existing invalid admin name.

### Issue(s) this completes

Fixes #6103

### CODE REVIEW

**Comment by avaleske** [comment]
Current dependencies on/for this PR:
* main
  * **PR #6120** <a href="https://app.graphite.dev/github/pr/civiform/civiform/6120?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/civiform/civiform/6120?utm_source=stack-comment).

File: server/app/services/question/types/QuestionDefinition.java [hunk 1]
```diff
@@ -201,8 +202,31 @@ public final String getValidationPredicatesAsString() {
...
+  }
+
+  /**
+   * Validate that all required fields are present and valid for the question.
+   *
+   * @param previousDefinition the optional previous version of the {@link QuestionDefinition}
+   * @throws IllegalArgumentException if the previousDefinition is not of the same type as this
+   *     definition.
+   */
+  public final ImmutableSet<CiviFormError> validate(
```
Comment (bion) [inline server/app/services/question/types/QuestionDefinition.java:221]: **suggestion (blocking):** mention in the comment why the previous version is optionally provided -- what behavior changes

**Review by bion — CHANGES_REQUESTED** [review]

File: server/app/services/question/types/QuestionDefinition.java (hunk 1 above)
Comment (avaleske) [reply server/app/services/question/types/QuestionDefinition.java]: Done!

Comment (avaleske) [reply server/app/services/question/types/QuestionDefinition.java]: Also added to the javadoc in the QuestionService

**Review by bion — APPROVED** [review]
