### PR TITLE
Limiting Max allowed entities for enums questions

### LINKED ISSUE #10845: Civiform is allowing humoungly large objects to be stored in DB
**Describe the bug**
CiviForm today doesn't restrict any size limitation on enum questions repetitions. We allow the resident to repeat enums multiple time.
This has exposed a vulnerability. We should set a limit on the number of times Enums can be repeated. 

**To Reproduce**

1. Go to 'any enum question
2. Click on add new household member many times 

**Expected behavior**
There should be a limit to the number of times it gets repeated.

### PR DESCRIPTION
**Pull request by swatkat1**
### Description

Limiting Max allowed entities for enums questions

## Release notes

We are by default setting a limit on the number of enum entities allowable in a enum question. This fixes the bug- https://github.com/civiform/civiform/pull/10845

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if the primary reviewer is not an admin and this PR includes functionality changes)
- [ ] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Issue(s) this completes

Fixes #10845

### CODE REVIEW

File: server/test/services/applicant/question/EnumeratorQuestionTest.java [hunk 1]
```diff
@@ -163,6 +163,79 @@ public void withTooManyEntities_hasValidationError() {
...
 
+  @Test
+  public void withTooManyEntitiesAboveMaxAllowed_hasValidationError() {
+    ApplicantQuestion applicantQuestion =
+        new ApplicantQuestion(
+            enumeratorQuestionDefinition, applicant, applicantData, Optional.empty());
+    QuestionAnswerer.answerEnumeratorQuestion(
+        applicantData,
+        applicantQuestion.getContextualizedPath(),
+        ImmutableList.of(
```
Comment (shane-exygy) [inline server/test/services/applicant/question/EnumeratorQuestionTest.java]: **issue:** This will be a bit more readible and less bulky if we use a loop

List values = ArrayList().
for (int i =1 ; i <+51; ++i) {
  values.add(String.format("item %d", i));
  }

File: server/app/services/applicant/question/EnumeratorQuestion.java [hunk 2]
```diff
@@ -57,11 +58,17 @@ private ImmutableSet<ValidationErrorMessage> validateEntities() {
...
-    if (getMaxEntities().isPresent() && entityNames.size() > getMaxEntities().getAsInt()) {
+    if ((getMaxEntities().isPresent() && entityNames.size() > getMaxEntities().getAsInt())
+        || (getMaxEntities().isEmpty()
+            && entityNames.size() > EnumeratorQuestionForm.MAX_ENUM_ENTITIES_ALLOWED)) {
       errorsBuilder.add(
           ValidationErrorMessage.create(
-              MessageKey.ENUMERATOR_VALIDATION_TOO_MANY_ENTITIES, getMaxEntities().getAsInt()));
+              MessageKey.ENUMERATOR_VALIDATION_TOO_MANY_ENTITIES,
+              getMaxEntities().isPresent()
+                  ? getMinEntities().getAsInt()
```
Comment (shane-exygy) [inline server/app/services/applicant/question/EnumeratorQuestion.java]: **issue:** This should be Max not Min correct?

Comment (swatkat1) [reply server/app/services/applicant/question/EnumeratorQuestion.java]: thanks for catching it! Fixed!

File: server/test/services/applicant/question/EnumeratorQuestionTest.java (hunk 1 above)
Comment (swatkat1) [reply server/test/services/applicant/question/EnumeratorQuestionTest.java]: Done! PS- I asked Gemini to do generate it (wanted AI to do something :D)

File: server/app/services/applicant/question/EnumeratorQuestion.java [hunk 3]
```diff
@@ -57,11 +58,17 @@ private ImmutableSet<ValidationErrorMessage> validateEntities() {
           ValidationErrorMessage.create(
               MessageKey.ENUMERATOR_VALIDATION_TOO_FEW_ENTITIES, getMinEntities().getAsInt()));
     }
-    if (getMaxEntities().isPresent() && entityNames.size() > getMaxEntities().getAsInt()) {
+    if ((getMaxEntities().isPresent() && entityNames.size() > getMaxEntities().getAsInt())
```
Comment (shane-exygy) [inline server/app/services/applicant/question/EnumeratorQuestion.java]: **suggestion:** 

This can be a little cleaner by determining the max first rather than twice.

```
int maxAllowed = getMaxEntities().orElse(EnumeratorQuestionForm.MAX_ENUM_ENTITIES_ALLOWED);
                  
 if(entityNames.size() > maxAllowed) {
                  errorsBuilder.add(
          ValidationErrorMessage.create(
             MessageKey.ENUMERATOR_VALIDATION_TOO_MANY_ENTITIES,
   maxAllowed));
   }
  ```

File: server/test/services/applicant/question/EnumeratorQuestionTest.java [hunk 4]
```diff
@@ -163,6 +165,30 @@ public void withTooManyEntities_hasValidationError() {
                         MessageKey.ENUMERATOR_VALIDATION_TOO_MANY_ENTITIES, 3))));
   }
 
+  @Test
+  public void withTooManyEntitiesAboveMaxAllowed_hasValidationError() {
+    ApplicantQuestion applicantQuestion =
+        new ApplicantQuestion(
+            enumeratorQuestionDefinition, applicant, applicantData, Optional.empty());
+    List<String> testList = new ArrayList<>();
+    for (int i = 0; i < 50; i++) {
```
Comment (shane-exygy) [inline server/test/services/applicant/question/EnumeratorQuestionTest.java]: **issue:** You're missing an item.

Doing
`for (int i = 1; i <= EnumeratorQuestionForm.MAX_ENUM_ENTITIES_ALLOWED + 1; i++) `

 will make it clearer there's the correct number of items.

**Review by melanie-exygy — APPROVED** [review]

**Review by shane-exygy — APPROVED** [review]
