### PR TITLE
Fix for TI dashboard client cards needing to only show submitted applications

### LINKED ISSUE #6834: TI Dashboard: Incorrect # of Applications Submitted
**Describe the bug**
As a TI, I can see a summary of the submitted applications per client on the TI dashboard. The summary looks to include "In Progress" applications as a part of "Submitted Applications"

**To Reproduce**

1. Login as a TI
2. Complete an application on behalf of a client
3. Start an application on behalf of a client, but don't submit it
4. See that the TI Dashboard lists 2 completed applications

**Expected behavior**
I would expect it to show the number of completed applications and the number of in progress applications separately

**Screenshots**
**1 application submitted, 1 is in progress**
image

**Shows as 2 submitted applications**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by melanie-exygy**
### Description

On the TI dashboard client cards, "# submitted applications" was showing all started applications rather than just the submitted ones.  This fixes that.

image

### Instructions for manual testing

1. Log in as a TI.
2. Create a client if you don't already have one.
3. On the client card, click "View applications".
4. Submit an application.
5. Go back to the TI dashboard.
6. Note that the client card now says "1 application submitted" with the program name below.
7. Click "View applications" again.
8. Start an application and click "Save and Next" but don't click "Submit".
9. Go back to the TI dashboard.
10. Note that the client card still says "1 application submitted".

### Issue(s) this completes

Fixes #6834

### CODE REVIEW

**Comment by melanie-exygy** [comment]
@dkatzz here's a copy of the other PR, but without the false screenshot diffs.

File: server/app/views/applicant/TrustedIntermediaryDashboardView.java [hunk 1]
```diff
@@ -367,11 +368,13 @@ private DivTag renderCardApplications(AccountModel account) {
       return div();
     }
 
-    ImmutableList<ApplicationModel> newestApplicantApplications =
-        newestApplicant.get().getApplications();
-    int applicationCount = newestApplicantApplications.size();
+    ImmutableList<ApplicationModel> submittedApplications =
+        newestApplicant.get().getApplications().stream()
+            .filter(application -> application.getLifecycleStage() == LifecycleStage.ACTIVE)
```
Comment (dkatzz) [inline server/app/views/applicant/TrustedIntermediaryDashboardView.java:373]: **suggestion:** You can also use `.equals` instead - `application.getLifecycleStage().equals(LifecycleStage.ACTIVE)`

**Review by dkatzz — APPROVED** [review]

File: server/app/views/applicant/TrustedIntermediaryDashboardView.java (hunk 1 above)
Comment (melanie-exygy) [reply server/app/views/applicant/TrustedIntermediaryDashboardView.java:373]: I considered using `.equals`, but found this Stack Overflow discussion and was convinced to use `==` instead:  [discussion](https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals).

**Comment by elisekalstad** [comment]
Wow, you're fast, @melanie-exygy ! Thank you for making the fix!
