### PR TITLE
 Fix: Prevent submission of removed Yes/No options (#11594)

### LINKED ISSUE #11594: Applicant can submit invalid/removed Yes/No option after admin updates question configuration
**Describe the bug**
When an admin removes an option from a Yes/No question after an applicant has started their application, the applicant can still submit the removed option value, resulting in invalid data being stored.

**To Reproduce**

1. Admin: Create Yes/No question with all 4 options, publish program
2. Applicant: Start application, select "Not sure", go to review page
3. Admin: Edit question to remove "Not sure" option, republish
4. Applicant: Refresh page and submit application
5. Result: Application submitted with invalid "Not sure" value

**Expected behavior**

- If an option is removed, applicants with in-progress applications should either:

   - See a validation error if they had selected the removed option
   - Be forced to re-select from valid options
   - Have their selection cleared and be required to choose again

**Actual behavior**

- Applicant can submit the removed "Not sure" option
- No validation prevents submission of invalid option
- Invalid data is stored in the system

- See a validation error if they had selected the removed option
- Be forced to re-select from valid options
- Have their selection cleared and be required to choose again

**Additional context**
**Impact:**

- Data integrity compromised
- Reports may contain invalid values
- Potential application processing errors

Related to: Issue #10780 (validation logic)

### PR DESCRIPTION
**Pull request by osajulian-dev**
### Description

This PR fixes a data integrity issue where applicants could submit invalid/removed Yes/No options after an admin updates the question configuration.

- Added `getDisplayableOptions()` method to `MultiOptionQuestionDefinition` that filters options based on
`displayInAnswerOptions` field 
- Updated `SingleSelectQuestion` and `MultiSelectQuestion` validation to check against displayable options only
  - Maintains backward compatibility with legacy options (options without `displayInAnswerOptions` field are treated as displayable)
  - Server-side validation provides defense-in-depth protection while client-side filtering maintains good UX

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [X] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [X] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [X] Added an additional reviewer from `civiform/eng-admin` as FYI (if the primary reviewer is not an admin and this PR includes functionality changes)
- [X] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [X] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

#### Database evolutions

Read the guidelines [here](https://github.com/civiform/civiform/wiki/Database#writing-database-evolutions)

- [ ] Assigned two reviewers
- [ ] Guarded against already existing resources using `IF NOT EXISTS` and `IF EXISTS`
- [ ] Downs created to undo changes in Ups
- [ ] Every comment in script should begin with -- and not # --- unless it denotes Ups or Downs. See [here](https://www.playframework.com/documentation/2.9.x/Evolutions) for details.
- [ ] Tested both the Downs and the Ups scripts manually (When testing, include all comments from the evolution in your test script to ensure any syntax errors in the comments are caught.)
- [ ] Data migrations aren't being done (please use a [Durable Job](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates) if doing a data migration)
- [ ] Update the model documentation in our [wiki](https://github.com/civiform/civiform/wiki/Database) if necessary

#### Durable jobs

Read the docs [here](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates)

- [ ] Assigned two reviewers
- [ ] Included a rollback plan and a job to undo the data changes if appropriate

#### User visible changes

- [ ] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) any new strings
  - [ ] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [ ] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Made equivalent changes in Thymeleaf for applicant-facing features and changes (or created an issue in the [Northstar epic](https://github.com/orgs/civiform/projects/1/views/94) to track that it's missing from Thymeleaf)
- [ ] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order
- [ ] Performed manual accessibility tests for any applicant-facing changes or any new admin-facing features. See [manual-accessibility-testing](https://github.com/civiform/civiform/wiki/Accessibility#manual-accessibility-testing)
- [ ] Manually tested with a right-to-left language

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

1. **Setup**: Create a Yes/No question with options: Yes, No, Maybe,
  Not sure (all with `displayInAnswerOptions=true`)
  2. **Add to program**: Add the question to a test program
  3. **Start application**: As an applicant, start the application and select "Maybe"
  4. **Simulate admin removing option**: Using database access, update  the "Maybe" option to set `displayInAnswerOptions=false`
  5. **Verify fix**: Return to the applicant view and attempt to submit 
     - **Expected**: "Maybe" option disappears from UI, applicant can select a different valid option
     - **Data integrity**: Invalid option cannot be submitted to database (server-side validation prevents it)

### Issue(s) this completes

Fixes #11594

### CODE REVIEW

File: server/app/services/applicant/question/SingleSelectQuestion.java [hunk 1]
```diff
@@ -58,9 +58,12 @@ private ImmutableSet<ValidationErrorMessage> validateInput() {
 
     Long selectedValue = optionalSelectedValue.get();
 
-    // Validate the long is in the set of allowed Question options.
+    // Validate the long is in the set of allowed Question options that are displayable to
+    // applicants.
+    // This prevents submission of options that have been removed/hidden by admins.
     boolean validSelection =
-        getQuestionDefinition().getOptions().stream().anyMatch(o -> selectedValue.equals(o.id()));
+        getQuestionDefinition().getDisplayableOptions().stream()
```
Comment (dkatzz) [inline server/app/services/applicant/question/SingleSelectQuestion.java:65]: **question:** getDisplayableOptions is defined in the MultiSelectQuestion class - not sure it's right to use it here too?

File: server/app/services/question/types/MultiOptionQuestionDefinition.java [hunk 2]
```diff
@@ -215,6 +215,22 @@ public ImmutableList<QuestionOption> getOptions() {
...
 
+  /**
+   * Get only the options that should be displayed to applicants in answer forms.
+   *
+   * <p>This filters options based on the {@code displayInAnswerOptions} field. Options without this
+   * field set (legacy options) are included by default for backward compatibility.
+   *
+   * @return a list of options that should be shown to applicants for selection
+   */
+  public ImmutableList<QuestionOption> getDisplayableOptions() {
```
Comment (dkatzz) [inline server/app/services/question/types/MultiOptionQuestionDefinition.java:226]: **question:** This part is already checked in, right? https://github.com/civiform/civiform/blob/main/server/app/services/question/types/MultiOptionQuestionDefinition.java#L226

File: server/test/services/applicant/question/SingleSelectQuestionTest.java [hunk 3]
```diff
@@ -155,4 +155,106 @@ public void getOptions_defaultsIfLangUnsupported() {
...
+                LocalizedStrings.of(Locale.US, "option 1"),
+                Optional.of(true)), // Displayable
+            QuestionOption.create(
+                2L,
+                2L,
+                "opt2",
+                LocalizedStrings.of(Locale.US, "option 2"),
+                Optional.of(false))); // Hidden/removed by admin
+
+    MultiOptionQuestionDefinition questionWithHiddenOption =
```
Comment (dkatzz) [inline server/test/services/applicant/question/SingleSelectQuestionTest.java:177]: **question:** This is still looking at a MultiOption question, right? Should this be included in single select? Same questions below.

File: server/app/services/applicant/question/SingleSelectQuestion.java (hunk 1 above)
Comment (Osajulian) [reply server/app/services/applicant/question/SingleSelectQuestion.java:65]: Both SingleSelect (Yes/No, Dropdown, Radio) and MultiSelect (Checkbox) questions are backed by MultiOptionQuestionDefinition and both need to filter displayable options during validation to prevent submission of hidden/disabled options. The methods are wrapper methods that delegate to `MultiOptionQuestionDefinition.getDisplayableOptions()`. This follows the existing pattern where both classes have similar methods like getOptions(), etc.

File: server/app/services/question/types/MultiOptionQuestionDefinition.java (hunk 2 above)
Comment (Osajulian) [reply server/app/services/question/types/MultiOptionQuestionDefinition.java:226]: The `getDisplayableOptions()` method in `MultiOptionQuestionDefinition` was added in PR #11592 (which merged first).

 For context on the dependency chain:

- #11592 (merged): Added `getDisplayableOptions()` to fix admin UI showing all options
- #11594 (this PR): Uses that same method to fix validation accepting invalid options
- #11595 (in flight): extends it for PDF/JSON exports

So yes, the base method already exists in main - this PR just adds the wrapper methods in the question classes to use it for validation.

This is following the plan I informed you in our last meeting that I would undertake to avoid any delays in PR response or review requests from blocking upcoming fixes.

File: server/test/services/applicant/question/SingleSelectQuestionTest.java (hunk 3 above)
Comment (Osajulian) [reply server/test/services/applicant/question/SingleSelectQuestionTest.java:177]: Yes, the test is checking `MultiOptionQuestionDefinition` behavior, and IMO OK to include in `SingleSelectQuestionTest` as SingleSelect questions are multi-option questions backed by `MultiOptionQuestionDefinition`, they just enforce single selection validation

The test verifies that when an applicant submits a SingleSelect question, the validation properly filters to only displayable options. This is the core fix for the bug where disabled options could still be submitted. I looked to similar tests in `MultiSelectQuestionTest` which verify the same behavior for Checkbox questions.

File: server/app/services/applicant/question/SingleSelectQuestion.java (hunk 1 above)
Comment (dkatzz) [reply server/app/services/applicant/question/SingleSelectQuestion.java:65]: Ok got it! I misunderstood, thanks for the explanation!

File: server/app/services/question/types/MultiOptionQuestionDefinition.java (hunk 2 above)
Comment (dkatzz) [reply server/app/services/question/types/MultiOptionQuestionDefinition.java:226]: Yeah, I knew that you were working on multiple things at once - just wanted to see if there was anything new here and noting so you could pull in main.

File: server/test/services/applicant/question/SingleSelectQuestionTest.java (hunk 3 above)
Comment (dkatzz) [reply server/test/services/applicant/question/SingleSelectQuestionTest.java:177]: Got it, yeah so the difference here is the MultiOptionQuestionType is RADIO_BUTTON. That makes sense.
