### PR TITLE
Prevent clearing service area validation values

### LINKED ISSUE #12079: Address validation error
**Describe the bug**
As a resident applying to a program that requires I live within the City of Seattle:

Address eligibility check says my address is ineligible for the program IF I go BACK after entering address.

**To Reproduce**

1. Go to [Home Repair program](https://civiform.seattle.gov/programs/home-repair-loan) 
2. Start application
3. Enter Seattle address
4. Approve the corrected address
5. Continue
6. Go back to address page (this is key!)
7. Continue
8. See that you are no longer eligible for the program, although it previously said you were eligible

**Expected behavior**
An address that initially is validated as a Seattle address will continue to be valid for the entire application process, even if the applicant goes back in the application.

**Screenshots**

Image

Image

Image

Image

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rockycodes**
### Description

This PR fixes a bug in our logic that cleared service area validation values whenever an applicant re-submitted an address question, even if none of the answer values had changed. 

More details:
In our existing logic for determining service area validation, we assume an address should have no service area if the data coming in hasn't been "corrected".
https://github.com/civiform/civiform/blob/c3bdf8a7c5aac65bba60a9aa2a14177b7c52702a/server/app/services/applicant/ServiceAreaUpdateResolver.java#L80-L83
But, when a user submits an address question without changing any data, we intentionally do not go through the correction flow again, so the incoming data will not have that "corrected" field on it. My fix in this PR is to skip the service area validation check altogether if the data hasn't changed.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if this PR includes functionality changes and neither you nor the primary reviewer is an admin)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Instructions for manual testing

1. Create a program with an address question with correction enabled and gating eligibility on service area validation
2. Fill out the application with an eligible address and click "Continue". 
3. See the eligibility message.
5. Go back to the address question page and click "Continue" again without editing any fields.
6. See the eligibility message.

### Issue(s) this completes

Fixes #12079

### CODE REVIEW

File: server/app/services/applicant/question/AddressQuestion.java [hunk 1]
```diff
@@ -210,9 +210,11 @@ public Optional<ImmutableList<ServiceAreaInclusion>> getServiceAreaValue() {
       return serviceAreaValue;
     }
 
-    return applicantQuestion
-        .getApplicantData()
-        .readServiceAreaList(getServiceAreasPath().safeWithoutArrayReference());
+    serviceAreaValue =
```
Comment (rockycodes) [inline server/app/services/applicant/question/AddressQuestion.java:213]: Updating this method to match other methods where the value is set on the field before being returned. I thought this might have been the whole bug at first. It wasn't, but still seems like we should follow the pattern of preserving the value if we have it.

**Review by gwendolyngoetz — APPROVED** [review]
