### PR TITLE
[Maps] change voiceover behavior so it also works on iphone

### LINKED ISSUE #11927: [Accessibility] Pagination loses focus on iPhone
**Describe the bug**
On iPhone with VoiceOver enabled, after using pagination controls to navigate to the next or previous page of locations, focus jumps to the a different item in the newly loaded content instead of remaining on or returning to the pagination controls.

**WCAG Success Criterion**
[2.4.3 Focus Order (Level A)](https://www.w3.org/TR/WCAG21/#focus-order)
[3.2.2 On Input (Level A)](https://www.w3.org/TR/WCAG21/#on-input)

**To Reproduce**
1. Open the maps feature on an iPhone
2. Enable VoiceOver
4. Activate the "next page" or "previous page" control
5. Observe that focus moves to the a confusing location

**Expected behavior**
After pagination, focus should remain on or return to the pagination control group so users can easily navigate to additional pages without having to search for the pagination controls again.

**Screenshots**
https://github.com/user-attachments/assets/93aa9624-29ad-451c-ac88-e7fe98d25fbf

### PR DESCRIPTION
**Pull request by tallulahkay**
### Description

Change what gets focus after paginating. Instead of focusing on the whole pagination container, it now focuses on the label for the available locations list.

https://github.com/user-attachments/assets/8473d0fd-9175-4798-a917-83f66b3be243

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [ ] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if this PR includes functionality changes and neither you nor the primary reviewer is an admin)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

### Issue(s) this completes

Fixes #11927

### CODE REVIEW

File: server/app/assets/javascripts/mapquestion/map_question_pagination.ts [hunk 1]
```diff
@@ -102,16 +101,14 @@ const updateVisibleLocations = (
   const endIndex = startIndex + ITEMS_PER_PAGE
 
   // Hide all checkboxes first, but preserve the CF_FILTER_HIDDEN class for filtered items
-  allCheckboxes.forEach((checkbox) => {
```
Comment (tallulahkay) [inline server/app/assets/javascripts/mapquestion/map_question_pagination.ts:105]: This (and the next chunk) is only changed because the formatter was unhappy with it - it shouldn't cause any functionality change
