### PR TITLE
[Program Card Images] Move alt-text higher up in program images admin UI

### LINKED ISSUE #6662: Move alt-text message higher up
**Describe the bug**
Message that tells you to add the alt-text before image is lowest on the page, confusing for users who don't see it until after they try to upload an image. 

**To Reproduce**
Go to image upload page. 

**Expected behavior**
Move this message below the alt-text box. 

image

### PR DESCRIPTION
**Pull request by azhangggggg**
### Description

Move the note `Note: Image description is required before uploading an image.` to a position higher up so that it's right below the alt-text input field

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).

#### User visible changes

- [x] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [x] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [x] Manually tested at 200% size
- [x] Manually evaluated tab order

### Issue(s) this completes

Fixes #6662

### CODE REVIEW

File: server/app/views/admin/programs/ProgramImageView.java [hunk 1]
```diff
@@ -222,6 +222,7 @@ private DivTag createImageDescriptionForm(
                         .setPlaceholderText("Colorful fruits and vegetables in bins")
                         .setValue(form.value().get().getSummaryImageDescription())
                         .getInputTag()))
+        .with(p("Note: Image description is required before uploading an image.").withClass("mt-1"))
```
Comment (caitlinshk) [inline server/app/views/admin/programs/ProgramImageView.java:225]: nitpick: Can you also add `mb-1` to the class list? It looks a little close to the buttons under it.

**Review by caitlinshk — APPROVED** [review]

**Comment by caitlinshk** [comment]
Quick nitpick: Can you add the fact that this is for the program images admin UI somewhere in the PR title?

**Comment by azhangggggg** [comment]
> Quick nitpick: Can you add the fact that this is for the program images admin UI somewhere in the PR title?

for sure!
