### PR TITLE
Fully hydrate program defintions in CalculateEligibilityDeterminationJob

### LINKED ISSUE #11154: CalculateEligibilityDeterminationJob is failing in several environments
**Describe the bug**
Error message:

```
A durable job has failed repeatedly on civiformtest.seattle.gov
This needs to be investigated by IT staff or the CiviForm core team (civiform-technical@googlegroups.com).
Error report for: job_name="CALCULATE_ELIGIBILITY_DETERMINATION_JOB", job_ID=635
Eligibility Determination: stopping early after 10 errors
END_ERROR
JobRunner_JobFailed ExecutionException job_name="CALCULATE_ELIGIBILITY_DETERMINATION_JOB", job_ID=635, attempts_remaining=2, duration_s=4.628000, error_message=jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed, trace=java.util.concurrent.ExecutionException: jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
at durablejobs.AbstractDurableJobRunner.runJobWithTimeout(AbstractDurableJobRunner.java:230)
at durablejobs.AbstractDurableJobRunner.runJob(AbstractDurableJobRunner.java:142)
at durablejobs.AbstractDurableJobRunner.runJobs(AbstractDurableJobRunner.java:90)
at modules.DurableJobModule$DurableJobRunnerScheduler.lambda$new$0(DurableJobModule.java:102)
at org.apache.pekko.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:124)
at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed
at io.ebeaninternal.server.transaction.JdbcTransaction.doRollback(JdbcTransaction.java:1024)
at io.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:1009)
at io.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:996)
at durablejobs.jobs.CalculateEligibilityDeterminationJob.run(CalculateEligibilityDeterminationJob.java:111)
at durablejobs.AbstractDurableJobRunner.lambda$runJobWithTimeout$0(AbstractDurableJobRunner.java:221)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Connection is closed
at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
at jdk.proxy3/jdk.proxy3.$Proxy42.rollback(Unknown Source)
at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:385)
at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
at io.ebeaninternal.server.transaction.JdbcTransaction.performRollback(JdbcTransaction.java:812)
at io.ebeaninternal.server.transaction.JdbcTransaction.doRollback(JdbcTransaction.java:1022)
... 10 more
END_ERROR
Eligibility Determination: stopping early after 10 errors
END_ERROR
JobRunner_JobFailed ExecutionException job_name="CALCULATE_ELIGIBILITY_DETERMINATION_JOB", job_ID=635, attempts_remaining=1, duration_s=1.509000, error_message=jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed, trace=java.util.concurrent.ExecutionException: jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
at durablejobs.AbstractDurableJobRunner.runJobWithTimeout(AbstractDurableJobRunner.java:230)
at durablejobs.AbstractDurableJobRunner.runJob(AbstractDurableJobRunner.java:142)
at durablejobs.AbstractDurableJobRunner.runJobs(AbstractDurableJobRunner.java:90)
at modules.DurableJobModule$DurableJobRunnerScheduler.lambda$new$0(DurableJobModule.java:102)
at org.apache.pekko.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:124)
at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed
at io.ebeaninternal.server.transaction.JdbcTransaction.doRollback(JdbcTransaction.java:1024)
at io.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:1009)
at io.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:996)
at durablejobs.jobs.CalculateEligibilityDeterminationJob.run(CalculateEligibilityDeterminationJob.java:111)
at durablejobs.AbstractDurableJobRunner.lambda$runJobWithTimeout$0(AbstractDurableJobRunner.java:221)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Connection is closed
at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
at jdk.proxy3/jdk.proxy3.$Proxy42.rollback(Unknown Source)
at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:385)
at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
at io.ebeaninternal.server.transaction.JdbcTransaction.performRollback(JdbcTransaction.java:812)
at io.ebeaninternal.server.transaction.JdbcTransaction.doRollback(JdbcTransaction.java:1022)
... 10 more
END_ERROR
Eligibility Determination: stopping early after 10 errors
END_ERROR
JobRunner_JobFailed ExecutionException job_name="CALCULATE_ELIGIBILITY_DETERMINATION_JOB", job_ID=635, attempts_remaining=0, duration_s=1.182000, error_message=jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed, trace=java.util.concurrent.ExecutionException: jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
at durablejobs.AbstractDurableJobRunner.runJobWithTimeout(AbstractDurableJobRunner.java:230)
at durablejobs.AbstractDurableJobRunner.runJob(AbstractDurableJobRunner.java:142)
at durablejobs.AbstractDurableJobRunner.runJobs(AbstractDurableJobRunner.java:90)
at modules.DurableJobModule$DurableJobRunnerScheduler.lambda$new$0(DurableJobModule.java:102)
at org.apache.pekko.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:124)
at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: jakarta.persistence.PersistenceException: java.sql.SQLException: Connection is closed
at io.ebeaninternal.server.transaction.JdbcTransaction.doRollback(JdbcTransaction.java:1024)
at io.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:1009)
at io.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:996)
at durablejobs.jobs.CalculateEligibilityDeterminationJob.run(CalculateEligibilityDeterminationJob.java:111)
at durablejobs.AbstractDurableJobRunner.lambda$runJobWithTimeout$0(AbstractDurableJobRunner.java:221)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source) 
```

**To Reproduce**

1. Create a program with an eligibility condition and publish
2. Apply to the program as an applicant
3. Update the data in the db so that the `eligibility_determination` column on the `applications` table equals `NOT_COMPUTED`
4. Run the `CalculateEligibilityDeterminationJob` via the dev tools and see the error
5. See that `eligibility_determination` column on the `applications` table is still `NOT_COMPUTED`

**Expected behavior**
`CALCULATE_ELIGIBILITY_DETERMINATION_JOB` should run without error and all `NOT_COMPUTED` values in the `eligibility_determination` column should be updated to the [appropriate value](https://github.com/civiform/civiform/blob/main/server/app/models/EligibilityDetermination.java).

**Additional context**

### PR DESCRIPTION
**Pull request by rockycodes**
### Description

`CalculateEligibilityDeterminationJob` job runs have been failing because Program Definitions are not fully hydrated with Question Definitions and underlying code that expects Question Definitions is erroring out. This change updates `CalculateEligibilityDeterminationJob` to fetch the program definition with `programService.getFullProgramDefinition` so that nested code which requires question definitions will run successfully.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from `civiform/eng-admin` as FYI (if the primary reviewer is not an admin and this PR includes functionality changes)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [x] Noted in the PR description which, if any, code in this PR was generated by AI.

#### Durable jobs

Read the docs [here](https://github.com/civiform/civiform/wiki/Database#durable-jobs-for-data-updates)

- [ ] Assigned two reviewers
- [ ] Included a rollback plan and a job to undo the data changes if appropriate

### Instructions for manual testing

1. Create a program with an eligibility condition and publish it
2. Apply to the program as an applicant
3. Update the data in the db so that the `eligibility_determination` column on the `applications` table equals `NOT_COMPUTED`
4. Run the `CalculateEligibilityDeterminationJob` via the dev tools and ensure it completes with no errors
5. Double check that the `eligibility_determination` column on the `applications` table was updated correctly for all `active` applications

### Issue(s) this completes

Fixes #11154

### CODE REVIEW

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java [hunk 1]
```diff
@@ -72,11 +76,14 @@ public void run() {
                   "Calculating eligibility determination for application id {}",
                   application.id); // Use the captured ID
 
-              ProgramModel pm = application.getProgram();
-              ProgramDefinition programDefinition = pm.getProgramDefinition();
+              Long programId = application.getProgram().id;
+              ProgramDefinition programDefinition =
+                  programService.getFullProgramDefinition(programId);
```
Comment (rockycodes) [inline server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:81]: A note about testing: I added an "eligible" test to `CalculateEligibilityDeterminationTest` which duplicates most of [the ineligible test](https://github.com/civiform/civiform/blob/main/server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java#L157), but both tests pass with/without this change so I didn't included it. It seems like those tests should fail with the same error we're seeing in prod, but they don't and I'm not sure why. I would love any thoughts/advice on why this might be so we can fully test this scenario!

**Review by orwant — APPROVED** [review]

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 1 above)
Comment (dkatzz) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:81]: Based on the discussion earlier - if the issue had to do with the enumerator check, would adding an enumerator question as part of the test trigger the error?

**Review by swatkat1 — APPROVED** [review]
Thanks for fixing this Rocky!

File: server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java (hunk 1 above)
Comment (rockycodes) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:81]: Great question, I'll try that. I'm pretty sure the check fails for all question types though.

Comment (rockycodes) [reply server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java:81]: @dkatzz I wasn't able to get the test to fail using an enumerator question either. I'm going to resolve this for now and will look into these tests further later!
