### PR TITLE
[Suffix] suffix for json presenter

### LINKED ISSUE #8589: [Suffix] Suffix field was not showing up under sample API response preview
**Describe the bug**
Suffix field was not showing up under sample API response preview.

**To Reproduce**

1. Go to 'https://baseurl/api/docs/v1/minimal-sample-program/active'
2. See there is no su error

**Expected behavior**
Sample API response preview to include suffix as a field.

**Screenshots**
Screenshot 2024-09-12 at 11 04 04 AM

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by azhangggggg**
### Description

Include name suffix in json doc, so that it shows up correctly under sample API response preview.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).

#### User visible changes

- [ ] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) any new strings
  - [ ] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [ ] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [x] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Made equivalent changes in Thymeleaf for applicant-facing features and changes (or created an issue in the [Northstar epic](https://github.com/orgs/civiform/projects/1/views/94) to track that it's missing from Thymeleaf)
- [x] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [x] Manually tested at 200% size
- [x] Manually evaluated tab order

### Issue(s) this completes

Fixes #8589

### CODE REVIEW

File: server/test/services/export/JsonExporterServiceTest.java [hunk 1]
```diff
@@ -1232,6 +1231,7 @@ public void export_whenNameQuestionIsAnswered_valueIsInResponse() {
           "first_name" : "Taylor",
           "last_name" : "Swift",
           "middle_name" : "Allison",
+          "name_suffix" : "I",
```
Comment (avaleske) [inline server/test/services/export/JsonExporterServiceTest.java:1234]: discussed offline but this should be `suffix` to match the csv

**Review by avaleske — CHANGES_REQUESTED** [review]

**Review by avaleske — APPROVED** [review]
Approve once we remove `replaceSuffixPath()` since it's now unused.
