### PR TITLE
[External Program Cards] Close modal when clicking outside the modal for external program opened after HTMX initialization 

### LINKED ISSUE #10591: [External Program Cards] Close modal for external program opened after HTMX initialization by clicking outside the modal
**Describe the bug**
The modal trigger is added after initialization via HTMX and doesn't have an event listener. Therefore, we added a 'htmx:afterSwap' listener that adds a click listener to the modal trigger buttons to show the modal
and listen for close actions to hide the modal.

Clicking outside the modal should close the modal. However, only clicking twice closes the modal. We should fix this.

**To Reproduce**
1. Log in as an admin
2. Enable EXTERNAL_PROGRAM_CARDS_ENABLED feature flag
3. Create and publish an external program with a filter
4. Logout
5. In the applicant home, verify the external program has a card on the 'Programs and Services' section
6. Apply the filter, verify the external program has a card on the 'Programs based on your selections ' section
7. Click on 'View on a new tab' which opens a modal
8. Click outside the modal

**Expected behavior**
Modal closes

**Actual behavior**
Modal stays opened. Click again outside the modal, modal is closed

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/user-attachments/assets/22a02f09-1f3c-484c-a3bd-a271abcd4c92)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version: 138.0.7180.2 (Official Build) dev (64-bit)

### PR DESCRIPTION
**Pull request by EmiliaPaz**
### Description

Program cards for external programs are rendered with HTMX when a filter is selected. Since the modal trigger is added after initialization via HTMX and doesn't have an event listener, 'htmx:afterSwap' listener adds a click listener to the modal trigger buttons to show the modal and listen for close actions to hide the modal.

This PR adds a click listener to the modal wrapper to close the modal if there is a click inside the wrapper but outside the actual dialog

Solution was suggested by AI, but fully verified by PR owner.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [ ] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [ ] Noted in the PR description which, if any, code in this PR was generated by AI.

#### User visible changes

- [ ] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) any new strings
  - [ ] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [ ] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Made equivalent changes in Thymeleaf for applicant-facing features and changes (or created an issue in the [Northstar epic](https://github.com/orgs/civiform/projects/1/views/94) to track that it's missing from Thymeleaf)
- [x] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [x] Manually tested at 200% size
- [ ] Manually evaluated tab order
- [ ] Manually tested with a screen reader if the feature is applicant-facing. See [screen reader testing](https://github.com/civiform/civiform/wiki/Testing#screen-reader-testing)

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [x] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

1. Log in as an admin
2. Enable EXTERNAL_PROGRAM_CARDS_ENABLED feature flag
3. Create and publish an external program with a filter
4. Logout
5. In the applicant home, verify the external program has a card on the 'Programs and Services' section
6. Apply the filter, verify the external program has a card on the 'Programs based on your selections ' section
7. Click on 'View on a new tab' which opens a modal
8. Click outside the modal

### Issue(s) this completes

Fixes #10591

### CODE REVIEW

**Comment by EmiliaPaz** [comment]
* **#10619** <a href="https://app.graphite.dev/github/pr/civiform/civiform/10619?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/civiform/civiform/10619?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: server/app/assets/javascripts/north_star_modal.ts [hunk 1]
```diff
@@ -148,6 +148,18 @@ export class NorthStarModalController {
         }
       }
       document.addEventListener('keydown', escapeKeyHandler)
+
+      // Add listener to hide modal when clicking outside the modal
+      modalWrapper.addEventListener('click', (event) => {
+        console.log('clicked modal wrapper')
```
Comment (melanie-exygy) [inline server/app/assets/javascripts/north_star_modal.ts:154]: **nitpick:** Might want to remove this `console.log()`.

File: browser-test/src/applicant/northstar_applicant_application_index.test.ts [hunk 2]
```diff
@@ -1555,6 +1555,33 @@ test.describe(
...
+          .filter({hasText: 'This will open a different website'})
+        const modalDialog = modalWrapper.locator('.usa-modal')
+
+        // Calculate a position that is within the wrapper but outside the dialog
+        const wrapperBox = await modalWrapper.boundingBox()
+        const dialogBox = await modalDialog.boundingBox()
+
+        // Click in the wrapper but outside the dialog
+        if (wrapperBox && dialogBox) {
+          await page.mouse.click(wrapperBox?.x + 10, wrapperBox?.y + 10)
```
Comment (melanie-exygy) [inline browser-test/src/applicant/northstar_applicant_application_index.test.ts:1570]: **question (non-blocking):** How do we know that +10 on the wrapper will be outside the dialog box?   Could we use the dialog box as the starting point instead?

**Review by melanie-exygy — COMMENTED** [review]
This is a clever solution.  Did you ever figure out why it was previously closing with two clicks?  Not important to know since your solution does work, but I'm curious.

File: browser-test/src/applicant/northstar_applicant_application_index.test.ts (hunk 2 above)
Comment (EmiliaPaz) [reply browser-test/src/applicant/northstar_applicant_application_index.test.ts]: We don't.. What about clicking on the top left corner (at 0,0). The modal is always centered in the middle and never fully expands, so this should be more reliable.
Couldn't find a better way to simulate a click in the wrapper outside the modal :/

**Comment by EmiliaPaz** [comment]
> This is a clever solution. Did you ever figure out why it was previously closing with two clicks? Not important to know since your solution does work, but I'm curious.
I've got a theory. The first click in the modal wrapper (outside the actual modal) "activates" the modal by adding `class="usa-js-modal--active"`. Then the second click is actually listened for. I guess another solution would be to "activating" the modal since it's opened, and that could have fixed the other "hide on close" listener we had to add... However, not sure on how to do that and this looks good, or at least good enough :)

File: browser-test/src/applicant/northstar_applicant_application_index.test.ts (hunk 2 above)
Comment (melanie-exygy) [reply browser-test/src/applicant/northstar_applicant_application_index.test.ts]: Using the top left corner seems like a good idea!

**Review by melanie-exygy — APPROVED** [review]
