### PR TITLE
[Status_migration] Migrate statuses from Programs table to Application_statuses table and give ability to set Applications to latest status

### LINKED ISSUE #7040: Ensure application status can always be changed to any available status
**Describe the bug**
1. If a submission does not have a status (eg, no default status was set), the submission cannot be changed to a different status. 
2. If a submission has Status A, and Status B was created after the submission was submitted, the submission's status cannot be changed to Status B. 

**Expected behavior**
1. Admins are able to add status to a submission that currently does not have a status. The same status dropdown shows for submissions without a status as for submissions with a status.
2. Admins are able to change a submission to any current status, including statuses created after the submission.

**Additional context**
This is needed as part of our [bulk status updates](https://docs.google.com/document/d/19jETzFmpIHEGfHfEbzqnPwSGmEB-WD-mauhXl5b9CDE/edit) work.

### PR DESCRIPTION
**Pull request by swatkat1**
### Description

[Status_migration] Migrate statuses from Programs table to Application_statuses table and give ability to set Applications to latest status.

## Release notes

Migrate statuses from Programs table to Application_statuses table and give ability to set Applications to latest status.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary

#### Database evolutions

Read the guidelines [here](https://github.com/civiform/civiform/wiki/Database#writing-database-evolutions)

- [x] Assigned two reviewers
- [x] Guarded against already existing resources using `IF NOT EXISTS` and `IF EXISTS`
- [ ] Downs created to undo changes in Ups

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #7040

### CODE REVIEW

**Review by avaleske — CHANGES_REQUESTED** [review]
Overall it looks good!

- I had some thoughts about what order to apply database changes to ensure consistency, so we don't accidentally end up with multiple active StatusDefinitions.
- also some naming nits

- I don't _think_ this is necessary, since this is temporary and not critical applicant data, but if we wanted to be especially careful about maintaining consistency we could save the `StatusDefinitions` by calling the `ApplicationStatusesRepository` from `ProgramRepository::updateProgramSync()` and `ProgramRepository::insertProgramSync()`, and wrapping both the `database.update()` and `ApplicationStatusesRepository::createOrUpdateStatusDefinitions()` calls in a transaction.

File: server/test/services/program/ProgramServiceTest.java [hunk 1]
```diff
@@ -2505,6 +2527,16 @@ public void updateLocalizations_doesNotProvideStatus_throws() {
 
     assertThatThrownBy(() -> ps.updateLocalization(program.id, Locale.FRENCH, updateData))
         .isInstanceOf(OutOfDateStatusesException.class);
+    // test hooks to new ApplicationStatusRepository
+    // no updates to repository
+    StatusDefinitions currentStatus =
```
[the remark this answers is not in the document]
Comment (swatkat1) [reply server/test/services/program/ProgramServiceTest.java:2532]: We are testing if the update is happening- we shouldn't see any updates, that's what we are testing.

File: server/conf/evolutions/default/68.sql [hunk 2]
```diff
@@ -1,5 +1,4 @@
  --- Create the categories and programs_categories tables.
-
```
[the remark this answers is not in the document]
Comment (swatkat1) [reply server/conf/evolutions/default/68.sql:2]: Reverting

File: server/test/services/program/ProgramServiceTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (swatkat1) [reply server/test/services/program/ProgramServiceTest.java:2532]: I have updated the comment Austin

File: server/test/services/program/ProgramServiceTest.java [hunk 3]
```diff
@@ -2542,6 +2574,16 @@ public void updateLocalizations_emailProvidedInUpdateWithNoEmailInConfigure_thro
 
     assertThatThrownBy(() -> ps.updateLocalization(program.id, Locale.FRENCH, updateData))
         .isInstanceOf(OutOfDateStatusesException.class);
+    // test hooks to new ApplicationStatusRepository
```
[the remark this answers is not in the document]
Comment (swatkat1) [reply server/test/services/program/ProgramServiceTest.java:2577]: yes. Updated the comment to say -"no update to applicationstatusRepository"

File: server/test/support/ProgramBuilder.java [hunk 4]
```diff
@@ -324,6 +325,11 @@ public ProgramDefinition buildDefinition() {
   /** Returns the {@link ProgramModel} built from this {@link ProgramBuilder}. */
   public ProgramModel build() {
     ProgramDefinition programDefinition = builder.build();
+    ApplicationStatusesRepository appStatusRepo =
+        injector.instanceOf(ApplicationStatusesRepository.class);
```
[the remark this answers is not in the document]
Comment (swatkat1) [reply server/test/support/ProgramBuilder.java:331]: I thought adding it to the build() method will be easier :)

File: server/app/services/applications/ProgramAdminApplicationService.java [hunk 5]
```diff
@@ -95,9 +99,13 @@ public void setStatus(
     // The send/sent phrasing is a little weird as the service layer is converting between intent
     // and reality.
     boolean sendEmail = newStatusEvent.emailSent();
+    ProgramDefinition programDef = programRepository.getShallowProgramDefinition(program);
```
Comment (dkatzz) [inline server/app/services/applications/ProgramAdminApplicationService.java:102]: **suggestion (non-blocking):** In this case, I think we're better off making the call to [get the full program definition](https://github.com/civiform/civiform/blob/b75bc4e6dd27df9981036c3acc6e6d974b6eb46a/server/app/services/program/ProgramService.java#L175), since that will utilize the cache if its available. I imagine when we change this to allow for bulk status updates, calling to get the program definition on every status update will slow things down a lot. I know this was already being called each time, so this is somewhat outside the scope of this PR, but something to be aware of.

File: server/app/services/program/ProgramService.java [hunk 6]
```diff
@@ -716,18 +730,30 @@ public ErrorAnd<ProgramDefinition, CiviFormError> updateLocalization(
...
-            .join());
+    ErrorAnd<ProgramDefinition, CiviFormError> result =
+        ErrorAnd.of(
+            syncProgramDefinitionQuestions(
+                    programRepository.getShallowProgramDefinition(
+                        programRepository.updateProgramSync(newProgram.build().toProgram())))
+                .toCompletableFuture()
+                .join());
+    if (!result.isError()) {
+      // Temporary hook to create a new row in ApplicationStatuses table for the status change
```
Comment (dkatzz) [inline server/app/services/program/ProgramService.java:748]: **suggestion:** This will only update in this case, right? Or will it sometimes create? Would you mind updating the comment if that's the case and also to also mention that this will save the statuses with its localized names set above?

File: server/app/services/program/ProgramService.java [hunk 7]
```diff
@@ -814,12 +840,28 @@ public ErrorAnd<ProgramDefinition, CiviFormError> appendStatus(
...
+    if (!result.isError()) {
+      // Temporary hook to create a new row in ApplicationStatuses table for the status change.
+      // Remove these hooks when we have created service class for creating/updating
+      // statuses from program controllers.
+      // github issue- https://github.com/civiform/civiform/issues/7040
+      applicationStatusesRepository.createOrUpdateStatusDefinitions(
+          program.adminName(),
+          new StatusDefinitions()
+              .setStatuses(
+                  ImmutableList.<StatusDefinitions.Status>builder()
```
Comment (dkatzz) [inline server/app/services/program/ProgramService.java:859]: **suggestion (non-blocking):** You can consider pulling this out into a variable and using it here and above, but since this is temporary, feel free to leave it as is if you prefer.

File: server/app/services/program/ProgramService.java [hunk 8]
```diff
@@ -814,12 +840,28 @@ public ErrorAnd<ProgramDefinition, CiviFormError> appendStatus(
...
-            .join());
+    ErrorAnd<ProgramDefinition, CiviFormError> result =
+        ErrorAnd.of(
+            syncProgramDefinitionQuestions(
+                    programRepository.getShallowProgramDefinition(
+                        programRepository.updateProgramSync(program.toProgram())))
+                .toCompletableFuture()
+                .join());
+    if (!result.isError()) {
+      // Temporary hook to create a new row in ApplicationStatuses table for the status change.
```
Comment (dkatzz) [inline server/app/services/program/ProgramService.java:851]: **question:** Does it create in this case? If it only updates will you reflect that in the comment or if it can do either, can you add that as well.

File: server/app/services/program/ProgramService.java [hunk 9]
```diff
@@ -877,13 +919,22 @@ public ErrorAnd<ProgramDefinition, CiviFormError> editStatus(
...
```
Comment (dkatzz) [inline server/app/services/program/ProgramService.java:930]: **question:** Same question as above.

File: server/conf/evolutions/default/70.sql [hunk 10]
```diff
@@ -0,0 +1,23 @@
+# --- !Ups
```
Comment (dkatzz) [inline server/conf/evolutions/default/70.sql:1]: **suggestion:** Could you add a comment to the top of this file explaining the change briefly. Something like "Copies over statuses from the programs table to the new application_statuses table"

File: server/test/repository/ApplicationStatusesRepositoryTest.java [hunk 11]
```diff
@@ -39,16 +37,11 @@ public void canQueryForActiveApplicationStatuses() {
...
+            .withStatusDefinitions(new StatusDefinitions(ImmutableList.of(APPROVED_STATUS)))
             .build();
-    String programName = program.getProgramDefinition().adminName();
-    StatusDefinitions statusDefinitions = new StatusDefinitions(ImmutableList.of(APPROVED_STATUS));
-    ApplicationStatusesModel applicationStatusesModel =
-        new ApplicationStatusesModel(
-            programName, statusDefinitions, StatusDefinitionsLifecycleStage.ACTIVE);
-    applicationStatusesModel.save();
-    applicationStatusesModel.setCreateTimeForTest("2041-01-01T00:00:00Z").save();
     // test
```
Comment (dkatzz) [inline server/test/repository/ApplicationStatusesRepositoryTest.java:42]: **nitpick:** Not related to your PR but this test comment seems like it was accidentally put there. Would you mind removing it?

File: server/conf/evolutions/default/69.sql [hunk 12]
```diff
@@ -0,0 +1,23 @@
...
+  p.name,
+  p.status_definitions,
+  'active' AS status_definitions_lifecycle_stage,
+  p.create_time
+FROM programs p
+       INNER JOIN versions_programs vp ON vp.programs_id = p.id
+       INNER JOIN versions v ON vp.versions_id = v.id
+WHERE v.lifecycle_stage IN ('active');
+
+INSERT INTO application_statuses (program_name,status_definitions,status_definitions_lifecycle_stage)
```
[the remark this answers is not in the document]
Comment (dkatzz) [reply server/conf/evolutions/default/69.sql]: SGTM too!

**Review by dkatzz — COMMENTED** [review]
LGTM! Just a couple of questions and some comments, but mostly non-blocking.

File: server/app/services/applications/ProgramAdminApplicationService.java (hunk 5 above)
Comment (swatkat1) [reply server/app/services/applications/ProgramAdminApplicationService.java:102]: This code is just a temporary hook Danielle. I plan to move this to its ApplicationStatusService class which will be called from the controller. Since this is getting the shallowProgramDef only for checking error state, does it matter?/

File: server/app/services/program/ProgramService.java (hunk 6 above)
Comment (swatkat1) [reply server/app/services/program/ProgramService.java:748]: For every change in status, it will update the current active one to "obsolete" and a the latest one as active. Yes, it will do both. I will update the comment :)

File: server/app/services/program/ProgramService.java (hunk 7 above)
Comment (swatkat1) [reply server/app/services/program/ProgramService.java:913]: It get moved Danielle soon. I think its ok to leave it here. :)

File: server/app/services/program/ProgramService.java (hunk 9 above)
Comment (swatkat1) [reply server/app/services/program/ProgramService.java]: Will be moved soon. So leaving it as such :)

File: server/test/repository/ApplicationStatusesRepositoryTest.java (hunk 11 above)
Comment (swatkat1) [reply server/test/repository/ApplicationStatusesRepositoryTest.java:42]: removed :)

File: server/app/services/applications/ProgramAdminApplicationService.java (hunk 5 above)
Comment (dkatzz) [reply server/app/services/applications/ProgramAdminApplicationService.java:102]: It looks like its part of the `setStatus` function, which I assume gets called each time someone wants to update a status (meaning a database call for each application that the status is changing for). This can be part of a larger refactor I'll plan to do though, so no worries on changing it in this PR.

File: server/app/services/program/ProgramService.java (hunk 6 above)
Comment (dkatzz) [reply server/app/services/program/ProgramService.java:775]: Thank you!

**Review by dkatzz — APPROVED** [review]

**Review by avaleske — APPROVED** [review]
