### PR TITLE
Fixes customized eligibility msg field showing up on visibility condition page

### LINKED ISSUE #10070: The visibility editor when editing a screen's visibility as a civiform admin shows an eligibility message field
**Describe the bug**
As a civiform admin, when you edit the visibility of a screen, there is an option to include an eligibility message.

**To Reproduce**

1. Log in as an admin
2. Go to a program
3. Create a new screen or navigate to an existing screen
4. Select 'Edit visibility condition'
5. See the 'eligibility message' field

**Expected behavior**
There is no eligibility message field because this is the visibility editing.

**Screenshots**
Image

**Desktop (please complete the following information):**

- MacOS
- Chrome

### PR DESCRIPTION
**Pull request by azhangggggg**
### Description

For CiviForm admins, customized eligibility message text field shows up on visibility condition page, but the field is only supposed to show up on eligibility page. This PR is a fix for this bug. 

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`

### Issue(s) this completes

Fixes #10070

### CODE REVIEW

File: server/app/views/admin/programs/ProgramPredicatesEditView.java [hunk 1]
```diff
@@ -231,7 +231,8 @@ public Content render(
             .with(removePredicateForm)
             // Show the eligibility message field, if the eligibility msg feature flag is on.
```
Comment (swatkat1) [inline server/app/views/admin/programs/ProgramPredicatesEditView.java:232]: Non-blocking - May be the comment needs to be updated too

Comment (azhangggggg) [reply server/app/views/admin/programs/ProgramPredicatesEditView.java]: good point - updated!

**Review by swatkat1 — APPROVED** [review]
Thanks!
