### PR TITLE
[Program Migration] handle server errors

### LINKED ISSUE #8653: [Program Migration] Handle server errors
Several server errors are being swallowed and no error is shown to the user. These include:
- changing the language to one that doesn't exist
- changing the id of a question to one that already exists or random number (null pointer exception)

See slack for details about exceptions: 
https://civiform.slack.com/archives/C07KXU02B70/p1726678882148489
https://civiform.slack.com/archives/C07KXU02B70/p1726679184681119

### PR DESCRIPTION
**Pull request by rockycodes**
### Description

This is a bug fix to surface a user facing an error when a server error occurs. Previously nothing would show and it would just look like nothing was happening.

There were two cases during bug bash where testers triggered a server error:
- trying to save a program with a language that doesn't exist
- trying to save a program where the question id on the question and in the block definition do not match

This fix handles both of those cases and should handle any other server errors that occur when attempting to render the program preview.

#### General

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Instructions for manual testing

1. Enable program migration flag
2. Copy program json into the import box
3. Edit the question id in the block definition to be different than the question ids on the questions
4. Click "Preview program"
5. See error message

### Issue(s) this completes

Fixes #8653;

### CODE REVIEW

File: server/test/controllers/admin/AdminImportControllerTest.java [hunk 1]
```diff
@@ -1874,4 +1893,101 @@ public void hxSaveProgram_noDuplicatesEnabled_addsAnEmptyStatus() {
...
+          + "      },\n"
+          + "      \"validationPredicates\" : {\n"
+          + "        \"type\" : \"name\"\n"
+          + "      },\n"
+          + "      \"id\" : 1,\n"
+          + "      \"universal\" : false,\n"
+          + "      \"primaryApplicantInfoTags\" : [ ]\n"
+          + "    }\n"
+          + "  } ]\n"
+          + "}";
```
Comment (gwendolyngoetz) [inline server/test/controllers/admin/AdminImportControllerTest.java:1992]: (non-blocking) Do you mind swapping this to the """ based [multiline string](https://www.baeldung.com/java-multiline-string)? It'll be easier to read and maintain.

**Review by gwendolyngoetz — CHANGES_REQUESTED** [review]

File: server/test/controllers/admin/AdminImportControllerTest.java (hunk 1 above)
Comment (rockycodes) [reply server/test/controllers/admin/AdminImportControllerTest.java]: done!

**Review by gwendolyngoetz — APPROVED** [review]
+1 for extra effort changing all the multiline strings!!
