### PR TITLE
[Maps] add no results help text

### LINKED ISSUE #11812: Help text not displayed when there are no results returned
**Describe the bug**
When an applicant applies a filter combination that returns no locations, there isn't any help text displayed in the listing area to help guide the user to correct the issue.

**To Reproduce**

1. Go to staging site
2. Create a map question and add it to a test program
3. Click "Preview as applicant"
4. Navigate to screen with map question
5. Apply filter combination that returns no results
7. See error

**Expected behavior**
When no results are returned, I would expect there to be help text displayed in the listing area to help guide the user to correct the issue: "No results found. Please try adjusting your filters." Design for reference [here](https://www.figma.com/design/OrNOrdj2qdM9xfXLd7lUGL/Location-selection-via-mapping?node-id=1543-20938&t=p7Ffd0sBrtA4eUnp-1).

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tallulahkay**
### Description

Add help text for when there are no results from a set of filters in the map question.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [ ] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [ ] Added an additional reviewer from `civiform/eng-admin` as FYI (if the primary reviewer is not an admin and this PR includes functionality changes)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [x] Noted in the PR description which, if any, code in this PR was generated by AI.

### Instructions for manual testing

1. Create a map question (include filters).
2. Add to a program.
3. As an applicant, choose a combination of filters that displays no results.

### Issue(s) this completes

Fixes #11812;

### CODE REVIEW

File: server/app/assets/javascripts/mapquestion/map_question_filters.ts [hunk 1]
```diff
@@ -75,23 +76,35 @@ const applyLocationFilters = (
...
+    mapId,
+    visibleCount,
+    locationCheckboxContainers.length,
+  )
   resetPagination(mapId)
 }
 
-const updateLocationCountForMap = (mapId: string): void => {
-  const locationCheckboxes = queryLocationCheckboxes(mapId)
-  const visibleCount = Array.from(locationCheckboxes).filter((checkbox) => {
```
Comment (tallulahkay) [inline server/app/assets/javascripts/mapquestion/map_question_filters.ts:99]: **note:** I realized this loop is unnecessary

**Review by fernandez-jack — APPROVED** [review]
LGTM

**Comment by fernandez-jack** [comment]
But please make sure the failing checks - took a brief look at one and it may just be maven being flaky and need a re-run

**Comment by tallulahkay** [comment]
> But please make sure the failing checks - took a brief look at one and it may just be maven being flaky and need a re-run

agreed it's flaky I'll rerun them and hopefully they pass 🤞

File: server/app/assets/javascripts/mapquestion/map_question_filters.ts [hunk 2]
```diff
@@ -90,18 +92,30 @@ const applyLocationFilters = (
       }
     }
   })
-  updateLocationCountForMap(mapId)
+
+  updateLocationCountForMap(
+    mapId,
+    visibleCount,
+    locationCheckboxContainers.length,
```
Comment (avrittrohwer) [inline server/app/assets/javascripts/mapquestion/map_question_filters.ts:99]: Part of the nitpick:

```suggestion
    totalCount,
```

File: server/app/assets/javascripts/mapquestion/map_question_filters.ts [hunk 3]
```diff
@@ -70,6 +70,7 @@ const applyLocationFilters = (
     openPopupFeatureId = popupContent.getAttribute(DATA_FEATURE_ID)
   }
 
+  let visibleCount = 0
   locationCheckboxContainers.forEach((container) => {
```
Comment (avrittrohwer) [inline server/app/assets/javascripts/mapquestion/map_question_filters.ts:74]: Nit-picking, feel free to ignore

```suggestion
  const totalCount = locationCheckboxContainers.length
  locationCheckboxContainers.forEach((container) => {
```

**Review by fernandez-jack — APPROVED** [review]
