### PR TITLE
Increase allowed payload size when saving program translations

### LINKED ISSUE #9992: Unable to save translations for large programs ERROR Request Entity Too Large
**Describe the bug**
When entering translations for larger programs with lots of larger status email messages I am running into an error of Request Entity Too Large.  Need to increase amount of text that can be saved to translations.

Image

**To Reproduce**

1. Find a program with a lot of statuses and large email text for each status 
2. Edit program
3. Select Translations
4. Enter translations
5. Click Save Tranlations

**Expected behavior**
Should be able to save translations for all program details and status messages without error due to amount of text

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

Increase allowed payload size when saving program translations.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### Issue(s) this completes

Fixes #9992

### CODE REVIEW

File: server/app/controllers/admin/AdminProgramTranslationsController.java [hunk 1]
```diff
@@ -128,6 +130,11 @@ private ProgramDefinition getDraftProgramDefinition(String programName) {
    *     same {@link ProgramTranslationView} with error messages
    */
   @Secure(authorizers = Authorizers.Labels.CIVIFORM_ADMIN)
+  // Adding our custom large body parser. The introduction of the eligibility message
+  // translations has resulted in the occasional exception if the program has a large
+  // number of them. This is a band-aid to allow them to be saved right now, the
```
Comment (codekarma) [inline server/app/controllers/admin/AdminProgramTranslationsController.java:135]: Do we have an issue tracking the redesign? Would it be helpful to include that in this comment?

**Review by codekarma — APPROVED** [review]
A minor nit about the comment.

File: server/app/controllers/admin/AdminProgramTranslationsController.java (hunk 1 above)
Comment (gwendolyngoetz) [reply server/app/controllers/admin/AdminProgramTranslationsController.java:135]: I plan on letting Shreya know and something will be filed
