### PR TITLE
Center align content within end of session toast

### LINKED ISSUE #9224: Center-align toast message content
#### Describe the solution presented in this issue.
Center-align toast message content.

image

#### Steps to reproduce:
1. From the Applicant Homepage, click on the "View and apply" button on any one of the program cards.
2. Click on the "End your session" link in the informational alert banner:  

Image

3. Note the alignment of the text in the green toast message.

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] The icons and text in toast messages are centered vertically and aligned with each other.

### PR DESCRIPTION
**Pull request by CallaJune**
### Description

This PR centers the icon, text, and exit button within the end of session toast.

Before: 
Screenshot 2026-01-07 at 4 38 44 PM
After:
Screenshot 2026-01-07 at 4 58 30 PM

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label (see [docs](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-appropriate-labels) for more info): < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from `civiform/eng-admin` as FYI (if this PR includes functionality changes and neither you nor the primary reviewer is an admin)
- [x] Removed the release notes section if the title is sufficient for the release notes description, or put more details in that section.
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [x] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [x] Noted in the PR description which, if any, code in this PR was generated by AI.

#### User visible changes

- [x] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) any new strings
  - [x] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
  - [x] Didn't use a message in applicant facing code that isn't translated yet (unless behind a flag)
- [x] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [x] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [x] Manually tested at 200% size
- [x] Manually evaluated tab order
- [x] Performed manual accessibility tests for any applicant-facing changes or any new admin-facing features. See [manual-accessibility-testing](https://github.com/civiform/civiform/wiki/Accessibility#manual-accessibility-testing)
- [x] Manually tested with a right-to-left language

### Instructions for manual testing

Steps to reproduce:
1. From the Applicant Homepage, click on the "View and apply" button on any one of the program cards.
2. Click on the "End your session" link in the informational alert banner.
3. Note the alignment of the text in the green toast message.

### Issue(s) this completes

Fixes #9224

### CODE REVIEW

**Comment by CallaJune** [comment]
* **#12349** <a href="https://app.graphite.com/github/pr/civiform/civiform/12349?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/civiform/civiform/12349?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: server/app/assets/javascripts/toast.ts [hunk 1]
```diff
@@ -197,7 +198,11 @@ export class ToastController {
    * @param {string} toastId The html id of the toast message
    * @param {boolean} dismissClicked Whether to add indicator in local storage to not show
    *  */
-  private static dismissToast(toastId: string, dismissClicked: boolean) {
+  private static dismissToast(
+    this: void,
```
Comment (gwendolyngoetz) [inline server/app/assets/javascripts/toast.ts]: (blocking, question) What's triggering the need for this?

File: browser-test/src/auth.test.ts [hunk 2]
```diff
@@ -100,6 +101,8 @@ test.describe('Applicant auth', () => {
     await loginAsTestUser(page)
     await logout(page, /* closeToast=*/ false)
     await validateToastMessage(page, 'Your session has ended.')
+    await validateScreenshot(page, 'auth-end-session-toast')
+    await validateToastLayoutCentered(page)
```
Comment (gwendolyngoetz) [inline browser-test/src/auth.test.ts]: (blocking) First, I appreciate the level of effort here, especially on your first PR. However, it's overkill for this application to calculate that this is centered mathematically. Let's take this function out.

I don't think this even needs a screenshot. You can just assert that the toast element has the `flex-align-center` class. See docs [here](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-class).

Comment (CallaJune) [reply browser-test/src/auth.test.ts]: Done -- removed the screenshot and centering tests and replaced them with a class checking the existence of the `flex-align-center` class.

File: server/app/assets/javascripts/toast.ts (hunk 1 above)
Comment (CallaJune) [reply server/app/assets/javascripts/toast.ts]: This is an error flagged by the formatter: 

```
  116:11  error  A method that is not declared with `this: void` may cause unintentional scoping of `this` when separated from its object.
Consider using an arrow function or explicitly `.bind()`ing the method to avoid calling the method with an unintended `this` value. 
If a function does not access `this`, it can be annotated with `this: void`
```

It is not entirely clear to me why the formatter has flagged it here as it appears to be existing and unrelated to the change I've made as far as I can tell. My best guess is that changing `toast.ts` triggered the formatter's scrutiny of this file.

File: browser-test/src/support/index.ts [hunk 3]
```diff
@@ -40,6 +40,7 @@ export {
   normalizeElements,
   validateToastHidden,
   validateToastMessage,
+  validateToastLayoutCentered,
```
Comment (tallulahkay) [inline browser-test/src/support/index.ts]: suggestion (blocking): this doesn't seem to be used anywhere. Does it need to be added?

File: browser-test/src/auth.test.ts [hunk 4]
```diff
@@ -100,6 +100,9 @@ test.describe('Applicant auth', () => {
     await loginAsTestUser(page)
     await logout(page, /* closeToast=*/ false)
     await validateToastMessage(page, 'Your session has ended.')
+    await expect(page.locator('.cf-toast')).toHaveClass(
```
Comment (tallulahkay) [inline browser-test/src/auth.test.ts:103]: suggestion (non-blocking): I think we could do a validateScreenshot test here of just the toast component so that we can easily tell if any other styling interferes with the centering

File: server/app/assets/javascripts/toast.ts [hunk 5]
```diff
@@ -85,6 +85,7 @@ export class ToastController {
     // Add the content string.
     const contentContainer = document.createElement('span')
     contentContainer.textContent = message.content
+    contentContainer.classList.add('display-flex', 'flex-align-center')
```
Comment (tallulahkay) [inline server/app/assets/javascripts/toast.ts]: suggestion (blocking): I think this line isn't necessary - when it's removed, the styling of the toast message doesn't change

File: server/app/assets/javascripts/toast.ts (hunk 1 above)
Comment (tallulahkay) [reply server/app/assets/javascripts/toast.ts]: I think it's a new/more strictly enforced eslint rule that came with a package update. I saw it start to pop up recently. 

Can you fix it by instead making line 15 `() => ToastController.dismissToast(message.id, false)`? just a simpler fix

File: browser-test/src/support/index.ts (hunk 3 above)
Comment (CallaJune) [reply browser-test/src/support/index.ts]: Nope -- I forgot to remove that. Odd that it didn't break something.

File: browser-test/src/auth.test.ts (hunk 4 above)
Comment (tallulahkay) [reply browser-test/src/auth.test.ts:103]: nvm!! @gwendolyngoetz had already suggested _not_ doing a screenshot - my bad :)

Comment (CallaJune) [reply browser-test/src/auth.test.ts:103]: Resolved offline -- we'll maintain removal of the screenshot test suggested in previous comment

File: server/app/assets/javascripts/toast.ts (hunk 5 above)
Comment (CallaJune) [reply server/app/assets/javascripts/toast.ts]: Removed and redid manual UI checks

File: server/app/assets/javascripts/toast.ts (hunk 1 above)
Comment (CallaJune) [reply server/app/assets/javascripts/toast.ts]: Done

**Review by gwendolyngoetz — APPROVED** [review]

**Review by tallulahkay — APPROVED** [review]
