### PR TITLE
Render question text with markdown formatting

### LINKED ISSUE #6420: Parse Markdown in Question Text in all places for admin
**Describe the bug**
Markdown for question text is not being correctly parsed in all places for admin.

**To Reproduce**

1. Create a question and use markdown in the question text
2. Navigate to one of the places described below
3. See the unparsed markdown

**Expected behavior**
Markdown should be parsed in all places text is shown

**Screenshots**

Question list view:
image

Question sidebar:
image

Program edit view:
image

**Additional context**
Other places may need parsing as well. Look at all the places the question text is referenced.

### PR DESCRIPTION
**Pull request by jcma-google**
### Description

Renders question text with markdown formatting in five new places

Some screenshot samples
- question bank
image

- program edit view
image

- question list view
image

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x ] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same organization as you)
- [x] Created unit and/or browser tests which fail without the change (if possible)
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [x] Extended the README / documentation, if necessary

### Issue(s) this completes

Fixes #6420

### CODE REVIEW

File: server/app/views/admin/programs/ProgramBlocksView.java [hunk 1]
```diff
@@ -434,7 +435,8 @@ private DivTag renderBlockPanel(
       ButtonTag blockDeleteModalButton,
       boolean isIntakeFormFeatureEnabled,
       Request request) {
-    // A block can only be deleted when it has no repeated blocks. Same is true for removing the
+    // A block can only be deleted when it has no repeated blocks. Same is true for
+    // removing the
```
Comment (rockycodes) [inline server/app/views/admin/programs/ProgramBlocksView.java:439]: nitpick: I guess `bin/fmt` decided to put the line breaks in different places 😂 will you move the next comment line (`// enumerator question from the block.`) up to this one so we don't have this weird two-word comment line? It looks like there are a bunch of places below where comments got split up in a strange way as well. Please fix those too.

File: server/app/views/components/TextFormatter.java [hunk 2]
```diff
@@ -38,6 +38,11 @@ public static ImmutableList<DomContent> formatText(
     return builder.build();
   }
 
+  /** Passes provided text through Markdown formatter. */
```
Comment (rockycodes) [inline server/app/views/components/TextFormatter.java:41]: nitpick: 
```suggestion
  /** Passes provided text through Markdown formatter without preserving empty lines or adding the required indicator. */
```

File: browser-test/src/admin/admin_program_creation.test.ts [hunk 3]
```diff
@@ -510,6 +510,39 @@ test.describe('program creation', () => {
     await expect(addressCorrectionInput).toHaveValue('false')
   })
 
+  test('create program with markdown questions', async ({
+    page,
+    adminQuestions,
+    adminPrograms,
+  }) => {
+    await loginAsAdmin(page)
+    await adminQuestions.addTextQuestion({
```
Comment (rockycodes) [inline browser-test/src/admin/admin_program_creation.test.ts:519]: suggestion (blocking): Add text for the other fields where we expect markdown to show up (I think this might just be `helpText`, but I'm not positive)

File: browser-test/src/admin/admin_question_list.test.ts [hunk 4]
```diff
@@ -31,25 +31,25 @@ test.describe('Admin question list', () => {
 
     // Most recently added question is on top.
     await expectQuestionListElements(adminQuestions, [
-      questionTwoPublishedText,
-      questionOnePublishedText,
+      'question list test question two\n',
```
Comment (rockycodes) [inline browser-test/src/admin/admin_question_list.test.ts:34]: suggestion (blocking): Reference the const here and then add `+ \n`. That way if someone changes the text for the const, they don't have to update it in multiple places.

File: browser-test/src/admin/admin_question_list.test.ts [hunk 5]
```diff
@@ -73,17 +73,39 @@ test.describe('Admin question list', () => {
...
+      questionOneDraftText + '\n',
+      questionTwoPublishedText + '\n',
     ])
   })
 
+  test('rendering markdown works', async ({page, adminQuestions}) => {
+    await loginAsAdmin(page)
+    await adminQuestions.addTextQuestion({
+      questionName: 'a',
+      questionText: '*italics*',
```
Comment (rockycodes) [inline browser-test/src/admin/admin_question_list.test.ts:91]: suggestion (blocking): add `helpText` with markdown to these questions as well.

**Review by rockycodes — CHANGES_REQUESTED** [review]
Looks good so far! I have a few blocking suggestions. In this PR, you're actually updating the question markdown so it shows up in 5 places (not 3):
- question bank
- program edit view
- question list view
- predicate configure view
- predicate edit view

Please add browser tests for all of those places to test that markdown renders.

File: browser-test/src/admin/admin_question_list.test.ts (hunk 4 above)
Comment (jcma-google) [reply browser-test/src/admin/admin_question_list.test.ts:34]: I've gotten into the habit of not using variables in the expect clause and I'm interested in discussing whether that makes sense for these unit tests! 

My reasoning is that by using the literal and not obfuscating them with a variable name is it directly conveys the expected value instead of having to scroll up and find what the variable matches. I also get "variable blindness" in that the names "questionOnePublishedText" and "questionTwoPublishedText" are so similar that it takes me a second or two to understand which text is expected. I think the literal strings themselves are easier to read because of the spaces :) 

But I think variables make sense if we want to make multiple assertions about a single interaction / object / class or property or complex interactions. I also believe consistency is important! So don't want to change it only here and have it be different from the current testing pattern. 

Let me know what you think!

Comment (rockycodes) [reply browser-test/src/admin/admin_question_list.test.ts:34]: That makes sense, and I actually hadn't thought about that before! I don't have a strong preference as long as we're consistent. I'd say go with either for now and let's chat about it at the next eng meet. It looks like there are some places where you're still referencing the var name in the expect statement though (eg `questionOneDraftText + '\n',`), so please update those to strings if you go that route.

File: browser-test/src/admin/admin_program_creation.test.ts (hunk 3 above)
Comment (rockycodes) [reply browser-test/src/admin/admin_program_creation.test.ts:519]: I think this comment is not resolved yet. My suggestion was to add `helpText` with markdown in it so we can cover that use case as well.

**Review by rockycodes — CHANGES_REQUESTED** [review]
There's just one outstanding comment (plus the comment about var names in tests) and I have some questions about these screenshots:
- `eligiblity-predicates-multi-values-multi-questions-predicate-edit` (what a name!), was regenerated, but I don't think there are any edits to that test that would require a new screenshot. That said, I think you do want to add some markdown to that test so this screenshot renders with markdown.
- same for `visibility-predicates-multi-questions-predicate-edit` (add some markdown)
- `operator-help-text.png` was also regenerated, but I believe there aren't any changes. If you delete the png and rebase off of main it should go away, but if it gets tricky with git it's fine to leave it.

**Comment by jcma-google** [comment]
I added markdown and regenerated screenshot tests for the eligibility predicates. For `operator-help-text.png` the screenshot was regenerated without any changes and I think I'll have to rebase to remove the file as changed. I hope that leaving it as-is is okay!

File: browser-test/src/admin/admin_program_creation.test.ts (hunk 3 above)
Comment (rockycodes) [reply browser-test/src/admin/admin_program_creation.test.ts:519]: This is still not resolved. My suggestion is to add `helpText` with markdown in it.

File: browser-test/src/support/admin_questions.ts [hunk 6]
```diff
@@ -1216,9 +1225,10 @@ export class AdminQuestions {
 
     await this.expectAdminQuestionsPageWithCreateSuccessToast()
 
-    expectedQuestionText = expectedQuestionText ?? questionText
-
-    await this.expectDraftQuestionExist(questionName, expectedQuestionText)
+    if (!markdown) {
```
Comment (rockycodes) [inline browser-test/src/support/admin_questions.ts:1228]: question (blocking): Why did you wrap this in `!markdown`? The way this is intended to work is you pass in `expectedQuestionText` if it's a markdown question and it checks for that first. https://github.com/civiform/civiform/pull/6688/files#diff-23ad99c6f330f49fe04c7f59414c9dd6933551c37ea33586d1094e92e1dcf016R1222

File: browser-test/src/admin/admin_predicates.test.ts [hunk 7]
```diff
@@ -609,6 +618,8 @@ test.describe('create and edit predicates', () => {
     await adminQuestions.addDateQuestion({questionName: 'date-question'})
     await adminQuestions.addCurrencyQuestion({
       questionName: 'currency-question',
+      questionText: '*currency-question*',
```
Comment (rockycodes) [inline browser-test/src/admin/admin_predicates.test.ts:621]: nitpick (non-blocking): take the `-` out of the `questionText` since generally we use those in admin names and not question titles (aka `questionText`).

**Review by rockycodes — CHANGES_REQUESTED** [review]
There is still an outstanding comment about including `helpText` with markdown in a test case (lmk if you think you don't need that). I also have a new question about an edit you made to `addTextQuestion` to skip the `expect` if it's a markdown question. 

Unfortunately, another PR went in that made changes to the `operator-help-text` screenshot, so you need to rebase on top of main in order for your tests to pass. Let me know if you want to pair on that!

File: browser-test/src/admin/admin_program_creation.test.ts (hunk 3 above)
Comment (jcma-google) [reply browser-test/src/admin/admin_program_creation.test.ts:519]: woops, missed this comment!

File: browser-test/src/support/admin_questions.ts (hunk 6 above)
Comment (jcma-google) [reply browser-test/src/support/admin_questions.ts:1228]: Because it's difficult to assert the markdown text without some additional manipulation which I am afraid would add brittleness to the test. For example, for the currency question the expected text is "*currency question*", with the asterisks because that's the pre-markdown rendering, and the received text is "currency question" because the markdown has now become stylistic rendering.

We have tests asserting the appearance of the markdown text in screenshots and I don't think we're losing much by skipping the innerText assertions (especially considering it would be onerous to assert that markdown is rendered correctly via presence of HTML elements).

Comment (rockycodes) [reply browser-test/src/support/admin_questions.ts:1228]: That makes sense! In that case, can you remove the `expectedQuestionText` param and logic (it's only used [here](https://github.com/civiform/civiform/blob/15c8a10338b236b07db5767b27f88bbdea318b25/browser-test/src/applicant/navigation/application_navigation_with_eligibility_conditions.test.ts#L359) I think) since we don't need it anymore?

Comment (rockycodes) [reply browser-test/src/support/admin_questions.ts:1228]: Alternatively you could pass in "currency question" for `expectedTest` if we wanted to keep this check, but I don't feel tied to that since we have other tests and it seems like it's not super clear how to use this workaround I added.

Comment (jcma-google) [reply browser-test/src/support/admin_questions.ts:1228]: done! removed the expectedQuestionText usage since that felt cleaner

File: browser-test/src/support/admin_questions.ts [hunk 8]
```diff
@@ -1215,10 +1222,6 @@ export class AdminQuestions {
     await this.clickSubmitButtonAndNavigate('Create')
 
     await this.expectAdminQuestionsPageWithCreateSuccessToast()
-
-    expectedQuestionText = expectedQuestionText ?? questionText
-
-    await this.expectDraftQuestionExist(questionName, expectedQuestionText)
```
Comment (rockycodes) [inline browser-test/src/support/admin_questions.ts:1221]: suggestion (blocking): We still want to keep `this.expectDraftQuestionExist` for questions that don't include markdown. I just meant to remove the `expectedQuestionText` logic. So this would become:

```
if (!markdown) {
await this.expectDraftQuestionExist(questionName, questionText)
}
```

**Review by rockycodes — APPROVED** [review]
lgtm! 🥳 will you make an issue to refactor the other calls to `formatText` to use the new method you added (passing in false for preserveEmptyLines and addRequiredIndicator) if you haven't already?
