### PR TITLE
Fixing details of the show program route for the North Star

### LINKED ISSUE #9455: Add test for the case when a user navigates to `/programs/programName` with a disabled program.
Add test for the case when a user navigates to /programs/programName with a disabled program.  See [this PR discussion](https://github.com/civiform/civiform/pull/9319#discussion_r1884720446).

### PR DESCRIPTION
**Pull request by melanie-exygy**
### Description

For the North Star, the program `show` route (`/programs/programName`), should lead to the new program overview page.  This is regardless of whether the user has started or completed an application for the program.  Essentially, we are replacing the old program details view.  This was already set up in PR #9319.  However, the current PR fixes 3 things:

- Clears the REDIRECT_TO key from the session after returning the program overview view.  This is so that the key won't be used again for the next redirect, for example, with the dev tools.
- Creates a new `showWithApplicantId` route that maintains the applicant id, this is for TIs applying on behalf of applicants.
- Navigates to the program overview even when there is an application in progress.  This distinguishes the `show` route from the `edit` or the `review` routes.

This PR also moves any tests from `northstar_program_deep_link.test.ts` that are still relevant into `northstar_program_overview.test.ts`.  Some of the tests were removed because they tested the "Create an account or sign in" modal, which used to pop up with the deep link before a guest user arrived on the program review page.  This modal won't show up before the program overview page.  We're only going to display it once the user clicks "Start an application" from the overview page.

### Instructions for manual testing

1. Turn on the North Star and disabled visibility condition flags.
2. Create a program if you don't have one.
3. Go to this URL `/programs/<your-program-name>` (the name needs to be lowercase and have dashes instead of spaces)
4. Note that this gets you to the program overview page (which is very bare bones at the moment).
5. Go back to the applicant home page.
6. Start applying to that program.
7. Go to `/programs/<your-program-name>` again.
8. Note that you get to the program overview page.
9. Submit your application.
10. Go to that same URL.
11. Note that you still get to the program overview page.
12. Log in as a trusted intermediary.
13. Create a client if you don't have one.
14. Click "View applications" on the client card.
15. Note that the URL now has the applicant id ("/applicants/35/programs").
16. Add the program slug to the end of that URL (`/applicants/35/programs/<your-program-name>`)
17.  Note that you get to the program overview page.

### Issue this is part of

Part of #9088

### Issue(s) this completes

Fixes #9455 ;

### CODE REVIEW

File: browser-test/src/support/civiform_fixtures.ts [hunk 1]
```diff
@@ -30,6 +31,7 @@ type CiviformFixtures = {
   adminSettings: AdminSettings
   applicantFileQuestion: ApplicantFileQuestion
   applicantProgramList: ApplicantProgramList
+  programOverview: ApplicantProgramOverview
```
Comment (gwendolyngoetz) [inline browser-test/src/support/civiform_fixtures.ts:34]:
```suggestion
  applicantProgramOverview: ApplicantProgramOverview
```

(blocking) Please rename so this matches up with the same naming pattern.

**Review by gwendolyngoetz — CHANGES_REQUESTED** [review]

File: browser-test/src/support/civiform_fixtures.ts (hunk 1 above)
Comment (melanie-exygy) [reply browser-test/src/support/civiform_fixtures.ts]: Good idea.  Done.

**Review by gwendolyngoetz — APPROVED** [review]
