### PR TITLE
Fix crash when ADFS sends a single group

### LINKED ISSUE #4295: AdClient crash when AD sends a single group
When attemping to log in via ADFS, it may be the case that ADFS only sends a single group as a string....or an empty string, if the person logging in is not a member of any relevant groups.   When an ADFS user like this attempts to log in, CiviForm errors out when an Exception.

CiviForm version 1.10.1

It would be ideal if we did not have to create special groups in AD for all city staff who would need to log in.  We'd really like to only designate a "Global Admin" group; and the rest of staff would still be allowed to log in....just not as global admins.

```
@80mg56lne - Internal server error, for (POST) [/callback/AdClient] ->                                                                                                                                                                    │
                                                                                                                                                                                                                                            │
play.api.UnexpectedException: Unexpected exception[ClassCastException: Attribute [group is of type class java.lang.String when we were expecting interface java.util.List]                                                                  │
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)                                                                                                                                     │
    at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)                                                                                                                                          │
    at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)                                                                                                                                       │
    at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)                                                                                                                                                    │
    at controllers.ErrorHandler.onServerError(ErrorHandler.java:100)                                                                                                                                                                        │
    at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)                                                                                                                                          │
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:436)                                                                                                                                                     │
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:428)                                                                                                                                                     │
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)                                                                                                                                                                  │
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)                                                                                                                                                 │
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)                                                                                                                                             │
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)                                                                                                                                                              │
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)                                                                                                                                                               │
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)                                                                                                                                                        │
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)                                                                                                                                                                        │
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)                                                                                                                              │
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)                                                                                                                                                                   │
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)                                                                                                                                                   │
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)                                                                                                                                                                     │
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)       
```

### PR DESCRIPTION
**Pull request by MichaelZetune**
### Description

Fixes an issue where if AD sends in a string instead of a list of groups (in the case of a single or 0 groups), we can handle it.

Previously, we could only handle:
* A list of groups returned by ADFS

Now we can handle:
* A list of groups
* A string that represents one group
* An empty string

### Testing

I've sent a Docker image of commit 0ca3a7 to Cliff at Bloomington and he verified it is working correctly.

### Issue(s) this completes

Fixes #4295

### CODE REVIEW

File: server/app/auth/oidc/admin/AdfsGroupAccessor.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+import java.util.List;
+import org.apache.commons.lang3.StringUtils;
+import org.pac4j.oidc.profile.OidcProfile;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public final class AdfsGroupAccessor {
+  private static final Logger logger = LoggerFactory.getLogger(AdfsGroupAccessor.class);
+
```
Comment (dkatzz) [inline server/app/auth/oidc/admin/AdfsGroupAccessor.java:11]: **suggestion:** Could you add a javadoc for this method and the class?

**Review by dkatzz — COMMENTED** [review]
Awesome job getting this working! Just a small comment about adding a couple of java docs.

File: server/app/auth/oidc/admin/AdfsGroupAccessor.java (hunk 1 above)
Comment (MichaelZetune) [reply server/app/auth/oidc/admin/AdfsGroupAccessor.java:15]: Done!

**Review by dkatzz — APPROVED** [review]
