### PR TITLE
Jessbumblebee/dateconversion3

### LINKED ISSUE #3607: Datetime Values in Data Exports
**Describe the bug**
Data exports display datetimes in UTC while the UI shows them localized. This causes confusion for end users.

**To Reproduce**
View an application in the admin pages `/admin/programs/:programId/applications` and note the date shows as PDT/PST.

image

Do a demographics export or a program export (csv or json). Look at the dates in the export file. They are UTC.

**Expected behavior**
Have the export localize the dates for a consistent end user experience.

### PR DESCRIPTION
**Pull request by jessbumblebee**
### Description

Change the format of creation and submission times in the data exports to be in local time
## Release notes:

Change data exports (CSV and Json) so that creation and submission time are recorded in local time rather than UST for consistency with the date and time displayed in the admin UI.

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

#### User visible changes

N/A

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

N/A

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

There is an additional change required to fix the issue (changing the time in the dropdown selector to PST/PDT)

### CODE REVIEW

File: server/app/services/export/CsvExporter.java [hunk 1]
```diff
@@ -70,13 +74,14 @@ public void exportRecord(
...
         case SUBMIT_TIME:
-          printer.print(
-              application.getSubmitTime() != null
-                  ? application.getSubmitTime().toString()
-                  : EMPTY_VALUE);
+          if (application.getSubmitTime() == null) {
+            printer.print(EMPTY_VALUE);
+            break;
+          }
+          printer.print(dateConverter.renderDateTimeDataOnly(application.getSubmitTime()));
```
Comment (gwendolyngoetz) [inline server/app/services/export/CsvExporter.java:84]: Can you move this into a private method of it's own? It's a little hard to read having multiple breaks in the same case.

File: server/app/services/DateConverter.java [hunk 2]
```diff
@@ -61,10 +61,19 @@ public Instant parseIso8601DateToStartOfDateInstant(String dateString) {
...
+    return dateTime.format(DateTimeFormatter.ofPattern("yyyy/MM/dd 'at' h:m a z"));
+  }
+
+  /**
+   * Formats an {@link Instant} to a date and time in the local time zone for the purpose of data
+   * exports (with no filler words).
+   */
+  public String renderDateTimeDataOnly(Instant time) {
+    ZonedDateTime dateTime = time.atZone(zoneId);
+    return dateTime.format(DateTimeFormatter.ofPattern("yyyy/MM/dd h:m:s a z"));
```
Comment (gwendolyngoetz) [inline server/app/services/DateConverter.java:76]: I think the minute and second need to be mm and ss so they have the 0 prepended for single digits.

File: server/app/services/export/CsvExporter.java (hunk 1 above)
Comment (jessbumblebee) [reply server/app/services/export/CsvExporter.java:84]: Good point. Actually, I've changed it to an if...else, which looks more readable to me and keeps the logic in place.
Let me know in case it still looks a bit cryptic.

File: server/app/services/DateConverter.java (hunk 2 above)
Comment (jessbumblebee) [reply server/app/services/DateConverter.java]: Good catch

**Review by gwendolyngoetz — CHANGES_REQUESTED** [review]
LGTM. Just update the `Release notes` description and I'll approve.

**Comment by jessbumblebee** [comment]
Done

**Review by gwendolyngoetz — APPROVED** [review]
